"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Button, Card, CardContent, CardHeader, CardTitle, ErrorState, PageHeader, SkeletonLoader } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { resolveWorkspaceContext } from "@/lib/supabase/workspace";

type Employee={id:string;employee_number:string;name:string;position_title:string;employment_status:string;hourly_rate:number|null;overtime_multiplier:number|null;fringe_hourly:number|null;provider:string|null;provider_employee_id:string|null;payroll_ready:boolean};
type Period={id:string;period_start:string;period_end:string;pay_date:string;status:string;regular_hours:number;overtime_hours:number;regular_pay:number;overtime_pay:number;fringe_pay:number;gross_pay:number;approved_at:string|null;exported_at:string|null};
type Workspace={employees:Employee[];periods:Period[];approved_unprocessed_hours:number;employees_needing_rates:number};
type RpcResult<T>={data:T|null;error:{message:string}|null};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const today=()=>new Date().toISOString().slice(0,10);
function mondayOfCurrentWeek(){const d=new Date();const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d.toISOString().slice(0,10);}
function plusDays(date:string,days:number){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);}

export default function PayrollWorkspace(){
 const supabase=useMemo(()=>createClient(),[]);const[companyId,setCompanyId]=useState("");const[data,setData]=useState<Workspace|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const[start,setStart]=useState(mondayOfCurrentWeek());const[end,setEnd]=useState(plusDays(mondayOfCurrentWeek(),6));const[payDate,setPayDate]=useState(plusDays(mondayOfCurrentWeek(),11));
 const load=useCallback(async()=>{if(!supabase)return;const workspace=await resolveWorkspaceContext(supabase);if(!workspace.context){setError(workspace.errorMessage||"Unable to resolve workspace.");setLoading(false);return;}setCompanyId(workspace.context.companyId);const result=await supabase.rpc("get_payroll_workspace" as never,{p_company_id:workspace.context.companyId} as never) as unknown as RpcResult<Workspace>;if(result.error||!result.data){setError(result.error?.message||"Unable to load payroll.");setLoading(false);return;}setData(result.data);setError(null);setLoading(false);},[supabase]);
 useEffect(()=>{queueMicrotask(()=>void load());},[load]);
 async function buildPeriod(e:FormEvent){e.preventDefault();if(!supabase||!companyId)return;setBusy(true);setError(null);const result=await supabase.rpc("build_weekly_payroll" as never,{p_company_id:companyId,p_period_start:start,p_period_end:end,p_pay_date:payDate} as never) as unknown as RpcResult<string>;if(result.error)setError(result.error.message);else await load();setBusy(false);}
 async function changeStatus(id:string,status:string){if(!supabase||!companyId)return;setBusy(true);setError(null);const result=await supabase.rpc("set_payroll_status" as never,{p_company_id:companyId,p_period_id:id,p_status:status} as never) as unknown as RpcResult<null>;if(result.error)setError(result.error.message);else await load();setBusy(false);}
 async function saveRate(employee:Employee,form:FormData){if(!supabase||!companyId)return;setBusy(true);setError(null);const result=await supabase.rpc("save_payroll_employee_setting" as never,{p_company_id:companyId,p_employee_id:employee.id,p_hourly_rate:Number(form.get("hourly_rate")),p_overtime_multiplier:Number(form.get("overtime_multiplier")),p_fringe_hourly:Number(form.get("fringe_hourly")),p_provider:String(form.get("provider")||""),p_provider_employee_id:String(form.get("provider_employee_id")||"")} as never) as unknown as RpcResult<null>;if(result.error)setError(result.error.message);else await load();setBusy(false);}
 if(loading)return <div className="container-content space-y-5"><SkeletonLoader className="h-20 w-full"/><SkeletonLoader className="h-40 w-full"/><SkeletonLoader className="h-80 w-full"/></div>;
 if(error&&!data)return <ErrorState title="Unable to load Payroll" description={error}/>;
 const periods=data?.periods||[],employees=data?.employees||[];const latest=periods[0];
 return <div className="container-content space-y-[var(--space-section)]"><PageHeader compact eyebrow="FINANCIAL · WORKFORCE" title="Payroll & Workforce Pay" description="Turn approved B.O.S. time into controlled weekly payroll, preserve job-cost evidence, and prepare approved payroll for an external payroll provider."/>
 {error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm">{error}</div>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Approved Unprocessed Time" value={`${Number(data?.approved_unprocessed_hours||0).toFixed(2)} hrs`} detail="Approved time not yet in payroll"/><Metric label="Payroll Ready" value={`${employees.filter(e=>e.payroll_ready).length}/${employees.length}`} detail="Active employees with pay settings"/><Metric label="Latest Gross Payroll" value={money.format(Number(latest?.gross_pay||0))} detail={latest?`${latest.period_start} – ${latest.period_end}`:"No payroll built yet"}/><Metric label="Latest Status" value={latest?.status?.toUpperCase()||"—"} detail="Approval/export state"/></div>
 <Card variant="elevated"><CardHeader><CardTitle>Build Weekly Payroll</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-[var(--bos-text-secondary)]">B.O.S. uses only approved workforce time. Weekly overtime is calculated after 40 hours. This workspace calculates gross wages and job-cost evidence; it does not file taxes or move money.</p><form onSubmit={buildPeriod} className="grid gap-3 md:grid-cols-4"><DateField label="Period Start" value={start} onChange={v=>{setStart(v);setEnd(plusDays(v,6));}}/><DateField label="Period End" value={end} onChange={setEnd}/><DateField label="Pay Date" value={payDate} onChange={setPayDate}/><div className="flex items-end"><Button type="submit" disabled={busy||Number(data?.employees_needing_rates||0)>0} className="w-full">{busy?"Working…":"Build Payroll"}</Button></div></form>{Number(data?.employees_needing_rates||0)>0&&<p className="mt-3 text-sm font-semibold text-amber-500">Set payroll rates for {data?.employees_needing_rates} active employee(s) before building payroll.</p>}</CardContent></Card>
 <Card variant="elevated"><CardHeader><CardTitle>Employee Pay Setup</CardTitle></CardHeader><CardContent className="space-y-3">{employees.length===0?<p className="py-6 text-sm text-[var(--bos-text-secondary)]">No active employees are available.</p>:employees.map(employee=><form key={employee.id} action={form=>void saveRate(employee,form)} className="grid gap-3 rounded-xl border border-[var(--bos-border-default)] p-4 md:grid-cols-[1.4fr_repeat(5,1fr)_auto]"><div><p className="font-semibold">{employee.name}</p><p className="text-xs text-[var(--bos-text-secondary)]">{employee.employee_number} · {employee.position_title}</p></div><SmallInput name="hourly_rate" label="Hourly" type="number" step="0.01" defaultValue={employee.hourly_rate??0}/><SmallInput name="overtime_multiplier" label="OT ×" type="number" step="0.01" defaultValue={employee.overtime_multiplier??1.5}/><SmallInput name="fringe_hourly" label="Fringe/hr" type="number" step="0.01" defaultValue={employee.fringe_hourly??0}/><SmallInput name="provider" label="Provider" defaultValue={employee.provider??""} placeholder="ADP / Gusto"/><SmallInput name="provider_employee_id" label="Provider ID" defaultValue={employee.provider_employee_id??""}/><div className="flex items-end"><Button type="submit" variant="secondary" disabled={busy}>Save</Button></div></form>)}</CardContent></Card>
 <Card variant="elevated"><CardHeader><CardTitle>Payroll History</CardTitle></CardHeader><CardContent className="overflow-x-auto">{periods.length===0?<p className="py-8 text-center text-sm text-[var(--bos-text-secondary)]">No payroll periods yet.</p>:<table className="min-w-[900px] w-full"><thead><tr className="text-left text-xs uppercase text-[var(--bos-text-muted)]"><th className="p-2">Period</th><th className="p-2">Pay Date</th><th className="p-2">Status</th><th className="p-2 text-right">Regular</th><th className="p-2 text-right">OT</th><th className="p-2 text-right">Gross</th><th className="p-2 text-right">Actions</th></tr></thead><tbody>{periods.map(p=><tr key={p.id} className="border-t border-[var(--bos-border-default)]"><td className="p-2 font-semibold">{p.period_start} – {p.period_end}</td><td className="p-2">{p.pay_date}</td><td className="p-2 uppercase">{p.status}</td><td className="p-2 text-right">{Number(p.regular_hours).toFixed(2)} hrs</td><td className="p-2 text-right">{Number(p.overtime_hours).toFixed(2)} hrs</td><td className="p-2 text-right font-bold">{money.format(Number(p.gross_pay))}</td><td className="p-2"><div className="flex justify-end gap-2">{p.status==="draft"&&<Button size="sm" variant="secondary" disabled={busy} onClick={()=>void changeStatus(p.id,"review")}>Review</Button>}{p.status==="review"&&<Button size="sm" disabled={busy} onClick={()=>void changeStatus(p.id,"approved")}>Approve</Button>}{p.status==="approved"&&<Button size="sm" variant="secondary" disabled={busy} onClick={()=>void changeStatus(p.id,"exported")}>Mark Exported</Button>}</div></td></tr>)}</tbody></table>}</CardContent></Card>
 </div>;
}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <Card variant="elevated"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-[var(--bos-text-muted)]">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-sm text-[var(--bos-text-secondary)]">{detail}</p></CardContent></Card>}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm font-semibold">{label}<input type="date" required value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--bos-border-default)] bg-[var(--bos-bg-panel)] px-3 py-2.5"/></label>}
function SmallInput(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const{label,...input}=props;return <label className="text-xs font-semibold">{label}<input {...input} className="mt-1 w-full rounded-lg border border-[var(--bos-border-default)] bg-[var(--bos-bg-panel)] px-2 py-2 text-sm"/></label>}
