import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const projectPage = readFileSync("app/(app)/projects/[id]/page.tsx", "utf8");
const workspace = readFileSync("components/projects/workspace/project-work-workspace.tsx", "utf8");
const executionBoard = readFileSync("components/projects/workspace/project-work-execution-board.tsx", "utf8");
const dependencyPanel = readFileSync("components/projects/workspace/project-task-dependencies-panel.tsx", "utf8");
const operationsTimeline = readFileSync("components/projects/workspace/project-work-operations-timeline.tsx", "utf8");
const dailyReportPage = readFileSync("app/(app)/daily-reports/new/page.tsx", "utf8");
const dailyReportHook = readFileSync("lib/daily-reports/use-daily-report.ts", "utf8");

assert.match(projectPage, /activeTab === "tasks"[\s\S]*?<ProjectWorkWorkspace/);
assert.match(projectPage, /tasks=\{workspace\.tasks\}/);
assert.match(workspace, /\.from\("tasks"\)[\s\S]*?\.insert\(\{/);
assert.match(workspace, /company_id: companyId/);
assert.match(workspace, /project_id: projectId/);
assert.match(workspace, /phase_id: selectedPhaseId/);
assert.match(executionBoard, /filters\.status/);
assert.match(executionBoard, /filters\.assignee/);
assert.match(executionBoard, /filters\.search/);
assert.match(executionBoard, /filters\.sort/);
assert.match(executionBoard, /<ProjectTaskDependenciesPanel selectedTaskId=\{selectedTaskId\} tasks=\{tasks\} t=\{t\}/);
assert.match(dependencyPanel, /\.from\("task_dependencies"\)/);
assert.match(dependencyPanel, /task_id: selectedTaskId/);
assert.match(dependencyPanel, /depends_on_task_id: candidateId/);
assert.match(dependencyPanel, /dependency_type: dependencyType/);
assert.match(dependencyPanel, /wouldCreateCycle/);
assert.match(dependencyPanel, /\.delete\(\)/);
assert.match(dependencyPanel, /\.update\(\{ dependency_type: nextType \}\)/);
assert.match(workspace, /\/schedule\?projectId=\$\{projectId\}/);
assert.match(workspace, /\/daily-reports\/new\?projectId=\$\{projectId\}&projectName=/);
assert.match(workspace, /\?tab=inspections/);
assert.match(workspace, /#punch-list/);
assert.doesNotMatch(operationsTimeline, /\?tab=work/);
assert.match(operationsTimeline, /loadDailyLogEvents/);
assert.match(operationsTimeline, /\.from\("workflow_events"\)[\s\S]*?\.eq\("reference_entity", "daily_report"\)/);
assert.match(operationsTimeline, /\.eq\("payload->>project_id", projectId\)/);
assert.match(operationsTimeline, /loadInspectionEvents/);
assert.match(operationsTimeline, /\.from\("project_inspections"\)[\s\S]*?\.eq\("project_id", projectId\)/);
assert.match(operationsTimeline, /\.\.\.dailyLogEvents/);
assert.match(operationsTimeline, /\.\.\.inspectionEvents/);
assert.match(dailyReportPage, /searchParams\.get\("projectId"\)/);
assert.match(dailyReportHook, /projectId: initialProjectId/);

console.log("Project Work operationalization contract passed.");
