import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const read = (file: string) => fs.readFileSync(path.resolve(process.cwd(), file), "utf8");
const page = read("app/(app)/projects/[id]/page.tsx");
const overview = read("components/projects/workspace/project-command-center-foundation.tsx");
const overviewLayout = read("components/projects/workspace/project-command-center-foundation.module.css");
const header = read("components/projects/workspace/project-workspace-header.tsx");
const headerWeather = read("components/projects/workspace/project-header-weather-strip.tsx");
const workWorkspace = read("components/projects/workspace/project-work-workspace.tsx");
const executionBoard = read("components/projects/workspace/project-work-execution-board.tsx");
const topCommandLayout = read("app/top-command-layout.css");

assert.ok(!page.includes("<ProjectWorkspaceHero"), "the oversized photo/weather hero stays out of the project landing view");
assert.ok(!page.includes("<ProjectKpiGrid"), "the duplicate KPI strip stays out of the project landing view");
assert.ok(overview.includes('data-project-overview="header-jobsite-clean"'), "the overview declares its cleaned header-jobsite hierarchy");
assert.ok(overview.includes("Scope of Work"));
assert.ok(overview.includes("Today's Priorities"));
assert.ok(overview.includes("Project Health"));
assert.ok(overview.includes("Next 7 Days"));
assert.ok(overview.includes("styles.detailsFirst"), "project details opt into the details-first overview order");
assert.ok(overviewLayout.includes("flex-direction: column"), "the overview parent becomes an ordered vertical stack");
assert.ok(overviewLayout.includes(":not(.detailsFirst)"), "the operating-system panel is ordered after the project details");
assert.ok(!overview.includes('label="Job site"'), "job-site address is not duplicated inside Project Team");
assert.ok(overview.includes('sm:grid-cols-3'), "Project Team uses three compact detail cards after job-site removal");
assert.ok(!overview.includes("<LocationForecastCard"), "the full-width weather/map card no longer consumes the project overview");
assert.ok(!overview.includes('data-project-jobsite-intelligence="primary"'));
assert.ok(header.includes("<WorkspaceHeader\n        compact"), "the project header uses the compact layout");
assert.ok(header.includes("<ProjectHeaderWeatherStrip />"), "weather and map sit directly with the project header");
assert.ok(header.includes('data-project-header-with-jobsite-intelligence="true"'));
assert.ok(headerWeather.includes('data-project-header-jobsite-intelligence="true"'));
assert.ok(headerWeather.includes("lg:grid-cols-[1.05fr_1fr_0.9fr]"), "desktop jobsite intelligence uses a compact horizontal strip");
assert.ok(headerWeather.includes("min-h-[112px]"), "weather and map stay short instead of stretching vertically");

assert.ok(!workWorkspace.includes('xl:grid-cols-[280px_minmax(0,1fr)_340px]'), "Tasks must not force the board between two fixed desktop rails");
assert.ok(workWorkspace.includes('xl:grid-cols-[240px_minmax(0,1fr)]'), "laptop Tasks layout reserves the dominant width for the execution board");
assert.ok(workWorkspace.includes('md:grid-cols-2 xl:col-span-2'), "supporting Tasks panels reflow beneath the board instead of squeezing it");
assert.ok(workWorkspace.includes('hidden md:block md:col-span-2 min-[1800px]:hidden'), "tablet and laptop users receive usable inline task details");
assert.ok(executionBoard.includes('data-testid="execution-board-scroll-region"'), "the execution board exposes its scroll-safe desktop region");
assert.ok(executionBoard.includes('min-w-[1040px] grid-cols-4'), "kanban columns retain a readable minimum width");
assert.ok(executionBoard.includes('overflow-x-auto'), "desktop kanban overflow scrolls instead of clipping or compressing cards");
assert.ok(!executionBoard.includes('lg:grid-cols-[minmax(0,1fr)_220px_220px]'), "filter controls must not use fixed widths inside a narrow board parent");
assert.ok(topCommandLayout.includes('@media (min-width: 640px) and (max-width: 1023px)'), "the shared shell has an explicit tablet/laptop transition range");
assert.ok(topCommandLayout.includes('flex-direction: column !important'), "tablet header context and utilities stack instead of colliding");
assert.ok(topCommandLayout.includes('flex-wrap: wrap !important'), "tablet header utilities can wrap safely");
assert.ok(topCommandLayout.includes('@media (min-width: 1280px) {'), "Tasks has a stable desktop correction that is not capped at an arbitrary viewport width");
assert.ok(!topCommandLayout.includes('@media (min-width: 1280px) and (max-width: 1799px)'), "Tasks must not re-enable a squeezed three-column layout at wide viewport breakpoints");
assert.ok(topCommandLayout.includes('.grid:has(> :nth-child(2) [data-testid="execution-board-scroll-region"]) {'), "Tasks explicitly corrects the StaggerGroup grid container");
assert.ok(topCommandLayout.includes('grid-template-columns: 260px minmax(0, 1fr) !important'), "Execution Board keeps the dominant desktop width regardless of shell width");
assert.ok(topCommandLayout.includes('.grid:has(> :nth-child(2) [data-testid="execution-board-scroll-region"]) > :nth-child(3)'), "Tasks corrects the StaggerGroup wrapper that owns supporting-panel placement");
assert.ok(topCommandLayout.includes('grid-column: 1 / -1'), "Tasks supporting panels span the full desktop row instead of a narrow rail");

console.log("+ project overview, Tasks workspace, and shared responsive layout invariants hold across desktop shell widths");
