import type { MissionScenario, MissionScenarioId } from "./types";

export const missionControlScenarios: Record<MissionScenarioId, MissionScenario> = {
  "normal-operations": {
    id: "normal-operations",
    name: "Normal Operations",
    companyState: {
      greeting: "Good morning, leadership team.",
      companyName: "Bango Construction Group",
      stateLabel: "Stable flow across active work",
      summary: "Most projects are moving as planned with low unresolved friction and strong field sync.",
      primaryOrionStatement: "Orion sees a schedule optimization opportunity on two crews without critical exposure.",
      scenarioLabel: "Normal Operations",
      freshness: "live",
      completenessPercent: 96,
      healthScore: 88,
      trend: "+3 versus last 24 hours",
      limitations: [
        "One rural delivery feed reports every 15 minutes instead of real-time.",
      ],
      dimensions: [
        { id: "dim-1", label: "Project Flow", value: "21 of 24 on-target", trend: "Steady", status: "healthy", freshness: "live" },
        { id: "dim-2", label: "Crew Synchronization", value: "94%", trend: "+2 today", status: "info", freshness: "live" },
        { id: "dim-3", label: "Equipment Reliability", value: "98.1%", trend: "Stable", status: "healthy", freshness: "live" },
        { id: "dim-4", label: "Critical Exposure", value: "0 active", trend: "No escalation", status: "healthy", freshness: "live" },
      ],
    },
    priorities: [
      {
        id: "nor-orion-1",
        status: "orion",
        kind: "recommendation",
        observation: "Two finishing crews are completing work early in adjacent windows.",
        whyItMatters: "Coordinating handoff can reduce idle time before inspection prep.",
        evidence: "Dispatch logs from Northpoint and Project Oak for the last two shifts.",
        evidenceQuality: "High",
        confidenceLabel: "Confidence 0.84",
        limitation: "Weather variance after 16:00 is not included in this fixture.",
        recommendedNextStep: "Preview a synchronized handoff plan for this afternoon.",
        approvalBoundary: "Requires superintendent approval before crew assignment changes.",
      },
      {
        id: "nor-orion-2",
        status: "info",
        kind: "fact",
        observation: "Equipment watchlist remains below baseline threshold.",
        whyItMatters: "Lower equipment contention supports schedule reliability.",
        evidence: "Fleet monitoring snapshot updated at 09:20.",
        evidenceQuality: "Medium",
        confidenceLabel: "Confidence 0.76",
        limitation: "One forklift telemetry feed is delayed by 12 minutes.",
        recommendedNextStep: "Inspect details for the delayed feed before noon.",
        approvalBoundary: "No operational write action is permitted from this view.",
      },
    ],
    twinNodes: [
      { id: "n1", label: "Northpoint", group: "project", status: "healthy", x: 12, y: 20, detail: "Concrete and MEP handoff on schedule." },
      { id: "n2", label: "Crew Alpha", group: "crew", status: "info", x: 38, y: 18, detail: "Crew fully staffed and synchronized." },
      { id: "n3", label: "Crane Cluster", group: "equipment", status: "healthy", x: 66, y: 22, detail: "No active contention across planned lifts." },
      { id: "n4", label: "Dispatch Control", group: "operations", status: "orion", x: 42, y: 54, detail: "Orion monitoring handoff sequencing opportunities." },
      { id: "n5", label: "Oak Schedule", group: "schedule", status: "info", x: 74, y: 58, detail: "Two-hour buffer remains on critical path." },
    ],
    twinLinks: [
      { id: "l1", from: "n1", to: "n2", relation: "staffing link" },
      { id: "l2", from: "n2", to: "n3", relation: "equipment link" },
      { id: "l3", from: "n2", to: "n4", relation: "operations link" },
      { id: "l4", from: "n4", to: "n5", relation: "schedule link" },
    ],
    metrics: [
      { id: "m1", label: "Active projects", value: "24", status: "healthy", trend: "+1 week-over-week", freshness: "live" },
      { id: "m2", label: "Crews synchronized", value: "42", status: "info", trend: "+3 since yesterday", freshness: "live" },
      { id: "m3", label: "Equipment under watch", value: "2", status: "attention", trend: "Down from 4", freshness: "live" },
      { id: "m4", label: "On-time rate", value: "93%", status: "healthy", trend: "+2 points", freshness: "live" },
      { id: "m5", label: "Data completeness", value: "96%", status: "info", trend: "Stable", freshness: "live" },
    ],
    timeline: [
      { id: "t1", at: "07:30", type: "crew-check-in", entity: "Crew Alpha", status: "healthy", detail: "Check-in completed at Northpoint.", source: "Field attendance log", freshness: "live" },
      { id: "t2", at: "08:10", type: "delivery-confirmation", entity: "Rebar Delivery", status: "info", detail: "Delivery confirmed at Gate B.", source: "Logistics scan record", freshness: "live" },
      { id: "t3", at: "09:05", type: "inspection-update", entity: "QA Packet", status: "info", detail: "Inspection packet moved to review-ready.", source: "Inspection checklist", freshness: "live" },
      { id: "t4", at: "10:15", type: "orion-evidence-update", entity: "Handoff Model", status: "orion", detail: "Orion refreshed handoff confidence with new dispatch evidence.", source: "Orion evidence set v3", freshness: "live" },
    ],
    actions: [
      { id: "a1", title: "Review handoff sequence", purpose: "Protect continuous flow between finishing and inspection prep.", owner: "Project Manager", due: "Today 13:00", urgency: "moderate", status: "attention", evidenceSource: "Dispatch and schedule logs", approvalRequired: "Superintendent approval required", previewLabel: "Preview plan" },
      { id: "a2", title: "Inspect delayed telemetry", purpose: "Confirm reliability of one delayed equipment feed.", owner: "Operations Analyst", due: "Today 11:30", urgency: "low", status: "info", evidenceSource: "Fleet polling monitor", approvalRequired: "No write action from Mission Control", previewLabel: "Inspect details" },
    ],
  },
  "weather-risk": {
    id: "weather-risk",
    name: "Weather Risk",
    companyState: {
      greeting: "Good morning, leadership team.",
      companyName: "Bango Construction Group",
      stateLabel: "Stable with weather-sensitive schedule pressure",
      summary: "Portfolio remains controlled, but one weather event may compress afternoon sequencing.",
      primaryOrionStatement: "Orion forecasts a moderate delay risk for one project if wind thresholds rise after 15:00.",
      scenarioLabel: "Weather Risk",
      freshness: "partial",
      completenessPercent: 89,
      healthScore: 78,
      trend: "-2 versus last 24 hours",
      limitations: [
        "Wind telemetry from Ridgeview site is delayed by 20 minutes.",
        "No financial-loss estimate is generated in this fixture scenario.",
      ],
      dimensions: [
        { id: "dim-1", label: "Project Flow", value: "19 of 24 on-target", trend: "One project at weather risk", status: "attention", freshness: "partial" },
        { id: "dim-2", label: "Crew Synchronization", value: "92%", trend: "Slight decline", status: "info", freshness: "live" },
        { id: "dim-3", label: "Equipment Reliability", value: "97.4%", trend: "Stable", status: "healthy", freshness: "live" },
        { id: "dim-4", label: "Critical Exposure", value: "0 active", trend: "No critical events", status: "healthy", freshness: "live" },
      ],
    },
    priorities: [
      {
        id: "wr-orion-1",
        status: "attention",
        kind: "prediction",
        observation: "Wind profile may exceed crane threshold during planned exterior lift window.",
        whyItMatters: "A delayed lift can push one dependency into tomorrow morning.",
        evidence: "Weather feed trend plus current crane schedule sequence.",
        evidenceQuality: "Moderate",
        confidenceLabel: "Confidence 0.68",
        limitation: "Ridgeview wind feed is partially stale.",
        recommendedNextStep: "Review alternate lift window and update sequencing options.",
        approvalBoundary: "Shift changes require PM and superintendent approval.",
      },
      {
        id: "wr-orion-2",
        status: "orion",
        kind: "recommendation",
        observation: "Pre-stage interior tasks to preserve crew productivity if exterior lift slips.",
        whyItMatters: "Maintains utilization and reduces schedule disruption.",
        evidence: "Current task graph and available interior scope.",
        evidenceQuality: "Medium",
        confidenceLabel: "Confidence 0.73",
        limitation: "Interior readiness checklist for one zone is unavailable in this fixture.",
        recommendedNextStep: "Preview fallback task sequence for Crew Delta.",
        approvalBoundary: "Execution remains manual outside this advisory surface.",
      },
    ],
    twinNodes: [
      { id: "w1", label: "Ridgeview", group: "project", status: "attention", x: 14, y: 22, detail: "Weather-sensitive lift in afternoon window." },
      { id: "w2", label: "Crew Delta", group: "crew", status: "info", x: 40, y: 18, detail: "Crew available for fallback interior tasks." },
      { id: "w3", label: "Tower Crane", group: "equipment", status: "attention", x: 66, y: 26, detail: "Wind threshold watch active." },
      { id: "w4", label: "Operations Board", group: "operations", status: "orion", x: 42, y: 56, detail: "Advisory sequencing options prepared." },
      { id: "w5", label: "Lift Sequence", group: "schedule", status: "stale", x: 74, y: 60, detail: "Latest weather-adjusted sequence pending refresh." },
    ],
    twinLinks: [
      { id: "wl1", from: "w1", to: "w2", relation: "crew assignment" },
      { id: "wl2", from: "w2", to: "w3", relation: "equipment dependency" },
      { id: "wl3", from: "w3", to: "w5", relation: "schedule dependency" },
      { id: "wl4", from: "w4", to: "w5", relation: "orion advisory" },
    ],
    metrics: [
      { id: "wm1", label: "Active projects", value: "24", status: "healthy", trend: "Unchanged", freshness: "live" },
      { id: "wm2", label: "Crews synchronized", value: "40", status: "info", trend: "-2 since yesterday", freshness: "live" },
      { id: "wm3", label: "Weather-sensitive tasks", value: "5", status: "attention", trend: "+1 this shift", freshness: "partial" },
      { id: "wm4", label: "On-time rate", value: "90%", status: "attention", trend: "-1 point", freshness: "partial" },
      { id: "wm5", label: "Data completeness", value: "89%", status: "stale", trend: "One feed delayed", freshness: "partial" },
    ],
    timeline: [
      { id: "wt1", at: "07:20", type: "crew-check-in", entity: "Crew Delta", status: "info", detail: "Crew check-in completed at Ridgeview.", source: "Field attendance log", freshness: "live" },
      { id: "wt2", at: "08:40", type: "schedule-adjustment", entity: "Lift Sequence", status: "attention", detail: "Alternate lift slot drafted due to wind forecast.", source: "Schedule planner note", freshness: "partial" },
      { id: "wt3", at: "09:25", type: "inspection-update", entity: "Zone C prep", status: "unknown", detail: "Inspection readiness status not yet reported.", source: "Inspection checklist feed", freshness: "unknown" },
      { id: "wt4", at: "10:05", type: "orion-evidence-update", entity: "Weather model", status: "orion", detail: "Orion updated risk confidence with latest wind trend.", source: "Orion evidence set v4", freshness: "partial" },
    ],
    actions: [
      { id: "wa1", title: "Inspect alternate lift plan", purpose: "Maintain flow if wind limits crane operations.", owner: "Scheduler", due: "Today 12:45", urgency: "high", status: "attention", evidenceSource: "Weather trend + lift dependency map", approvalRequired: "PM and superintendent approval required", previewLabel: "Inspect details" },
      { id: "wa2", title: "Review interior fallback scope", purpose: "Reduce potential idle time for Crew Delta.", owner: "Field Ops", due: "Today 13:15", urgency: "moderate", status: "orion", evidenceSource: "Task readiness board", approvalRequired: "No auto-dispatch in lab mode", previewLabel: "Review" },
    ],
  },
  "labor-shortage": {
    id: "labor-shortage",
    name: "Labor Shortage",
    companyState: {
      greeting: "Good morning, leadership team.",
      companyName: "Bango Construction Group",
      stateLabel: "Targeted labor pressure across one corridor",
      summary: "One crew is unavailable and one upcoming project has staffing risk; other operations remain stable.",
      primaryOrionStatement: "Orion identifies a staffing conflict with moderate confidence and clear data limitations.",
      scenarioLabel: "Labor Shortage",
      freshness: "partial",
      completenessPercent: 84,
      healthScore: 72,
      trend: "-4 versus last 24 hours",
      limitations: [
        "One subcontractor roster feed is unavailable.",
        "Shift-swap confirmations are stale for one site.",
      ],
      dimensions: [
        { id: "dim-1", label: "Project Flow", value: "17 of 24 on-target", trend: "One upcoming milestone at risk", status: "attention", freshness: "partial" },
        { id: "dim-2", label: "Crew Synchronization", value: "86%", trend: "Declining", status: "critical", freshness: "partial" },
        { id: "dim-3", label: "Equipment Reliability", value: "97.9%", trend: "Stable", status: "healthy", freshness: "live" },
        { id: "dim-4", label: "Critical Exposure", value: "1 active", trend: "Staffing conflict", status: "critical", freshness: "live" },
      ],
    },
    priorities: [
      {
        id: "ls-orion-1",
        status: "critical",
        kind: "prediction",
        observation: "Tomorrow's concrete prep may miss start window due to one unavailable crew.",
        whyItMatters: "Missed prep window can delay a dependent inspection and schedule handoff.",
        evidence: "Crew availability feed, assignment roster, and schedule dependencies.",
        evidenceQuality: "Moderate",
        confidenceLabel: "Confidence 0.66",
        limitation: "Subcontractor roster feed is unavailable for one scope.",
        recommendedNextStep: "Review contingency staffing options and confirm supervisor coverage.",
        approvalBoundary: "Any assignment changes require operations manager approval.",
      },
      {
        id: "ls-orion-2",
        status: "orion",
        kind: "recommendation",
        observation: "A short-term shift rebalance could reduce tomorrow's staffing exposure.",
        whyItMatters: "Rebalancing preserves milestone readiness without overloading one crew.",
        evidence: "Current labor allocation and near-term project demand.",
        evidenceQuality: "Medium",
        confidenceLabel: "Confidence 0.71",
        limitation: "Overtime tolerance constraints are not included in this fixture.",
        recommendedNextStep: "Preview staffing rebalance plan for next-day window.",
        approvalBoundary: "No direct dispatch or assignment writes from this screen.",
      },
    ],
    twinNodes: [
      { id: "s1", label: "Harbor Build", group: "project", status: "attention", x: 12, y: 20, detail: "Upcoming staffing-sensitive milestone." },
      { id: "s2", label: "Crew Echo", group: "crew", status: "unavailable", x: 38, y: 18, detail: "Crew unavailable for next shift window." },
      { id: "s3", label: "Rebar Fleet", group: "equipment", status: "healthy", x: 66, y: 22, detail: "Equipment capacity is available." },
      { id: "s4", label: "Ops Coordination", group: "operations", status: "orion", x: 42, y: 56, detail: "Contingency staffing advisory in progress." },
      { id: "s5", label: "Milestone Chain", group: "schedule", status: "critical", x: 74, y: 60, detail: "One dependency likely to slip without labor adjustment." },
      { id: "s6", label: "Subcontract Feed", group: "crew", status: "unknown", x: 20, y: 60, detail: "Roster feed unavailable in this fixture snapshot." },
    ],
    twinLinks: [
      { id: "sl1", from: "s1", to: "s2", relation: "staffing dependency" },
      { id: "sl2", from: "s2", to: "s5", relation: "schedule risk" },
      { id: "sl3", from: "s3", to: "s5", relation: "equipment support" },
      { id: "sl4", from: "s4", to: "s5", relation: "orion recommendation" },
      { id: "sl5", from: "s6", to: "s2", relation: "missing roster signal" },
    ],
    metrics: [
      { id: "sm1", label: "Active projects", value: "24", status: "healthy", trend: "Unchanged", freshness: "live" },
      { id: "sm2", label: "Crews synchronized", value: "37", status: "critical", trend: "-5 since yesterday", freshness: "partial" },
      { id: "sm3", label: "Crew unavailable", value: "1", status: "critical", trend: "New today", freshness: "live" },
      { id: "sm4", label: "Upcoming staffing risk", value: "1 project", status: "attention", trend: "Next 24h", freshness: "partial" },
      { id: "sm5", label: "Data completeness", value: "84%", status: "unknown", trend: "Roster feed unavailable", freshness: "unknown" },
    ],
    timeline: [
      { id: "st1", at: "07:10", type: "crew-check-in", entity: "Crew Echo", status: "critical", detail: "Crew marked unavailable for next shift.", source: "Crew availability board", freshness: "live" },
      { id: "st2", at: "08:05", type: "schedule-adjustment", entity: "Harbor milestone", status: "attention", detail: "Milestone moved to risk watch due to staffing gap.", source: "Schedule coordinator note", freshness: "partial" },
      { id: "st3", at: "09:00", type: "delivery-confirmation", entity: "Rebar delivery", status: "healthy", detail: "Material delivery confirmed on time.", source: "Logistics scan record", freshness: "live" },
      { id: "st4", at: "10:20", type: "orion-evidence-update", entity: "Staffing model", status: "orion", detail: "Orion refreshed staffing risk estimate with latest assignments.", source: "Orion evidence set v5", freshness: "partial" },
    ],
    actions: [
      { id: "sa1", title: "Review staffing contingency", purpose: "Protect tomorrow's prep milestone against crew unavailability.", owner: "Operations Manager", due: "Today 14:00", urgency: "high", status: "critical", evidenceSource: "Crew roster and schedule dependency map", approvalRequired: "Operations manager approval required", previewLabel: "Review" },
      { id: "sa2", title: "Preview shift rebalance", purpose: "Reduce labor conflict exposure without immediate writes.", owner: "Project Superintendent", due: "Today 15:00", urgency: "moderate", status: "orion", evidenceSource: "Orion staffing recommendation", approvalRequired: "Manual assignment changes only", previewLabel: "Preview plan" },
    ],
  },
};

export const missionScenarioOrder: MissionScenarioId[] = [
  "normal-operations",
  "weather-risk",
  "labor-shortage",
];
