import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const migration = readFileSync(resolve(root, "supabase/migrations/20260813130000_blueprint_operational_links.sql"), "utf8");
const takeoffMigration = readFileSync(resolve(root, "supabase/migrations/20260813143000_blueprint_estimate_takeoffs.sql"), "utf8");
const changeOrderMigration = readFileSync(resolve(root, "supabase/migrations/20260813160000_blueprint_change_order_initiation.sql"), "utf8");
const workforceMigration = readFileSync(resolve(root, "supabase/migrations/20260813173000_blueprint_workforce_assignments.sql"), "utf8");
const punchMigration = readFileSync(resolve(root, "supabase/migrations/20260813190000_blueprint_punch_items.sql"), "utf8");
const service = readFileSync(resolve(root, "lib/blueprints/operations.ts"), "utf8");
const surface = readFileSync(resolve(root, "components/plans/blueprint-markup-surface.tsx"), "utf8");
const intelligence = readFileSync(resolve(root, "lib/blueprints/intelligence.ts"), "utf8");
const intelligencePanel = readFileSync(resolve(root, "components/plans/blueprint-orion-intelligence.tsx"), "utf8");
const projectImpact = readFileSync(resolve(root, "components/plans/blueprint-project-impact.tsx"), "utf8");
const plansWorkspace = readFileSync(resolve(root, "components/plans/plans-workspace.tsx"), "utf8");
const governanceMigration = readFileSync(resolve(root, "supabase/migrations/20260813203000_blueprint_revision_governance.sql"), "utf8");
const governanceService = readFileSync(resolve(root, "lib/blueprints/revision-governance.ts"), "utf8");
const governancePanel = readFileSync(resolve(root, "components/plans/blueprint-revision-governance.tsx"), "utf8");
const revisionEventsMigration = readFileSync(resolve(root, "supabase/migrations/20260813214500_blueprint_revision_events.sql"), "utf8");
const eventTypes = readFileSync(resolve(root, "lib/orion/events/event-types.ts"), "utf8");
const scheduleMigration = readFileSync(resolve(root, "supabase/migrations/20260813230000_blueprint_schedule_impacts.sql"), "utf8");

assert.match(migration, /enable row level security/i);
assert.match(migration, /is_company_member\(company_id\)/);
assert.match(migration, /created_by = auth\.uid\(\)/);
assert.match(migration, /create_task_from_blueprint_issue/);
assert.match(migration, /annotation_type = 'pin'/);
assert.match(migration, /pg_advisory_xact_lock/);
assert.match(migration, /unique \(company_id, annotation_id, target_type, target_id\)/);
assert.match(service, /\.eq\("company_id", identity\.companyId\)/);
assert.match(service, /\.eq\("project_id", identity\.projectId\)/);
assert.match(service, /\.eq\("blueprint_version_id", identity\.versionId\)/);
assert.match(surface, /Create task/);
assert.match(surface, /Task linked/);
assert.match(takeoffMigration, /create_estimate_line_item_from_blueprint_takeoff/);
assert.match(takeoffMigration, /annotation_type in \('distance', 'area'\)/);
assert.match(takeoffMigration, /project_id = p_project_id/);
assert.match(takeoffMigration, /3\.280839895/);
assert.match(takeoffMigration, /10\.763910417/);
assert.match(service, /loadBlueprintProjectEstimates/);
assert.match(service, /createEstimateLineItemFromBlueprintTakeoff/);
assert.match(surface, /Add to estimate/);
assert.match(surface, /Estimate item linked/);
assert.match(changeOrderMigration, /create_change_order_from_blueprint_issue/);
assert.match(changeOrderMigration, /allocate_change_order_number/);
assert.match(changeOrderMigration, /annotation_type = 'pin'/);
assert.match(changeOrderMigration, /status,\s*customer_id/);
assert.match(service, /createChangeOrderFromBlueprintIssue/);
assert.match(surface, /Start change order/);
assert.match(surface, /Change order linked/);
assert.match(workforceMigration, /assign_blueprint_issue_to_workforce/);
assert.match(workforceMigration, /employment_status = 'active'/);
assert.match(workforceMigration, /status = 'active'/);
assert.match(workforceMigration, /'workforce_assignment'/);
assert.match(service, /loadBlueprintWorkforceOptions/);
assert.match(service, /assignBlueprintIssueToWorkforce/);
assert.match(surface, /Assign workforce/);
assert.match(surface, /Workforce assigned/);
assert.match(punchMigration, /create_punch_item_from_blueprint_issue/);
assert.match(punchMigration, /project_punch_items/);
assert.match(punchMigration, /'blueprint:' \|\| p_annotation_id::text/);
assert.match(punchMigration, /Blueprint page/);
assert.match(service, /createPunchItemFromBlueprintIssue/);
assert.match(surface, /Create punch item/);
assert.match(surface, /Punch item linked/);
assert.match(intelligence, /unowned-issues/);
assert.match(intelligence, /operational-response/);
assert.match(intelligencePanel, /loadBlueprintOperationalLinks/);
assert.match(intelligencePanel, /analyzeBlueprint\(items,links\)/);
assert.match(service, /loadBlueprintProjectImpactSummary/);
assert.match(service, /unlinkedIssues/);
assert.match(projectImpact, /blueprint-project-impact/);
assert.match(projectImpact, /without response/);
assert.match(plansWorkspace, /BlueprintProjectImpact/);
assert.match(governanceMigration, /blueprint_revision_acknowledgments/);
assert.match(governanceMigration, /has_company_role/);
assert.match(governanceMigration, /set_blueprint_revision_review_status/);
assert.match(governanceService, /acknowledgeBlueprintRevision/);
assert.match(governanceService, /setBlueprintRevisionReviewStatus/);
assert.match(governancePanel, /Acknowledge/);
assert.match(governancePanel, /Approve revision/);
assert.match(revisionEventsMigration, /trg_blueprint_revision_status_event/);
assert.match(revisionEventsMigration, /trg_blueprint_revision_ack_event/);
assert.match(revisionEventsMigration, /on conflict \(company_id, event_type, idempotency_key\)/);
assert.match(revisionEventsMigration, /reference_entity, reference_id, source_module/);
assert.match(eventTypes, /blueprint\.revision_submitted/);
assert.match(eventTypes, /blueprint\.revision_approved/);
assert.match(eventTypes, /blueprint\.revision_acknowledged/);
assert.match(scheduleMigration, /schedule_blueprint_issue_task/);
assert.match(scheduleMigration, /planned_finish < p_planned_start/);
assert.match(scheduleMigration, /target_type = 'task'/);
assert.match(scheduleMigration, /'schedule.updated'/);
assert.match(service, /scheduleBlueprintIssueTask/);
assert.match(surface, /Schedule task/);

console.log("Blueprint operational integration contract checks passed.");
