import type { OrionCoreScenario, OrionCoreStateId } from "./types";

export const orionCoreScenarioOrder: OrionCoreStateId[] = [
  "READY",
  "ANALYZING",
  "NEW_INSIGHT",
  "ATTENTION",
  "CRITICAL",
  "STALE_DATA",
  "UNAVAILABLE",
  "REDUCED_MOTION",
];

const scenarios: Record<OrionCoreStateId, OrionCoreScenario> = {
  READY: {
    id: "READY",
    title: "Ready",
    stateLabel: "Ready",
    ariaStateLabel: "Ready. Orion is calmly monitoring operations.",
    severity: "info",
    ringStyle: "solid",
    hasPriorityIndicator: false,
    motionHint: "Slow breathing core every eight seconds.",
    textCue: "Steady baseline state",
    badgeLabel: "Stable",
    executiveSnapshot: {
      companyHealth: "Operational flow is stable across active work.",
      topPriority: "Sequence handoff review for tomorrow morning planning window.",
      whyItMatters: "Maintains continuity without introducing avoidable idle time.",
      evidenceQuality: "Moderate",
      freshness: "fresh",
      supportingSignalCount: 3,
      memoryMatchCount: 2,
      graphRelationshipCount: 6,
      recommendedReviewOrder: ["handoff-sequence", "crew-capacity", "inspection-window"],
      recommendedNextStep: "Review handoff sequence and confirm owner acknowledgements.",
      approvalBoundary: "Operations lead review required before any reassignment.",
      limitations: ["One schedule feed updates every 15 minutes instead of real-time."],
    },
  },
  ANALYZING: {
    id: "ANALYZING",
    title: "Analyzing",
    stateLabel: "Analyzing operations",
    ariaStateLabel: "Analyzing operations. Orion is correlating active relationships.",
    severity: "info",
    ringStyle: "arc",
    hasPriorityIndicator: false,
    motionHint: "Outer arc rotates slowly; inner layer remains calm.",
    textCue: "Relationship correlation in progress",
    badgeLabel: "In Progress",
    executiveSnapshot: {
      companyHealth: "Correlation run is active for near-term schedule and staffing data.",
      topPriority: "Pending synthesis of delivery timing against crew availability.",
      whyItMatters: "Prevents contradictory recommendations from partial context.",
      evidenceQuality: "Moderate",
      freshness: "mixed",
      supportingSignalCount: 5,
      memoryMatchCount: 3,
      graphRelationshipCount: 8,
      recommendedReviewOrder: ["delivery-risk", "crew-window", "invoice-timing"],
      recommendedNextStep: "Wait for synthesis completion, then review ranked priorities.",
      approvalBoundary: "No operational change is permitted during analysis phase.",
      limitations: ["One workforce roster source is pending refresh."],
    },
  },
  NEW_INSIGHT: {
    id: "NEW_INSIGHT",
    title: "New Insight",
    stateLabel: "New insight available",
    ariaStateLabel: "New insight available. Orion has surfaced a review-ready priority.",
    severity: "info",
    ringStyle: "double-pulse",
    hasPriorityIndicator: true,
    motionHint: "Two gentle pulses, then return to Ready state.",
    textCue: "New review item detected",
    badgeLabel: "New",
    executiveSnapshot: {
      companyHealth: "A new relationship pattern was detected with moderate confidence.",
      topPriority: "Customer approval delay now links to near-term billing risk.",
      whyItMatters: "Delayed approval can defer invoicing and compress downstream planning.",
      evidenceQuality: "High",
      freshness: "fresh",
      supportingSignalCount: 6,
      memoryMatchCount: 4,
      graphRelationshipCount: 11,
      recommendedReviewOrder: ["customer-approval-delay", "invoice-delay", "cash-review"],
      recommendedNextStep: "Review approval path and assign owner for documented follow-up.",
      approvalBoundary: "Finance and operations manager approval required before escalation.",
      limitations: ["No direct customer response timestamp from external channel."],
    },
  },
  ATTENTION: {
    id: "ATTENTION",
    title: "Attention",
    stateLabel: "Attention required",
    ariaStateLabel: "Attention required. Orion has identified elevated operational exposure.",
    severity: "attention",
    ringStyle: "halo",
    hasPriorityIndicator: true,
    motionHint: "Restrained amber halo with no flashing.",
    textCue: "Elevated exposure",
    badgeLabel: "Attention",
    executiveSnapshot: {
      companyHealth: "One operational corridor requires management review this shift.",
      topPriority: "Crew update risk remains unresolved for an active phase.",
      whyItMatters: "Missing updates reduce confidence in assignment and progress visibility.",
      evidenceQuality: "Moderate",
      freshness: "mixed",
      supportingSignalCount: 5,
      memoryMatchCount: 4,
      graphRelationshipCount: 9,
      recommendedReviewOrder: ["crew-update-risk", "phase-readiness", "dependency-check"],
      recommendedNextStep: "Confirm supervisor contact and record verification timestamp.",
      approvalBoundary: "Supervisor sign-off required before reassignment decisions.",
      limitations: ["One dependency link is stale and awaiting confirmation."],
    },
  },
  CRITICAL: {
    id: "CRITICAL",
    title: "Critical",
    stateLabel: "Critical priority",
    ariaStateLabel: "Critical priority. Immediate executive review is required.",
    severity: "critical",
    ringStyle: "critical-pulse",
    hasPriorityIndicator: true,
    motionHint: "One brief pulse, then steady critical ring.",
    textCue: "Immediate review required",
    badgeLabel: "Critical",
    executiveSnapshot: {
      companyHealth: "A critical compliance risk is active in the current window.",
      topPriority: "Equipment inspection overdue before scheduled dependency window.",
      whyItMatters: "Proceeding without verified inspection creates immediate operational exposure.",
      evidenceQuality: "High",
      freshness: "fresh",
      supportingSignalCount: 4,
      memoryMatchCount: 2,
      graphRelationshipCount: 7,
      recommendedReviewOrder: ["equipment-compliance-risk", "inspection-status", "schedule-constraint"],
      recommendedNextStep: "Hold dependent activity until inspection verification is complete.",
      approvalBoundary: "Operations manager and safety lead approval required before restart.",
      limitations: ["Inspection completion artifact has not been received yet."],
    },
  },
  STALE_DATA: {
    id: "STALE_DATA",
    title: "Stale Data",
    stateLabel: "Data is stale",
    ariaStateLabel: "Data is stale. Orion confidence is reduced until sources are refreshed.",
    severity: "stale",
    ringStyle: "dashed",
    hasPriorityIndicator: false,
    motionHint: "Muted core with segmented ring.",
    textCue: "Freshness degraded",
    badgeLabel: "Stale",
    executiveSnapshot: {
      companyHealth: "Decision confidence is limited by stale source freshness.",
      topPriority: "Refresh delayed data sources before accepting advisory ordering.",
      whyItMatters: "Stale relationships can hide current constraints or overstate old risk.",
      evidenceQuality: "Limited",
      freshness: "stale",
      supportingSignalCount: 2,
      memoryMatchCount: 1,
      graphRelationshipCount: 3,
      recommendedReviewOrder: ["refresh-sources", "recompute-priorities"],
      recommendedNextStep: "Trigger source refresh and re-run fixture review sequence.",
      approvalBoundary: "No decision execution should occur while freshness is stale.",
      limitations: ["Schedule and equipment freshness timestamps exceed threshold."],
    },
  },
  UNAVAILABLE: {
    id: "UNAVAILABLE",
    title: "Unavailable",
    stateLabel: "Orion unavailable",
    ariaStateLabel: "Orion unavailable. Intelligence context is temporarily unavailable.",
    severity: "unavailable",
    ringStyle: "static",
    hasPriorityIndicator: false,
    motionHint: "Static neutral core with no animation.",
    textCue: "Unavailable state",
    badgeLabel: "Unavailable",
    executiveSnapshot: {
      companyHealth: "Orion context is unavailable for this snapshot.",
      topPriority: "Use standard operational review while Orion is unavailable.",
      whyItMatters: "Avoid assumptions when intelligence sources are not available.",
      evidenceQuality: "Limited",
      freshness: "unknown",
      supportingSignalCount: 0,
      memoryMatchCount: 0,
      graphRelationshipCount: 0,
      recommendedReviewOrder: ["manual-operations-review"],
      recommendedNextStep: "Confirm source availability and retry when service is restored.",
      approvalBoundary: "Manual review protocols remain in effect.",
      limitations: ["Fixture source intentionally unavailable for prototype state."],
    },
  },
  REDUCED_MOTION: {
    id: "REDUCED_MOTION",
    title: "Reduced Motion Preview",
    stateLabel: "Reduced motion preview",
    ariaStateLabel: "Reduced motion preview. Orion state cues remain understandable without animation.",
    severity: "info",
    ringStyle: "static",
    hasPriorityIndicator: false,
    motionHint: "Static equivalents for all motion cues.",
    textCue: "Motion-minimized readability",
    badgeLabel: "Reduced Motion",
    executiveSnapshot: {
      companyHealth: "Motion-minimized mode preserves semantic state communication.",
      topPriority: "Validate readability and action boundaries without animation.",
      whyItMatters: "Ensures accessibility and comfort for motion-sensitive users.",
      evidenceQuality: "Moderate",
      freshness: "mixed",
      supportingSignalCount: 3,
      memoryMatchCount: 2,
      graphRelationshipCount: 5,
      recommendedReviewOrder: ["readability-check", "state-cue-check", "focus-flow-check"],
      recommendedNextStep: "Verify every state remains clear via labels and ring styles.",
      approvalBoundary: "Prototype remains read-only with advisory-only recommendations.",
      limitations: ["Animations are intentionally suppressed in this preview state."],
    },
  },
};

export const orionCoreScenarios: Record<OrionCoreStateId, OrionCoreScenario> = scenarios;
