"use client";
import { useState } from "react";
import { Download, FileJson, Share2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { buildBlueprintPackage, createShareableBlueprintPackage, downloadBlueprintCsv, downloadBlueprintJson, type BlueprintPackageDocument } from "@/lib/blueprints/exports";

export function BlueprintExportActions({ companyId, projectId, versionId, userId, projectName, document }: { companyId: string; projectId: string; versionId: string; userId: string; projectName: string; document: BlueprintPackageDocument }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const run = async (action: "json" | "csv" | "share") => { const supabase = createClient(); if (!supabase || busy) return; setBusy(true); setMessage(null); try { const identity = { companyId, projectId, versionId, userId }; const snapshot = await buildBlueprintPackage(supabase, identity, document, projectName); if (action === "json") downloadBlueprintJson(snapshot, document.fileName); if (action === "csv") downloadBlueprintCsv(snapshot, document.fileName); if (action === "share") { const token = await createShareableBlueprintPackage(supabase, identity, snapshot, `${document.fileName} · ${document.revision}`); const url = `${window.location.origin}/shared/blueprints/${token}`; await navigator.clipboard.writeText(url); setMessage("Secure 14-day package link copied."); } } catch (error) { setMessage(error instanceof Error ? error.message : "Could not create this plan package."); } finally { setBusy(false); } };
  return <div className="flex flex-wrap items-center gap-1.5" data-orion-region="blueprint-export-actions"><button type="button" disabled={busy} onClick={() => void run("json")} className="inline-flex h-8 items-center gap-1 rounded-md border border-slate-300 bg-white px-2 text-[11px] font-semibold text-slate-700 disabled:opacity-50"><FileJson size={13}/>JSON</button><button type="button" disabled={busy} onClick={() => void run("csv")} className="inline-flex h-8 items-center gap-1 rounded-md border border-slate-300 bg-white px-2 text-[11px] font-semibold text-slate-700 disabled:opacity-50"><Download size={13}/>CSV</button><button type="button" disabled={busy} onClick={() => void run("share")} className="inline-flex h-8 items-center gap-1 rounded-md bg-blue-600 px-2 text-[11px] font-semibold text-white disabled:opacity-50"><Share2 size={13}/>Share package</button>{message ? <span className="text-[10px] font-medium text-slate-600" role="status">{message}</span> : null}</div>;
}
