import fs from "node:fs";
import path from "node:path";

function assert(condition: boolean, message: string) {
  if (!condition) throw new Error(message);
}

const root = process.cwd();
const projectPage = fs.readFileSync(path.join(root, "app/(app)/projects/[id]/page.tsx"), "utf8");
const tabs = fs.readFileSync(path.join(root, "components/projects/workspace/project-workspace-tabs.ts"), "utf8");
const navigation = fs.readFileSync(path.join(root, "lib/orion/navigation/catalog.ts"), "utf8");
const blueprintsPage = fs.readFileSync(path.join(root, "app/(app)/blueprints/page.tsx"), "utf8");
const planRoom = fs.readFileSync(path.join(root, "lib/blueprints/plan-room.ts"), "utf8");
const uploadPanel = fs.readFileSync(path.join(root, "components/plans/blueprint-upload-panel.tsx"), "utf8");
const revisionPanel = fs.readFileSync(path.join(root, "components/plans/blueprint-revision-panel.tsx"), "utf8");
const plansWorkspace = fs.readFileSync(path.join(root, "components/plans/plans-workspace.tsx"), "utf8");
const blueprintViewer = fs.readFileSync(path.join(root, "components/plans/blueprint-2d-viewer.tsx"), "utf8");
const migration = fs.readFileSync(path.join(root, "supabase/migrations/20260812090000_blueprints_plan_room_foundation.sql"), "utf8");
const membershipAlignment = fs.readFileSync(path.join(root, "supabase/migrations/20260812103000_blueprints_membership_rls_alignment.sql"), "utf8");
const transactionalUploads = fs.readFileSync(path.join(root, "supabase/migrations/20260812113000_blueprints_transactional_upload_rpcs.sql"), "utf8");
const storageAuthorization = fs.readFileSync(path.join(root, "supabase/migrations/20260812120000_blueprints_storage_path_authorization.sql"), "utf8");
const duplicateGuard = fs.readFileSync(path.join(root, "supabase/migrations/20260812130000_blueprints_duplicate_sheet_guard.sql"), "utf8");
const blueprintFormat = fs.readFileSync(path.join(root, "lib/blueprints/format.ts"), "utf8");
const markupService = fs.readFileSync(path.join(root, "lib/blueprints/markups.ts"), "utf8");
const markupSurface = fs.readFileSync(path.join(root, "components/plans/blueprint-markup-surface.tsx"), "utf8");
const planWorkspace = fs.readFileSync(path.join(root, "components/plans/blueprint-plan-workspace.tsx"), "utf8");
const pdfViewer = fs.readFileSync(path.join(root, "components/plans/blueprint-pdf-viewer.tsx"), "utf8");
const annotationsMigration = fs.readFileSync(path.join(root, "supabase/migrations/20260812143000_blueprint_revision_annotations.sql"), "utf8");
const measurementsMigration = fs.readFileSync(path.join(root, "supabase/migrations/20260812170000_blueprint_measurement_annotations.sql"), "utf8");
const realtimeService = fs.readFileSync(path.join(root, "lib/blueprints/realtime.ts"), "utf8");
const realtimeMigration = fs.readFileSync(path.join(root, "supabase/migrations/20260812220000_blueprint_realtime_collaboration.sql"), "utf8");
const mediaService = fs.readFileSync(path.join(root, "lib/blueprints/media-attachments.ts"), "utf8");
const mediaMigration = fs.readFileSync(path.join(root, "supabase/migrations/20260812233000_blueprint_media_attachments.sql"), "utf8");
const exportService = fs.readFileSync(path.join(root, "lib/blueprints/exports.ts"), "utf8");
const exportActions = fs.readFileSync(path.join(root, "components/plans/blueprint-export-actions.tsx"), "utf8");
const packageMigration = fs.readFileSync(path.join(root, "supabase/migrations/20260813010000_blueprint_plan_packages.sql"), "utf8");
const symbolLibrary = fs.readFileSync(path.join(root, "components/plans/blueprint-symbol-library.tsx"), "utf8");
const symbolMigration = fs.readFileSync(path.join(root, "supabase/migrations/20260813023000_blueprint_symbol_libraries.sql"), "utf8");
const wallDimensionMigration = fs.readFileSync(path.join(root, "supabase/migrations/20260813040000_blueprint_wall_dimension_annotations.sql"), "utf8");
const snapping = fs.readFileSync(path.join(root, "lib/blueprints/snapping.ts"), "utf8");

assert(tabs.includes('key: "blueprints"'), "Project workspace must expose a Blueprints tab");
assert(projectPage.includes('activeTab === "blueprints"'), "Project workspace must render the Blueprint Plan Room");
assert(projectPage.includes("<PlansWorkspace"), "Blueprints must reuse the existing plans foundation");
assert(navigation.includes('href: "/blueprints"'), "The BOS and Orion route catalog must include Blueprints");
assert(navigation.includes('routeId: "route-blueprints"'), "Orion must recognize Blueprint navigation language");
assert(blueprintsPage.includes("company_id"), "Company plan-room discovery must be tenant-scoped");
assert(blueprintsPage.includes("?tab=blueprints"), "Global plan-room entries must deep-link to the project Blueprints tab");
assert(planRoom.includes('BLUEPRINTS_BUCKET = "blueprints"'), "Blueprint files must use the private Blueprint bucket");
assert(planRoom.includes("validateBlueprintFile"), "Blueprint uploads must be type and size validated");
assert(planRoom.includes("createSignedUrls"), "Blueprint previews must use expiring signed URLs");
assert(planRoom.includes("storagePath") && planRoom.includes(".remove([storagePath])"), "Failed metadata writes must clean up uploaded files");
assert(uploadPanel.includes('data-orion-region="blueprint-upload"'), "The upload workflow must expose semantic Orion context");
assert(uploadPanel.includes('data-orion-action="') === false, "The upload form must not introduce ambiguous duplicate Orion actions");
assert(revisionPanel.includes("uploadBlueprintRevision"), "Existing sheets must support new revision uploads");
assert(migration.includes("create table public.blueprint_sets"), "Blueprint plan sets must be persisted");
assert(migration.includes("create table public.blueprint_sheets"), "Blueprint sheets must be persisted");
assert(migration.includes("create table public.blueprint_versions"), "Blueprint revision records must be persisted");
assert(migration.includes("enable row level security"), "Blueprint records must enable RLS");
assert(migration.includes("public.blueprint_member_of_company"), "Blueprint RLS must enforce company membership");
assert(migration.includes("register_blueprint_revision"), "Revision registration must be transactional");
assert(migration.includes("set status = 'superseded'"), "A new revision must supersede the previous working version");
assert(migration.includes("public = excluded.public") && migration.includes("false, 104857600"), "The Blueprint bucket must remain private and size-limited");
assert(membershipAlignment.includes("public.is_company_member(tenant_id)"), "Blueprint RLS must use active multi-company membership");
assert(membershipAlignment.includes("drop policy if exists blueprints_storage_insert"), "The legacy storage insert policy must be replaced");
assert(membershipAlignment.includes("project.id::text = (storage.foldername(name))[2]"), "Storage writes must remain project-scoped");
assert(transactionalUploads.includes("create_blueprint_sheet_upload"), "Blueprint metadata creation must use a verified database transaction");
assert(transactionalUploads.includes("register_initial_blueprint_version"), "Initial Blueprint versions must use a verified database function");
assert(transactionalUploads.includes("public.is_company_member(project_record.company_id)"), "Blueprint transactions must verify active company membership server-side");
assert(transactionalUploads.includes("split_part(object_path, '/', 3) <> sheet_record.id::text"), "Blueprint version registration must validate the complete storage path");
assert(planRoom.includes("Could not create Blueprint metadata"), "Upload failures must identify the failing Blueprint stage");
assert(planRoom.includes("Could not store the Blueprint file"), "Storage RLS failures must be distinguishable from metadata failures");
assert(storageAuthorization.includes("blueprint_storage_path_authorized"), "Blueprint storage RLS must use a server-verified path predicate");
assert(storageAuthorization.includes("sheet.id::text = split_part(object_name, '/', 3)"), "Blueprint storage authorization must verify the sheet path segment");
assert(storageAuthorization.includes("public.is_company_member(sheet.company_id)"), "Blueprint storage authorization must verify active membership");
assert(storageAuthorization.includes("grant execute on function public.blueprint_storage_path_authorized(text) to authenticated"), "Only authenticated users may execute the Blueprint storage predicate");
assert(duplicateGuard.includes("pg_advisory_xact_lock"), "Concurrent Blueprint sheet creation must be serialized");
assert(duplicateGuard.includes("use Upload revision instead"), "Duplicate sheets must direct users into revision control");
assert(blueprintFormat.includes('Intl.DateTimeFormat("en-US"'), "Blueprint timestamps must be formatted for people");
assert(plansWorkspace.includes("duplicate sheet record"), "Existing duplicate Blueprint sheets must be disclosed without automatic deletion");
assert(blueprintViewer.includes('data-orion-region="blueprint-2d-viewer"'), "The 2D viewer must expose semantic Orion context");
assert(blueprintViewer.includes("requestFullscreen"), "The 2D viewer must support fullscreen inspection");
assert(blueprintViewer.includes("setPointerCapture"), "The 2D image viewer must support pointer-based panning");
assert(blueprintViewer.includes("MIN_ZOOM") && blueprintViewer.includes("MAX_ZOOM"), "The 2D viewer must constrain zoom safely");
assert(blueprintViewer.includes('document.addEventListener("fullscreenchange"'), "The 2D viewer must react to browser fullscreen layout changes");
assert(blueprintViewer.includes("fillsAvailableHeight"), "Fullscreen and expanded viewers must fill the available canvas height");
assert(annotationsMigration.includes("create table public.blueprint_annotations"), "Blueprint markups must be persisted");
assert(annotationsMigration.includes("blueprint_version_id"), "Blueprint markups must be revision-scoped");
assert(annotationsMigration.includes("public.is_company_member(company_id)"), "Blueprint markup RLS must enforce active company membership");
assert(annotationsMigration.includes("created_by = auth.uid()"), "Blueprint markup deletion must be creator-scoped");
assert(markupService.includes('from("blueprint_annotations")'), "Blueprint markup access must use the annotation store");
assert(markupSurface.includes('data-orion-region="blueprint-markup-toolbar"'), "Markup tools must expose semantic Orion context");
assert(markupSurface.includes('"freehand"') && markupSurface.includes('"arrow"') && markupSurface.includes('"text"') && markupSurface.includes('"pin"'), "Markup must support redlines, arrows, text, and issue pins");
assert(planWorkspace.includes('data-orion-region="blueprint-plan-workspace"'), "The large Plan Workspace must expose semantic Orion context");
assert(planWorkspace.includes("closeOnBackdrop={false}"), "The Plan Workspace must protect unsaved drawing interactions from backdrop dismissal");
assert(planWorkspace.includes("expanded"), "The Plan Workspace must use the expanded drawing canvas");
assert(plansWorkspace.includes("<PlansPreview"), "The Plan Workspace must remain connected to the project Plan Room");
assert(pdfViewer.includes('import("pdfjs-dist")'), "PDF.js must be lazy-loaded only for PDF plans");
assert(pdfViewer.includes("pageNumber={pageNumber}"), "PDF markups must be scoped to the visible page");
assert(pdfViewer.includes("Page {pageNumber}/"), "PDF plans must provide page navigation context");
assert(markupSurface.includes("geometry: { ...geometry, page: pageNumber }"), "Persistent markup geometry must record its PDF page");
assert(measurementsMigration.includes("'calibration','distance','area'"), "Blueprint annotations must support calibrated measurements");
assert(wallDimensionMigration.includes("'wall','locked_dimension'"), "Blueprint annotations must support walls and locked dimensions");
assert(snapping.includes('reason: "endpoint"') && snapping.includes('reason: "axis"') && snapping.includes('reason: "grid"'), "Blueprint snapping must prioritize wall endpoints, axes, and grid points");
assert(markupSurface.includes('label="Wall"') && markupSurface.includes('label="Lock dimension"'), "The markup toolbar must expose wall and locked-dimension tools");
assert(markupSurface.includes("lockedValue") && markupSurface.includes("snapEnabled"), "Locked dimensions must preserve their value and allow snapping to be toggled");
assert(markupSurface.includes('label="Calibrate"') && markupSurface.includes('label="Distance"') && markupSurface.includes('label="Area"'), "The markup toolbar must expose measurement tools");
assert(markupSurface.includes("unitsPerDrawingUnit"), "Measurements must use a persisted drawing calibration");
assert(blueprintViewer.includes('closest("[data-blueprint-controls]")'), "Viewer panning must ignore nested Blueprint controls");
assert(markupSurface.includes("data-blueprint-controls") && markupSurface.includes("event.stopPropagation()"), "Markup controls must isolate pointer events from canvas panning");
assert(!markupSurface.includes("window.confirm"), "Fullscreen Blueprint actions must not use native confirmation dialogs");
assert(markupSurface.includes('role="alertdialog"') && markupSurface.includes("pendingDelete"), "Undo must confirm inside the fullscreen Blueprint toolbar");
assert(markupService.includes("updateBlueprintMarkupStatus"), "Issue status changes must use the tenant-scoped markup service");
assert(markupSurface.includes('data-orion-region="blueprint-layer-controls"'), "Blueprint layer controls must expose semantic Orion context");
assert(markupSurface.includes('data-orion-region="blueprint-annotation-register"'), "The annotation register must expose semantic Orion context");
assert(markupSurface.includes("Resolve issue") && markupSurface.includes("Reopen issue"), "Issue pins must support resolution workflows");
assert(realtimeMigration.includes("alter table public.blueprint_annotations replica identity full"), "Realtime deletes must carry sufficient annotation identity");
assert(realtimeMigration.includes("alter publication supabase_realtime add table public.blueprint_annotations"), "Blueprint annotations must be published to Supabase Realtime");
assert(realtimeService.includes("blueprint:${identity.companyId}:${identity.projectId}:${identity.versionId}"), "Collaboration presence channels must be tenant, project, and revision scoped");
assert(realtimeService.includes("filter: `blueprint_version_id=eq.${identity.versionId}`"), "Annotation change subscriptions must be revision scoped");
assert(realtimeService.includes("user_id: identity.userId") && realtimeService.includes("company_id: identity.companyId"), "Blueprint presence must retain authenticated tenant identity");
assert(markupSurface.includes('data-orion-region="blueprint-collaboration-status"'), "Live Blueprint collaboration must expose semantic Orion context");
assert(markupSurface.includes("subscribeToBlueprintCollaboration"), "The markup surface must subscribe through the shared collaboration service");
assert(mediaMigration.includes("create table public.blueprint_media_attachments"), "Pinned Blueprint media must have a dedicated metadata store");
assert(mediaMigration.includes("foreign key (blueprint_version_id, company_id, project_id)"), "Pinned media must preserve exact tenant, project, and revision integrity");
assert(mediaMigration.includes("public.is_company_member(company_id)"), "Pinned media metadata must enforce active company membership");
assert(mediaMigration.includes("'blueprint-media', 'blueprint-media', false"), "Pinned media must use private storage");
assert(mediaService.includes("createSignedUrls") && mediaService.includes("60 * 30"), "Pinned media previews must use expiring signed URLs");
assert(mediaService.includes("remove([storagePath])"), "Failed media metadata writes must clean up private storage");
assert(markupSurface.includes("Media pin") && markupSurface.includes('data-orion-region="blueprint-media-preview"'), "The Plan Workspace must expose semantic coordinate-pinned media workflows");
assert(packageMigration.includes("create table public.blueprint_plan_packages"), "Shareable plan packages must be persisted");
assert(packageMigration.includes("digest(package_token, 'sha256')"), "Plan package tokens must be stored and validated as hashes");
assert(packageMigration.includes("revoked_at") && packageMigration.includes("expires_at <= now()"), "Plan package links must be revocable and expiring");
assert(exportService.includes('schema: "bango.blueprint-package.v1"'), "Structured exports must have a versioned schema");
assert(!exportService.includes("signedUrl: item.signedUrl"), "Shared snapshots must exclude private signed media URLs");
assert(exportActions.includes('run("json")') && exportActions.includes('run("csv")') && exportActions.includes('run("share")'), "Plan Workspace must expose JSON, CSV, and share-package actions");
assert(planWorkspace.includes("<BlueprintExportActions"), "Structured exports must be available in the large Plan Workspace");
assert(symbolMigration.includes("create table public.blueprint_symbol_definitions"), "Blueprint symbol definitions must support system and tenant libraries");
assert(symbolMigration.includes("public.is_company_member(company_id)"), "Custom symbol libraries must enforce company membership");
assert(symbolMigration.includes("'symbol'"), "Placed symbols must use the revision-scoped annotation store");
assert(symbolLibrary.includes("draggable") && symbolLibrary.includes("BLUEPRINT_SYMBOL_MIME"), "Symbol library items must support typed drag and drop");
assert(symbolLibrary.includes("select then tap a location"), "Symbol placement must provide a touch and keyboard alternative");
assert(markupSurface.includes('data-orion-region="blueprint-symbol-library"') || symbolLibrary.includes('data-orion-region="blueprint-symbol-library"'), "Symbol libraries must expose semantic Orion context");

console.log("BOS Blueprints Phase 1 navigation foundation contract passed");
