import {
  executeArchiveCustomerCommand,
  executeAssignCrewToProjectCommand,
  executeAssignCrewCommand,
  executeArchiveEmployeeCommand,
  executeCreateCrewCommand,
  executeCreateCustomerCommand,
  executeCreateEmployeeCommand,
  executeCreateEstimateCommand,
  executeCreateInvoiceCommand,
  executeCreateProjectCommand,
  executeCreateTaskCommand,
  executeEstimateWorkflowCommand,
  executeInvoiceActionCommand,
  executeRecordInvoicePaymentCommand,
  executeOpenEntityCommand,
  executeProjectExecutionCommand,
  executeRemoveCrewCommand,
  executeSendEstimateCommand,
  executeRestoreCustomerCommand,
  executeTaskStatusCommand,
  executeUnsupportedCommand,
  executeUpdateCustomerCommand,
  executeUpdateProjectStatusCommand,
} from "./handlers";
import type { OrionCommandDefinition, OrionCommandPermission } from "./types";
import { validateObject, validateRequiredKeys } from "./validators";

const OWNER_AND_ADMIN: OrionCommandPermission[] = ["owner", "administrator"];
const MANAGEMENT: OrionCommandPermission[] = ["owner", "administrator", "operations_manager", "project_manager", "superintendent"];
const TEAM: OrionCommandPermission[] = ["owner", "administrator", "operations_manager", "project_manager", "superintendent", "employee"];
const FINANCE: OrionCommandPermission[] = ["owner", "administrator", "accountant"];

function openDefinition(): Pick<OrionCommandDefinition, "validate" | "execute"> {
  return {
    validate: (params) => validateRequiredKeys(params, ["entityType", "entityId"]),
    execute: executeOpenEntityCommand,
  };
}

type OrionCommandDraft = Omit<OrionCommandDefinition, "confirmationLevel" | "coverage" | "eventContract" | "navigation"> & {
  confirmationLevel?: OrionCommandDefinition["confirmationLevel"];
  coverage?: OrionCommandDefinition["coverage"];
  eventContract?: OrionCommandDefinition["eventContract"];
  navigation?: OrionCommandDefinition["navigation"];
};

const ORION_COMMAND_DRAFTS: OrionCommandDraft[] = [
  {
    id: "customer.open",
    name: "Open Customer",
    description: "Open an existing customer workspace.",
    requiredPermissions: TEAM,
    entityType: "customer",
    inputSchema: "{ entityType: 'customer', entityId: string, deepLink?: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "customer.create",
    name: "Create Customer",
    description: "Create a new customer record.",
    requiredPermissions: MANAGEMENT,
    entityType: "customer",
    inputSchema: "{ firstName: string, lastName: string, customerType?: string, ... }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["firstName", "lastName"]),
    execute: executeCreateCustomerCommand,
  },
  {
    id: "customer.update",
    name: "Update Customer",
    description: "Update an existing customer record.",
    requiredPermissions: MANAGEMENT,
    entityType: "customer",
    inputSchema: "{ customerId: string, updates: object }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["customerId"]),
    execute: executeUpdateCustomerCommand,
  },
  {
    id: "customer.archive",
    name: "Archive Customer",
    description: "Archive customer visibility without deleting history.",
    requiredPermissions: OWNER_AND_ADMIN,
    entityType: "customer",
    inputSchema: "{ customerId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["customerId"]),
    execute: executeArchiveCustomerCommand,
  },
  {
    id: "customer.restore",
    name: "Restore Customer",
    description: "Restore an archived customer record.",
    requiredPermissions: OWNER_AND_ADMIN,
    entityType: "customer",
    inputSchema: "{ customerId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["customerId"]),
    execute: executeRestoreCustomerCommand,
  },

  {
    id: "estimate.create",
    name: "Create Estimate",
    description: "Create or update an estimate.",
    requiredPermissions: MANAGEMENT,
    entityType: "estimate",
    inputSchema: "{ values: object, lineItems: array, estimateId?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["values", "lineItems"]),
    execute: executeCreateEstimateCommand,
  },
  {
    id: "estimate.open",
    name: "Open Estimate",
    description: "Open an existing estimate.",
    requiredPermissions: TEAM,
    entityType: "estimate",
    inputSchema: "{ entityType: 'estimate', entityId: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "estimate.send",
    name: "Send Estimate",
    description: "Send estimate to customer channel.",
    requiredPermissions: MANAGEMENT,
    entityType: "estimate",
    confirmationLevel: "REVIEW",
    inputSchema: "{ estimateId: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["estimateId"]),
    execute: executeSendEstimateCommand,
  },
  {
    id: "estimate.approve",
    name: "Approve Estimate",
    description: "Approve estimate using workflow service.",
    requiredPermissions: MANAGEMENT,
    entityType: "estimate",
    inputSchema: "{ estimateId: string, typedName: string, consentAccepted: boolean }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["estimateId", "typedName", "action"]),
    execute: (params, context, deps) => executeEstimateWorkflowCommand({ ...params, action: "approve" }, context, deps),
  },
  {
    id: "estimate.decline",
    name: "Decline Estimate",
    description: "Decline estimate using workflow service.",
    requiredPermissions: MANAGEMENT,
    entityType: "estimate",
    inputSchema: "{ estimateId: string, reason: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["estimateId", "reason", "action"]),
    execute: (params, context, deps) => executeEstimateWorkflowCommand({ ...params, action: "decline" }, context, deps),
  },
  {
    id: "estimate.convert",
    name: "Convert Estimate",
    description: "Convert an approved estimate to project.",
    requiredPermissions: MANAGEMENT,
    entityType: "estimate",
    inputSchema: "{ estimateId: string, createDepositInvoice?: boolean }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["estimateId", "action"]),
    execute: (params, context, deps) => executeEstimateWorkflowCommand({ ...params, action: "convert" }, context, deps),
  },
  {
    id: "estimate.generate_deposit_invoice",
    name: "Generate Deposit Invoice",
    description: "Generate a deposit invoice from estimate.",
    requiredPermissions: FINANCE,
    entityType: "estimate",
    inputSchema: "{ estimateId: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["estimateId", "action"]),
    execute: (params, context, deps) => executeEstimateWorkflowCommand({ ...params, action: "deposit_invoice" }, context, deps),
  },

  {
    id: "project.create",
    name: "Create Project",
    description: "Create a new project record.",
    requiredPermissions: MANAGEMENT,
    entityType: "project",
    inputSchema: "{ name: string, customerId?: string, status?: string, ... }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["name"]),
    execute: executeCreateProjectCommand,
  },
  {
    id: "project.open",
    name: "Open Project",
    description: "Open an existing project.",
    requiredPermissions: TEAM,
    entityType: "project",
    inputSchema: "{ entityType: 'project', entityId: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "schedule.open",
    name: "Open Schedule",
    description: "Open schedule workspace.",
    requiredPermissions: TEAM,
    entityType: "schedule",
    inputSchema: "{ entityType: 'schedule', entityId: string, deepLink?: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "project.update_status",
    name: "Update Status",
    description: "Update project status with deterministic events.",
    requiredPermissions: MANAGEMENT,
    entityType: "project",
    inputSchema: "{ projectId: string, status: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId", "status"]),
    execute: executeUpdateProjectStatusCommand,
  },
  {
    id: "project.assign_crew",
    name: "Assign Crew",
    description: "Assign crew to project.",
    requiredPermissions: MANAGEMENT,
    entityType: "project",
    confirmationLevel: "REVIEW",
    inputSchema: "{ input: object }",
    undoCapable: true,
    validate: (params) => validateObject(params),
    execute: executeAssignCrewToProjectCommand,
  },
  {
    id: "project.complete",
    name: "Complete Project",
    description: "Complete project through closeout checklist validation.",
    requiredPermissions: MANAGEMENT,
    entityType: "project",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ projectId: string, exceptions?: array, startWarranty?: boolean }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["projectId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "project.complete" }, context, deps),
  },
  {
    id: "project.archive",
    name: "Archive Project",
    description: "Archive project execution.",
    requiredPermissions: OWNER_AND_ADMIN,
    entityType: "project",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ projectId: string, reason?: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["projectId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "project.archive" }, context, deps),
  },

  {
    id: "invoice.open",
    name: "Open Invoice",
    description: "Open an existing invoice.",
    requiredPermissions: TEAM,
    entityType: "invoice",
    inputSchema: "{ entityType: 'invoice', entityId: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "invoice.create",
    name: "Create Invoice",
    description: "Create or update an invoice.",
    requiredPermissions: FINANCE,
    entityType: "invoice",
    inputSchema: "{ values: object, lineItems: array, invoiceId?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["values", "lineItems"]),
    execute: executeCreateInvoiceCommand,
  },
  {
    id: "invoice.send",
    name: "Send Invoice",
    description: "Send invoice to customer.",
    requiredPermissions: FINANCE,
    entityType: "invoice",
    inputSchema: "{ invoiceId: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["invoiceId", "action"]),
    execute: (params, context, deps) => executeInvoiceActionCommand({ ...params, action: "send" }, context, deps),
  },
  {
    id: "invoice.record_payment",
    name: "Record Payment",
    description: "Record invoice payment.",
    requiredPermissions: FINANCE,
    entityType: "invoice",
    inputSchema: "{ invoiceId: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["invoiceId", "action"]),
    execute: (params, context, deps) => executeInvoiceActionCommand({ ...params, action: "record_payment" }, context, deps),
  },
  {
    id: "invoice.record_deposit",
    name: "Record Deposit",
    description: "Record a customer deposit.",
    requiredPermissions: FINANCE,
    entityType: "invoice",
    confirmationLevel: "REVIEW",
    inputSchema: "{ invoiceId: string, amount: number }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["invoiceId", "amount"]),
    execute: executeRecordInvoicePaymentCommand,
  },
  {
    id: "invoice.issue_refund",
    name: "Issue Refund",
    description: "Issue refund against invoice payments.",
    requiredPermissions: FINANCE,
    entityType: "invoice",
    confirmationLevel: "REQUIRED",
    coverage: {
      status: "unsupported",
      reason: "No production-safe refund workflow is available yet.",
      missingDependency: "Missing refund_reconciliation ledger table (or equivalent RPC) to link refund records to payment history and processor transaction ids.",
      plannedPhase: "6C",
      expectedEvent: "refund.issued",
      ownerModule: "invoices",
    },
    inputSchema: "{ invoiceId: string, amount: number, reason: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["invoiceId", "amount", "reason"]),
    execute: (params, context) => executeUnsupportedCommand({
      ...params,
      reason: "Refund issuance is not implemented with proper financial reconciliation.",
      missingDependency: "Refund ledger and processor integration.",
    }, context),
  },

  {
    id: "employee.create",
    name: "Create Employee",
    description: "Create employee profile.",
    requiredPermissions: MANAGEMENT,
    entityType: "employee",
    inputSchema: "{ input: object }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["input"]),
    execute: executeCreateEmployeeCommand,
  },
  {
    id: "employee.open",
    name: "Open Employee",
    description: "Open employee profile.",
    requiredPermissions: TEAM,
    entityType: "employee",
    inputSchema: "{ entityType: 'employee', entityId: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "employee.assign",
    name: "Assign Employee",
    description: "Assign employee to project or task.",
    requiredPermissions: MANAGEMENT,
    entityType: "employee",
    inputSchema: "{ taskId: string, assignedProfileId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["taskId", "assignedProfileId"]),
    execute: (params, context, deps) => executeTaskStatusCommand({ ...params, status: "in_progress" }, context, deps),
  },
  {
    id: "employee.archive",
    name: "Archive Employee",
    description: "Archive employee profile.",
    requiredPermissions: OWNER_AND_ADMIN,
    entityType: "employee",
    inputSchema: "{ employeeId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["employeeId"]),
    execute: executeArchiveEmployeeCommand,
  },

  {
    id: "crew.open",
    name: "Open Crew",
    description: "Open crew profile.",
    requiredPermissions: TEAM,
    entityType: "crew",
    inputSchema: "{ entityType: 'crew', entityId: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "crew.create",
    name: "Create Crew",
    description: "Create a workforce crew.",
    requiredPermissions: MANAGEMENT,
    entityType: "crew",
    inputSchema: "{ input: object }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["input"]),
    execute: executeCreateCrewCommand,
  },
  {
    id: "crew.assign",
    name: "Assign Crew",
    description: "Assign employee to crew.",
    requiredPermissions: MANAGEMENT,
    entityType: "crew",
    inputSchema: "{ input: object }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["input"]),
    execute: executeAssignCrewCommand,
  },
  {
    id: "crew.remove",
    name: "Remove Crew",
    description: "End crew membership.",
    requiredPermissions: MANAGEMENT,
    entityType: "crew",
    inputSchema: "{ membershipId: string, endsOn: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["membershipId", "endsOn"]),
    execute: executeRemoveCrewCommand,
  },

  {
    id: "task.create",
    name: "Create Task",
    description: "Create a project task.",
    requiredPermissions: MANAGEMENT,
    entityType: "task",
    inputSchema: "{ title: string, projectId: string, taskNumber: number }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["title", "projectId", "taskNumber"]),
    execute: executeCreateTaskCommand,
  },
  {
    id: "task.complete",
    name: "Complete Task",
    description: "Mark task complete.",
    requiredPermissions: TEAM,
    entityType: "task",
    inputSchema: "{ taskId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["taskId"]),
    execute: (params, context, deps) => executeTaskStatusCommand({ ...params, status: "completed" }, context, deps),
  },
  {
    id: "task.start",
    name: "Start Task",
    description: "Start task execution.",
    requiredPermissions: TEAM,
    entityType: "task",
    inputSchema: "{ taskId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["taskId"]),
    execute: (params, context, deps) => executeTaskStatusCommand({ ...params, status: "in_progress" }, context, deps),
  },
  {
    id: "task.pause",
    name: "Pause Task",
    description: "Pause task execution.",
    requiredPermissions: TEAM,
    entityType: "task",
    inputSchema: "{ taskId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["taskId"]),
    execute: (params, context, deps) => executeTaskStatusCommand({ ...params, status: "on_hold" }, context, deps),
  },
  {
    id: "task.assign",
    name: "Assign Task",
    description: "Assign profile and start task.",
    requiredPermissions: MANAGEMENT,
    entityType: "task",
    inputSchema: "{ taskId: string, assignedProfileId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["taskId", "assignedProfileId"]),
    execute: (params, context, deps) => executeTaskStatusCommand({ ...params, status: "in_progress" }, context, deps),
  },

  {
    id: "inspection.create",
    name: "Create Inspection",
    description: "Create a project inspection record.",
    requiredPermissions: MANAGEMENT,
    entityType: "inspection",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, inspectionType: string, scheduledAt?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId", "inspectionType"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "inspection.create" }, context, deps),
  },
  {
    id: "inspection.open",
    name: "Open Inspection",
    description: "Open project inspections workspace.",
    requiredPermissions: TEAM,
    entityType: "inspection",
    inputSchema: "{ entityType: 'inspection', entityId: string, deepLink?: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "inspection.schedule",
    name: "Schedule Inspection",
    description: "Schedule or update inspection date.",
    requiredPermissions: MANAGEMENT,
    entityType: "inspection",
    confirmationLevel: "REVIEW",
    inputSchema: "{ inspectionId: string, scheduledAt: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["inspectionId", "scheduledAt"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "inspection.schedule" }, context, deps),
  },
  {
    id: "inspection.reschedule",
    name: "Reschedule Inspection",
    description: "Reschedule an inspection.",
    requiredPermissions: MANAGEMENT,
    entityType: "inspection",
    confirmationLevel: "REVIEW",
    inputSchema: "{ inspectionId: string, scheduledAt: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["inspectionId", "scheduledAt"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "inspection.reschedule" }, context, deps),
  },
  {
    id: "inspection.pass",
    name: "Pass Inspection",
    description: "Record inspection pass result.",
    requiredPermissions: MANAGEMENT,
    entityType: "inspection",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ inspectionId: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["inspectionId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "inspection.pass" }, context, deps),
  },
  {
    id: "inspection.fail",
    name: "Fail Inspection",
    description: "Record inspection failure result.",
    requiredPermissions: MANAGEMENT,
    entityType: "inspection",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ inspectionId: string, correctionNotes?: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["inspectionId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "inspection.fail" }, context, deps),
  },
  {
    id: "inspection.cancel",
    name: "Cancel Inspection",
    description: "Cancel an inspection.",
    requiredPermissions: MANAGEMENT,
    entityType: "inspection",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ inspectionId: string, notes?: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["inspectionId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "inspection.cancel" }, context, deps),
  },
  {
    id: "inspection.schedule_reinspection",
    name: "Schedule Reinspection",
    description: "Schedule inspection re-check.",
    requiredPermissions: MANAGEMENT,
    entityType: "inspection",
    confirmationLevel: "REVIEW",
    inputSchema: "{ inspectionId: string, reinspectionDate: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["inspectionId", "reinspectionDate"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "inspection.schedule_reinspection" }, context, deps),
  },

  {
    id: "permit.create",
    name: "Create Permit",
    description: "Create project permit requirement.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, permitType: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId", "permitType"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.create" }, context, deps),
  },
  {
    id: "permit.open",
    name: "Open Permit",
    description: "Open permit workspace.",
    requiredPermissions: TEAM,
    entityType: "permit",
    inputSchema: "{ entityType: 'permit', entityId: string, deepLink?: string }",
    undoCapable: false,
    ...openDefinition(),
  },
  {
    id: "permit.submit",
    name: "Submit Permit",
    description: "Submit permit to authority.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ permitId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["permitId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.submit" }, context, deps),
  },
  {
    id: "permit.approve",
    name: "Approve Permit",
    description: "Record permit approval.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ permitId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["permitId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.approve" }, context, deps),
  },
  {
    id: "permit.issue",
    name: "Issue Permit",
    description: "Record permit issuance.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ permitId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["permitId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.issue" }, context, deps),
  },
  {
    id: "permit.reject",
    name: "Reject Permit",
    description: "Record permit rejection.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ permitId: string, reason: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["permitId", "reason"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.reject" }, context, deps),
  },
  {
    id: "permit.renew",
    name: "Renew Permit",
    description: "Renew an expired permit.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ permitId: string, expirationDate?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["permitId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.renew" }, context, deps),
  },
  {
    id: "permit.close",
    name: "Close Permit",
    description: "Close permit lifecycle.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ permitId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["permitId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.close" }, context, deps),
  },
  {
    id: "permit.mark_not_required",
    name: "Mark Permit Not Required",
    description: "Mark permit as not required.",
    requiredPermissions: MANAGEMENT,
    entityType: "permit",
    confirmationLevel: "REVIEW",
    inputSchema: "{ permitId: string, notes?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["permitId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "permit.mark_not_required" }, context, deps),
  },

  {
    id: "project.start_closeout",
    name: "Start Closeout",
    description: "Start project closeout lifecycle.",
    requiredPermissions: MANAGEMENT,
    entityType: "project",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, notes?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "project.start_closeout" }, context, deps),
  },
  {
    id: "punch_item.create",
    name: "Create Punch Item",
    description: "Create closeout punch item.",
    requiredPermissions: MANAGEMENT,
    entityType: "punch_item",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, title: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId", "title"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "punch_item.create" }, context, deps),
  },
  {
    id: "punch_item.assign",
    name: "Assign Punch Item",
    description: "Assign punch item.",
    requiredPermissions: MANAGEMENT,
    entityType: "punch_item",
    confirmationLevel: "REVIEW",
    inputSchema: "{ punchItemId: string, assignedProfileId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["punchItemId", "assignedProfileId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "punch_item.assign" }, context, deps),
  },
  {
    id: "punch_item.complete",
    name: "Complete Punch Item",
    description: "Complete punch item.",
    requiredPermissions: MANAGEMENT,
    entityType: "punch_item",
    confirmationLevel: "REVIEW",
    inputSchema: "{ punchItemId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["punchItemId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "punch_item.complete" }, context, deps),
  },
  {
    id: "punch_item.reopen",
    name: "Reopen Punch Item",
    description: "Reopen completed punch item.",
    requiredPermissions: MANAGEMENT,
    entityType: "punch_item",
    confirmationLevel: "REVIEW",
    inputSchema: "{ punchItemId: string, notes?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["punchItemId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "punch_item.reopen" }, context, deps),
  },
  {
    id: "project.record_walkthrough",
    name: "Record Walkthrough",
    description: "Record customer walkthrough completion.",
    requiredPermissions: MANAGEMENT,
    entityType: "project",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, notes?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "project.record_walkthrough" }, context, deps),
  },
  {
    id: "project.complete_handover",
    name: "Complete Handover",
    description: "Record customer handover completion.",
    requiredPermissions: MANAGEMENT,
    entityType: "project",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, notes?: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "project.complete_handover" }, context, deps),
  },

  {
    id: "customer_update.create",
    name: "Create Customer Update",
    description: "Create draft customer project update.",
    requiredPermissions: MANAGEMENT,
    entityType: "communication",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, message: string, channel: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId", "message"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "customer_update.create" }, context, deps),
  },
  {
    id: "customer_update.preview",
    name: "Preview Customer Update",
    description: "Preview customer update prior to sending.",
    requiredPermissions: MANAGEMENT,
    entityType: "communication",
    inputSchema: "{ communicationId: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["communicationId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "customer_update.preview" }, context, deps),
  },
  {
    id: "customer_update.send",
    name: "Send Customer Update",
    description: "Send customer update through configured provider.",
    requiredPermissions: MANAGEMENT,
    entityType: "communication",
    confirmationLevel: "REQUIRED",
    inputSchema: "{ communicationId: string, confirmed: boolean }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["communicationId", "confirmed"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "customer_update.send" }, context, deps),
  },
  {
    id: "customer_update.cancel",
    name: "Cancel Customer Update",
    description: "Cancel draft or queued customer update.",
    requiredPermissions: MANAGEMENT,
    entityType: "communication",
    confirmationLevel: "REVIEW",
    inputSchema: "{ communicationId: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["communicationId"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "customer_update.cancel" }, context, deps),
  },
  {
    id: "customer_update.log_phone_call",
    name: "Log Phone Update",
    description: "Log phone communication with customer.",
    requiredPermissions: TEAM,
    entityType: "communication",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, message: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId", "message"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "customer_update.log_phone_call" }, context, deps),
  },
  {
    id: "customer_update.log_in_person",
    name: "Log In-Person Update",
    description: "Log in-person communication with customer.",
    requiredPermissions: TEAM,
    entityType: "communication",
    confirmationLevel: "REVIEW",
    inputSchema: "{ projectId: string, message: string }",
    undoCapable: true,
    validate: (params) => validateRequiredKeys(params, ["projectId", "message"]),
    execute: (params, context, deps) => executeProjectExecutionCommand({ ...params, action: "customer_update.log_in_person" }, context, deps),
  },
  {
    id: "customer_update.open",
    name: "Open Communications",
    description: "Open project communications workspace.",
    requiredPermissions: TEAM,
    entityType: "communication",
    inputSchema: "{ entityType: 'communication', entityId: string, deepLink?: string }",
    undoCapable: false,
    ...openDefinition(),
  },

  {
    id: "daily_report.create",
    name: "Create Daily Report",
    description: "Create a daily report draft.",
    requiredPermissions: MANAGEMENT,
    entityType: "daily_report",
    confirmationLevel: "REVIEW",
    coverage: {
      status: "unsupported",
      reason: "Daily report storage is currently disconnected.",
      missingDependency: "Daily Reports storage connection and repository.",
      plannedPhase: "6C",
      expectedEvent: "daily_report.created",
      ownerModule: "daily_reports",
    },
    inputSchema: "{ reportDate: string, projectId: string }",
    undoCapable: true,
    validate: (params) => validateObject(params),
    execute: (params, context) => executeUnsupportedCommand({
      ...params,
      reason: "Daily Reports storage is not connected.",
      missingDependency: "Daily Reports storage service.",
    }, context),
  },
  {
    id: "daily_report.update",
    name: "Update Daily Report",
    description: "Update a daily report.",
    requiredPermissions: MANAGEMENT,
    entityType: "daily_report",
    confirmationLevel: "REVIEW",
    coverage: {
      status: "unsupported",
      reason: "Daily report storage is currently disconnected.",
      missingDependency: "Daily Reports storage connection and repository.",
      plannedPhase: "6C",
      expectedEvent: "daily_report.updated",
      ownerModule: "daily_reports",
    },
    inputSchema: "{ reportId: string, updates: object }",
    undoCapable: true,
    validate: (params) => validateObject(params),
    execute: (params, context) => executeUnsupportedCommand({
      ...params,
      reason: "Daily Reports storage is not connected.",
      missingDependency: "Daily Reports storage service.",
    }, context),
  },
  {
    id: "daily_report.open",
    name: "Open Daily Report",
    description: "Open a daily report.",
    requiredPermissions: TEAM,
    entityType: "daily_report",
    inputSchema: "{ entityType: 'daily_report', entityId: string }",
    undoCapable: false,
    ...openDefinition(),
  },

  {
    id: "dashboard.open",
    name: "Open Dashboard",
    description: "Open dashboard workspace.",
    requiredPermissions: TEAM,
    entityType: "workflow",
    inputSchema: "{ entityType: 'workflow', entityId: string, deepLink?: string }",
    undoCapable: false,
    validate: (params) => validateRequiredKeys(params, ["entityType", "entityId"]),
    execute: executeOpenEntityCommand,
  },
  {
    id: "document.upload",
    name: "Upload Document",
    description: "Upload project or customer document.",
    requiredPermissions: TEAM,
    entityType: "document",
    confirmationLevel: "REVIEW",
    coverage: {
      status: "unsupported",
      reason: "No production documents service is currently wired.",
      missingDependency: "Document storage service with company-scoped ACL.",
      plannedPhase: "6C",
      expectedEvent: "document.uploaded",
      ownerModule: "documents",
    },
    inputSchema: "{ projectId: string, fileName: string }",
    undoCapable: true,
    validate: (params) => validateObject(params),
    execute: (params, context) => executeUnsupportedCommand({
      ...params,
      reason: "Document upload is unavailable without a document storage backend.",
      missingDependency: "Document storage backend and metadata repository.",
    }, context),
  },
  {
    id: "document.delete",
    name: "Delete Document",
    description: "Delete stored document.",
    requiredPermissions: MANAGEMENT,
    entityType: "document",
    confirmationLevel: "REQUIRED",
    coverage: {
      status: "unsupported",
      reason: "No production documents service is currently wired.",
      missingDependency: "Document deletion policy and storage backend.",
      plannedPhase: "6C",
      expectedEvent: "document.deleted",
      ownerModule: "documents",
    },
    inputSchema: "{ documentId: string }",
    undoCapable: true,
    validate: (params) => validateObject(params),
    execute: (params, context) => executeUnsupportedCommand({
      ...params,
      reason: "Document delete is unavailable without a document storage backend.",
      missingDependency: "Document storage backend and retention policy enforcement.",
    }, context),
  },
  {
    id: "document.sign",
    name: "Sign Document",
    description: "Apply signature to document.",
    requiredPermissions: MANAGEMENT,
    entityType: "document",
    confirmationLevel: "REQUIRED",
    coverage: {
      status: "unsupported",
      reason: "No production document signature workflow is currently wired.",
      missingDependency: "Agreement signature records and legal audit artifact store.",
      plannedPhase: "6C",
      expectedEvent: "document.signed",
      ownerModule: "documents",
    },
    inputSchema: "{ documentId: string, signerName: string }",
    undoCapable: false,
    validate: (params) => validateObject(params),
    execute: (params, context) => executeUnsupportedCommand({
      ...params,
      reason: "Document signing is unavailable without signature record persistence.",
      missingDependency: "Signature records table and signing workflow.",
    }, context),
  },
  {
    id: "document.view",
    name: "View Document",
    description: "Open document viewer.",
    requiredPermissions: TEAM,
    entityType: "document",
    inputSchema: "{ entityType: 'document', entityId: string, deepLink?: string }",
    undoCapable: false,
    ...openDefinition(),
  },
];

export const ORION_INITIAL_COMMANDS: OrionCommandDefinition[] = ORION_COMMAND_DRAFTS.map((draft) => {
  const defaultNavigation = draft.id.endsWith(".open") || draft.id.endsWith(".view")
    ? { resolvesHref: true }
    : undefined;

  const expectedEventByCommandId: Partial<Record<string, string[]>> = {
    "customer.create": ["customer.created"],
    "customer.update": ["customer.updated"],
    "customer.archive": ["customer.archived"],
    "customer.restore": ["customer.restored"],
    "estimate.create": ["estimate.created", "estimate.updated"],
    "estimate.send": ["estimate.sent"],
    "estimate.approve": ["estimate.approved"],
    "estimate.decline": ["estimate.declined"],
    "estimate.convert": ["estimate.converted"],
    "estimate.generate_deposit_invoice": ["estimate.deposit_requested"],
    "project.create": ["project.created"],
    "project.update_status": ["project.status_changed"],
    "project.assign_crew": ["crew.assigned"],
    "project.complete": ["project.completed"],
    "project.archive": ["project.archived"],
    "invoice.create": ["invoice.created", "invoice.updated"],
    "invoice.send": ["invoice.sent"],
    "invoice.record_payment": ["invoice.paid"],
    "invoice.record_deposit": ["deposit.received"],
    "employee.create": ["employee.created"],
    "employee.assign": ["task.started"],
    "employee.archive": ["employee.archived"],
    "crew.create": ["crew.created"],
    "crew.assign": ["crew.assigned"],
    "crew.remove": ["crew.unassigned"],
    "task.create": ["task.created"],
    "task.complete": ["task.completed"],
    "inspection.create": ["inspection.created", "inspection.scheduled"],
    "inspection.schedule": ["inspection.scheduled"],
    "inspection.reschedule": ["inspection.rescheduled"],
    "inspection.pass": ["inspection.passed"],
    "inspection.fail": ["inspection.failed", "inspection.reinspection_required"],
    "inspection.cancel": ["inspection.cancelled"],
    "inspection.schedule_reinspection": ["inspection.reinspection_required"],
    "permit.create": ["permit.created", "permit.required"],
    "permit.submit": ["permit.submitted"],
    "permit.approve": ["permit.approved"],
    "permit.issue": ["permit.issued"],
    "permit.reject": ["permit.rejected"],
    "permit.renew": ["permit.renewed"],
    "permit.close": ["permit.closed"],
    "permit.mark_not_required": ["permit.not_required"],
    "project.start_closeout": ["project.closeout_started"],
    "punch_item.create": ["punch_item.created"],
    "punch_item.complete": ["punch_item.completed"],
    "punch_item.reopen": ["punch_item.reopened"],
    "project.record_walkthrough": ["project.walkthrough_completed"],
    "project.complete_handover": ["project.handover_completed"],
    "customer_update.create": ["customer_update.drafted"],
    "customer_update.send": ["customer_update.sent", "customer_update.failed"],
    "customer_update.log_phone_call": ["customer_update.logged"],
    "customer_update.log_in_person": ["customer_update.logged"],
    "task.assign": ["task.started"],
  };

  const isNavigation = Boolean(defaultNavigation);
  const coverage = draft.coverage || {
    status: isNavigation ? "navigation_only" : "implemented",
    ownerModule: draft.entityType,
  };

  const defaultEvents = expectedEventByCommandId[draft.id]
    || (coverage.expectedEvent ? [coverage.expectedEvent] : undefined);

  return {
    ...draft,
    confirmationLevel: draft.confirmationLevel || "NONE",
    coverage,
    eventContract: draft.eventContract || (isNavigation || coverage.status === "unsupported" ? undefined : {
      expectedEvents: defaultEvents || ["workflow.executed"],
    }),
    navigation: draft.navigation || defaultNavigation,
  };
});

export function createOrionCommandRegistry() {
  const byId = new Map(ORION_INITIAL_COMMANDS.map((command) => [command.id, command]));
  const byName = new Map(ORION_INITIAL_COMMANDS.map((command) => [command.name.toLowerCase(), command]));

  return {
    list: () => ORION_INITIAL_COMMANDS,
    getById: (id: string) => byId.get(id) || null,
    getByName: (name: string) => byName.get(name.trim().toLowerCase()) || null,
  };
}
