import type {
  NewManualProjectNoteInput,
  ProjectEvent,
  ProjectEventActor,
  ProjectTimelineRiskItem,
  ProjectTimelineSummary,
} from "./types";

const iso = (value: string) => new Date(value).toISOString();

const actorProjectManager: ProjectEventActor = {
  id: "actor-pm-1",
  name: "M. Rivera",
  avatarUrl: null,
  role: "Project Manager",
  type: "employee",
};

const actorEstimator: ProjectEventActor = {
  id: "actor-est-1",
  name: "A. Flores",
  avatarUrl: null,
  role: "Estimator",
  type: "employee",
};

const actorSuperintendent: ProjectEventActor = {
  id: "actor-sup-1",
  name: "J. Carter",
  avatarUrl: null,
  role: "Superintendent",
  type: "employee",
};

const actorInspector: ProjectEventActor = {
  id: "actor-inspector-1",
  name: "City Inspector",
  avatarUrl: null,
  role: "Inspector",
  type: "vendor",
};

const actorCustomer: ProjectEventActor = {
  id: "actor-customer-1",
  name: "Northpoint Medical",
  avatarUrl: null,
  role: "Customer",
  type: "customer",
};

const actorAI: ProjectEventActor = {
  id: "actor-ai-1",
  name: "Bango AI",
  avatarUrl: null,
  role: "AI Assistant",
  type: "ai",
};

const actorSystem: ProjectEventActor = {
  id: "actor-system",
  name: "BangoOS",
  avatarUrl: null,
  role: "System",
  type: "system",
};

export function getProjectEventsMockData(projectId: string): ProjectEvent[] {
  return [
    {
      id: "evt-001",
      projectId,
      eventType: "customer_created",
      category: "customer",
      title: "projects.intelligenceEvent.customerCreated.title",
      description: "projects.intelligenceEvent.customerCreated.description",
      occurredAt: iso("2026-03-10T09:00:00-05:00"),
      createdAt: iso("2026-03-10T09:05:00-05:00"),
      actor: actorEstimator,
      source: "system",
      priority: "normal",
      status: "completed",
      impactAreas: ["customer"],
      metadata: { channel: "crm", keywords: ["new lead", "medical buildout"] },
      relatedEntity: { id: "cust-100", type: "customer", label: "Northpoint Medical", href: "/customers/cust-100" },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-002",
      projectId,
      eventType: "project_created",
      category: "project",
      title: "projects.intelligenceEvent.projectCreated.title",
      description: "projects.intelligenceEvent.projectCreated.description",
      occurredAt: iso("2026-03-12T08:25:00-05:00"),
      createdAt: iso("2026-03-12T08:26:00-05:00"),
      actor: actorProjectManager,
      source: "system",
      priority: "normal",
      status: "completed",
      impactAreas: ["none"],
      metadata: { projectNumber: "PRJ-2044", keywords: ["kickoff", "workspace"] },
      relatedEntity: { id: projectId, type: "project", label: "Northpoint Medical - Imaging Wing", href: `/projects/${projectId}` },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-003",
      projectId,
      eventType: "estimate_created",
      category: "estimate",
      title: "projects.intelligenceEvent.estimateCreated.title",
      description: "projects.intelligenceEvent.estimateCreated.description",
      occurredAt: iso("2026-03-13T11:10:00-05:00"),
      createdAt: iso("2026-03-13T11:15:00-05:00"),
      actor: actorEstimator,
      source: "manual",
      priority: "normal",
      status: "completed",
      impactAreas: ["financial"],
      metadata: { estimateNumber: "EST-8801", keywords: ["proposal", "base scope"] },
      relatedEntity: { id: "est-8801", type: "estimate", label: "Estimate EST-8801", href: "/estimates/est-8801" },
      attachments: [
        {
          id: "att-est-1",
          name: "estimate-est-8801.pdf",
          type: "pdf",
          url: "/mock/estimate-est-8801.pdf",
          thumbnailUrl: null,
        },
      ],
      financialImpact: { amount: 182500, currency: "USD", direction: "increase", budgetCategory: "base_contract", changeOrderId: null, invoiceId: null },
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-004",
      projectId,
      eventType: "estimate_sent",
      category: "estimate",
      title: "projects.intelligenceEvent.estimateSent.title",
      description: "projects.intelligenceEvent.estimateSent.description",
      occurredAt: iso("2026-03-14T16:30:00-05:00"),
      createdAt: iso("2026-03-14T16:30:00-05:00"),
      actor: actorEstimator,
      source: "system",
      priority: "normal",
      status: "completed",
      impactAreas: ["customer"],
      metadata: { channel: "email", keywords: ["estimate", "sent"] },
      relatedEntity: { id: "est-8801", type: "estimate", label: "Estimate EST-8801", href: "/estimates/est-8801" },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-005",
      projectId,
      eventType: "customer_message",
      category: "customer",
      title: "projects.intelligenceEvent.customerMessage.title",
      description: "projects.intelligenceEvent.customerMessage.description",
      occurredAt: iso("2026-03-16T10:20:00-05:00"),
      createdAt: iso("2026-03-16T10:20:00-05:00"),
      actor: actorCustomer,
      source: "integration",
      priority: "normal",
      status: "completed",
      impactAreas: ["customer"],
      metadata: { channel: "email", keywords: ["revision", "timeline"] },
      relatedEntity: { id: "cust-thread-88", type: "customer", label: "Message Thread #88", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-006",
      projectId,
      eventType: "estimate_approved",
      category: "estimate",
      title: "projects.intelligenceEvent.estimateApproved.title",
      description: "projects.intelligenceEvent.estimateApproved.description",
      occurredAt: iso("2026-03-18T14:05:00-05:00"),
      createdAt: iso("2026-03-18T14:06:00-05:00"),
      actor: actorCustomer,
      source: "integration",
      priority: "high",
      status: "completed",
      impactAreas: ["financial", "customer"],
      metadata: { keywords: ["approved", "go"] },
      relatedEntity: { id: "est-8801", type: "estimate", label: "Estimate EST-8801", href: "/estimates/est-8801" },
      attachments: [],
      financialImpact: { amount: 182500, currency: "USD", direction: "increase", budgetCategory: "contract_value", changeOrderId: null, invoiceId: null },
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-007",
      projectId,
      eventType: "contract_signed",
      category: "contract",
      title: "projects.intelligenceEvent.contractSigned.title",
      description: "projects.intelligenceEvent.contractSigned.description",
      occurredAt: iso("2026-03-20T09:40:00-05:00"),
      createdAt: iso("2026-03-20T09:45:00-05:00"),
      actor: actorCustomer,
      source: "integration",
      priority: "high",
      status: "completed",
      impactAreas: ["financial", "documentation"],
      metadata: { keywords: ["contract", "signature"] },
      relatedEntity: { id: "contract-1001", type: "contract", label: "Owner Contract #1001", href: null },
      attachments: [
        {
          id: "att-contract-1",
          name: "northpoint-contract-signed.pdf",
          type: "pdf",
          url: "/mock/northpoint-contract-signed.pdf",
          thumbnailUrl: null,
        },
      ],
      financialImpact: { amount: 182500, currency: "USD", direction: "increase", budgetCategory: "contract_value", changeOrderId: null, invoiceId: null },
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-008",
      projectId,
      eventType: "permit_submitted",
      category: "permit",
      title: "projects.intelligenceEvent.permitSubmitted.title",
      description: "projects.intelligenceEvent.permitSubmitted.description",
      occurredAt: iso("2026-03-22T15:15:00-05:00"),
      createdAt: iso("2026-03-22T15:18:00-05:00"),
      actor: actorProjectManager,
      source: "manual",
      priority: "normal",
      status: "in_progress",
      impactAreas: ["documentation", "schedule"],
      metadata: { permitNumber: "PER-761", keywords: ["permit", "submission"] },
      relatedEntity: { id: "permit-761", type: "permit", label: "Electrical Permit PER-761", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-009",
      projectId,
      eventType: "permit_approved",
      category: "permit",
      title: "projects.intelligenceEvent.permitApproved.title",
      description: "projects.intelligenceEvent.permitApproved.description",
      occurredAt: iso("2026-03-26T13:10:00-05:00"),
      createdAt: iso("2026-03-26T13:11:00-05:00"),
      actor: actorInspector,
      source: "integration",
      priority: "high",
      status: "completed",
      impactAreas: ["schedule"],
      metadata: { keywords: ["permit", "approved"] },
      relatedEntity: { id: "permit-761", type: "permit", label: "Electrical Permit PER-761", href: null },
      attachments: [
        {
          id: "att-permit-1",
          name: "permit-approval.pdf",
          type: "pdf",
          url: "/mock/permit-approval.pdf",
          thumbnailUrl: null,
        },
      ],
      financialImpact: null,
      scheduleImpact: { delayDays: 0, recoveredDays: 1, affectedPhase: "Pre-construction", affectedTaskId: null, reason: "Permit approved ahead of buffer" },
      aiContext: null,
    },
    {
      id: "evt-010",
      projectId,
      eventType: "employee_assigned",
      category: "employee",
      title: "projects.intelligenceEvent.employeeAssigned.title",
      description: "projects.intelligenceEvent.employeeAssigned.description",
      occurredAt: iso("2026-03-27T08:00:00-05:00"),
      createdAt: iso("2026-03-27T08:00:00-05:00"),
      actor: actorSuperintendent,
      source: "manual",
      priority: "normal",
      status: "completed",
      impactAreas: ["schedule"],
      metadata: { crew: "Crew A", keywords: ["crew", "assignment"] },
      relatedEntity: { id: "task-setup", type: "task", label: "Site setup and demolition", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-011",
      projectId,
      eventType: "phase_started",
      category: "project",
      title: "projects.intelligenceEvent.phaseStarted.title",
      description: "projects.intelligenceEvent.phaseStarted.description",
      occurredAt: iso("2026-03-28T07:30:00-05:00"),
      createdAt: iso("2026-03-28T07:32:00-05:00"),
      actor: actorSuperintendent,
      source: "system",
      priority: "normal",
      status: "completed",
      impactAreas: ["schedule"],
      metadata: { phase: "Demolition", keywords: ["phase", "start"] },
      relatedEntity: { id: "phase-demo", type: "phase", label: "Demolition", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-012",
      projectId,
      eventType: "material_ordered",
      category: "material",
      title: "projects.intelligenceEvent.materialOrdered.title",
      description: "projects.intelligenceEvent.materialOrdered.description",
      occurredAt: iso("2026-03-29T15:25:00-05:00"),
      createdAt: iso("2026-03-29T15:30:00-05:00"),
      actor: actorProjectManager,
      source: "integration",
      priority: "normal",
      status: "completed",
      impactAreas: ["financial", "schedule"],
      metadata: { vendor: "BuildSupply", poNumber: "PO-7781", keywords: ["materials", "po"] },
      relatedEntity: { id: "po-7781", type: "material_order", label: "Material Order PO-7781", href: null },
      attachments: [],
      financialImpact: { amount: 24600, currency: "USD", direction: "increase", budgetCategory: "materials", changeOrderId: null, invoiceId: null },
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-013",
      projectId,
      eventType: "site_photo_uploaded",
      category: "sitecam",
      title: "projects.intelligenceEvent.sitePhotoUploaded.title",
      description: "projects.intelligenceEvent.sitePhotoUploaded.description",
      occurredAt: iso("2026-03-31T17:50:00-05:00"),
      createdAt: iso("2026-03-31T17:52:00-05:00"),
      actor: actorSuperintendent,
      source: "sitecam",
      priority: "low",
      status: "completed",
      impactAreas: ["documentation"],
      metadata: { category: "progress", keywords: ["sitecam", "demo complete"] },
      relatedEntity: { id: "photo-001", type: "site_photo", label: "Demo completion photo set", href: null },
      attachments: [
        {
          id: "att-photo-1",
          name: "demo-complete-1.jpg",
          type: "photo",
          url: "/mock/demo-complete-1.jpg",
          thumbnailUrl: "/mock/demo-complete-1-thumb.jpg",
        },
      ],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-014",
      projectId,
      eventType: "daily_report_created",
      category: "daily_report",
      title: "projects.intelligenceEvent.dailyReportCreated.title",
      description: "projects.intelligenceEvent.dailyReportCreated.description",
      occurredAt: iso("2026-04-01T18:30:00-05:00"),
      createdAt: iso("2026-04-01T18:35:00-05:00"),
      actor: actorSuperintendent,
      source: "manual",
      priority: "normal",
      status: "completed",
      impactAreas: ["documentation"],
      metadata: { reportNumber: "DR-2201", keywords: ["daily report", "crew hours"] },
      relatedEntity: { id: "dr-2201", type: "daily_report", label: "Daily Report DR-2201", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-015",
      projectId,
      eventType: "phase_completed",
      category: "project",
      title: "projects.intelligenceEvent.phaseCompleted.title",
      description: "projects.intelligenceEvent.phaseCompleted.description",
      occurredAt: iso("2026-04-02T16:05:00-05:00"),
      createdAt: iso("2026-04-02T16:05:00-05:00"),
      actor: actorProjectManager,
      source: "system",
      priority: "normal",
      status: "completed",
      impactAreas: ["schedule"],
      metadata: { phase: "Demolition", keywords: ["phase complete"] },
      relatedEntity: { id: "phase-demo", type: "phase", label: "Demolition", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: { delayDays: 0, recoveredDays: 0, affectedPhase: "Demolition", affectedTaskId: null, reason: "Completed on plan" },
      aiContext: null,
    },
    {
      id: "evt-016",
      projectId,
      eventType: "phase_started",
      category: "project",
      title: "projects.intelligenceEvent.phaseStartedRoughIn.title",
      description: "projects.intelligenceEvent.phaseStartedRoughIn.description",
      occurredAt: iso("2026-04-03T07:15:00-05:00"),
      createdAt: iso("2026-04-03T07:16:00-05:00"),
      actor: actorSuperintendent,
      source: "system",
      priority: "normal",
      status: "completed",
      impactAreas: ["schedule"],
      metadata: { phase: "Rough-in", keywords: ["rough-in", "phase"] },
      relatedEntity: { id: "phase-roughin", type: "phase", label: "Rough-in", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-017",
      projectId,
      eventType: "inspection_scheduled",
      category: "inspection",
      title: "projects.intelligenceEvent.inspectionScheduled.title",
      description: "projects.intelligenceEvent.inspectionScheduled.description",
      occurredAt: iso("2026-04-04T09:30:00-05:00"),
      createdAt: iso("2026-04-04T09:32:00-05:00"),
      actor: actorProjectManager,
      source: "manual",
      priority: "high",
      status: "in_progress",
      impactAreas: ["schedule", "documentation"],
      metadata: { inspectionType: "Electrical rough-in", keywords: ["inspection", "schedule"] },
      relatedEntity: { id: "insp-901", type: "inspection", label: "Inspection #901", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-018",
      projectId,
      eventType: "material_delayed",
      category: "material",
      title: "projects.intelligenceEvent.materialDelayed.title",
      description: "projects.intelligenceEvent.materialDelayed.description",
      occurredAt: iso("2026-04-05T12:20:00-05:00"),
      createdAt: iso("2026-04-05T12:22:00-05:00"),
      actor: actorSystem,
      source: "integration",
      priority: "high",
      status: "open",
      impactAreas: ["schedule", "financial"],
      metadata: { poNumber: "PO-7781", keywords: ["delay", "drywall", "supplier"] },
      relatedEntity: { id: "po-7781", type: "material_order", label: "Material Order PO-7781", href: null },
      attachments: [],
      financialImpact: { amount: 1200, currency: "USD", direction: "increase", budgetCategory: "expedite_shipping", changeOrderId: null, invoiceId: null },
      scheduleImpact: { delayDays: 3, recoveredDays: 0, affectedPhase: "Rough-in", affectedTaskId: "task-drywall", reason: "Drywall shipment delayed by supplier" },
      aiContext: {
        summary: "Drywall delay is expected to affect interior close-in sequencing.",
        keywords: ["drywall", "supplier", "delay"],
        riskSignals: ["critical path material late"],
        confidence: 0.82,
        requiresAttention: true,
      },
    },
    {
      id: "evt-019",
      projectId,
      eventType: "schedule_updated",
      category: "schedule",
      title: "projects.intelligenceEvent.scheduleUpdated.title",
      description: "projects.intelligenceEvent.scheduleUpdated.description",
      occurredAt: iso("2026-04-05T15:40:00-05:00"),
      createdAt: iso("2026-04-05T15:40:00-05:00"),
      actor: actorProjectManager,
      source: "manual",
      priority: "high",
      status: "completed",
      impactAreas: ["schedule", "customer"],
      metadata: { version: "v12", keywords: ["baseline shift", "trade resequence"] },
      relatedEntity: { id: "sch-v12", type: "project", label: "Master Schedule v12", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: { delayDays: 2, recoveredDays: 0, affectedPhase: "Rough-in", affectedTaskId: "task-drywall", reason: "Delay acknowledged and sequence adjusted" },
      aiContext: null,
    },
    {
      id: "evt-020",
      projectId,
      eventType: "site_photo_uploaded",
      category: "sitecam",
      title: "projects.intelligenceEvent.sitePhotoIssue.title",
      description: "projects.intelligenceEvent.sitePhotoIssue.description",
      occurredAt: iso("2026-04-06T10:15:00-05:00"),
      createdAt: iso("2026-04-06T10:16:00-05:00"),
      actor: actorSuperintendent,
      source: "sitecam",
      priority: "normal",
      status: "completed",
      impactAreas: ["documentation", "schedule"],
      metadata: { keywords: ["obstruction", "corridor", "photo evidence"] },
      relatedEntity: { id: "photo-014", type: "site_photo", label: "Blocked corridor photo", href: null },
      attachments: [
        {
          id: "att-photo-2",
          name: "corridor-obstruction.jpg",
          type: "photo",
          url: "/mock/corridor-obstruction.jpg",
          thumbnailUrl: "/mock/corridor-obstruction-thumb.jpg",
        },
      ],
      financialImpact: null,
      scheduleImpact: { delayDays: 1, recoveredDays: 0, affectedPhase: "Rough-in", affectedTaskId: "task-electrical", reason: "Trade area access blocked" },
      aiContext: null,
    },
    {
      id: "evt-021",
      projectId,
      eventType: "inspection_failed",
      category: "inspection",
      title: "projects.intelligenceEvent.inspectionFailed.title",
      description: "projects.intelligenceEvent.inspectionFailed.description",
      occurredAt: iso("2026-04-07T14:35:00-05:00"),
      createdAt: iso("2026-04-07T14:36:00-05:00"),
      actor: actorInspector,
      source: "integration",
      priority: "critical",
      status: "open",
      impactAreas: ["schedule", "documentation", "safety"],
      metadata: { failureCode: "ELEC-17", keywords: ["inspection fail", "bonding"] },
      relatedEntity: { id: "insp-901", type: "inspection", label: "Inspection #901", href: null },
      attachments: [
        {
          id: "att-insp-1",
          name: "inspection-failure-notes.pdf",
          type: "pdf",
          url: "/mock/inspection-failure-notes.pdf",
          thumbnailUrl: null,
        },
      ],
      financialImpact: { amount: 1800, currency: "USD", direction: "increase", budgetCategory: "rework", changeOrderId: null, invoiceId: null },
      scheduleImpact: { delayDays: 4, recoveredDays: 0, affectedPhase: "Rough-in", affectedTaskId: "task-inspection-rework", reason: "Electrical bonding deficiency" },
      aiContext: {
        summary: "Failed inspection has a high chance of delaying drywall start unless corrected within 48 hours.",
        keywords: ["inspection", "rework", "drywall risk"],
        riskSignals: ["critical gate failed", "drywall dependency blocked"],
        confidence: 0.91,
        requiresAttention: true,
      },
    },
    {
      id: "evt-022",
      projectId,
      eventType: "task_created",
      category: "task",
      title: "projects.intelligenceEvent.correctiveTaskCreated.title",
      description: "projects.intelligenceEvent.correctiveTaskCreated.description",
      occurredAt: iso("2026-04-07T16:05:00-05:00"),
      createdAt: iso("2026-04-07T16:06:00-05:00"),
      actor: actorProjectManager,
      source: "manual",
      priority: "critical",
      status: "in_progress",
      impactAreas: ["schedule", "safety"],
      metadata: { taskNumber: "T-220", keywords: ["corrective action", "inspection"] },
      relatedEntity: { id: "task-inspection-rework", type: "task", label: "Correct electrical bonding", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: { delayDays: 1, recoveredDays: 0, affectedPhase: "Rough-in", affectedTaskId: "task-inspection-rework", reason: "Corrective task inserted" },
      aiContext: null,
    },
    {
      id: "evt-023",
      projectId,
      eventType: "task_completed",
      category: "task",
      title: "projects.intelligenceEvent.correctiveTaskCompleted.title",
      description: "projects.intelligenceEvent.correctiveTaskCompleted.description",
      occurredAt: iso("2026-04-08T13:25:00-05:00"),
      createdAt: iso("2026-04-08T13:25:00-05:00"),
      actor: actorSuperintendent,
      source: "manual",
      priority: "high",
      status: "completed",
      impactAreas: ["schedule", "safety"],
      metadata: { keywords: ["rework complete", "ready for reinspection"] },
      relatedEntity: { id: "task-inspection-rework", type: "task", label: "Correct electrical bonding", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: { delayDays: 0, recoveredDays: 1, affectedPhase: "Rough-in", affectedTaskId: "task-inspection-rework", reason: "Rework completed same day" },
      aiContext: null,
    },
    {
      id: "evt-024",
      projectId,
      eventType: "inspection_passed",
      category: "inspection",
      title: "projects.intelligenceEvent.inspectionPassed.title",
      description: "projects.intelligenceEvent.inspectionPassed.description",
      occurredAt: iso("2026-04-09T11:45:00-05:00"),
      createdAt: iso("2026-04-09T11:46:00-05:00"),
      actor: actorInspector,
      source: "integration",
      priority: "high",
      status: "completed",
      impactAreas: ["schedule"],
      metadata: { keywords: ["inspection pass", "release"] },
      relatedEntity: { id: "insp-901", type: "inspection", label: "Inspection #901", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: { delayDays: 0, recoveredDays: 2, affectedPhase: "Rough-in", affectedTaskId: null, reason: "Passed and downstream work released" },
      aiContext: null,
    },
    {
      id: "evt-025",
      projectId,
      eventType: "change_order_created",
      category: "change_order",
      title: "projects.intelligenceEvent.changeOrderCreated.title",
      description: "projects.intelligenceEvent.changeOrderCreated.description",
      occurredAt: iso("2026-04-10T09:55:00-05:00"),
      createdAt: iso("2026-04-10T09:56:00-05:00"),
      actor: actorEstimator,
      source: "manual",
      priority: "high",
      status: "open",
      impactAreas: ["financial", "customer"],
      metadata: { changeOrderNumber: "CO-014", keywords: ["scope increase", "imaging shield"] },
      relatedEntity: { id: "co-014", type: "change_order", label: "Change Order CO-014", href: null },
      attachments: [
        {
          id: "att-co-1",
          name: "co-014-draft.pdf",
          type: "pdf",
          url: "/mock/co-014-draft.pdf",
          thumbnailUrl: null,
        },
      ],
      financialImpact: { amount: 8400, currency: "USD", direction: "increase", budgetCategory: "owner_changes", changeOrderId: "co-014", invoiceId: null },
      scheduleImpact: { delayDays: 1, recoveredDays: 0, affectedPhase: "Drywall", affectedTaskId: null, reason: "Added shielding scope" },
      aiContext: null,
    },
    {
      id: "evt-026",
      projectId,
      eventType: "customer_message",
      category: "customer",
      title: "projects.intelligenceEvent.customerApprovalRequest.title",
      description: "projects.intelligenceEvent.customerApprovalRequest.description",
      occurredAt: iso("2026-04-10T13:40:00-05:00"),
      createdAt: iso("2026-04-10T13:41:00-05:00"),
      actor: actorProjectManager,
      source: "integration",
      priority: "normal",
      status: "completed",
      impactAreas: ["customer"],
      metadata: { keywords: ["change order", "approval requested"] },
      relatedEntity: { id: "co-014", type: "change_order", label: "Change Order CO-014", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-027",
      projectId,
      eventType: "change_order_approved",
      category: "change_order",
      title: "projects.intelligenceEvent.changeOrderApproved.title",
      description: "projects.intelligenceEvent.changeOrderApproved.description",
      occurredAt: iso("2026-04-11T10:10:00-05:00"),
      createdAt: iso("2026-04-11T10:10:00-05:00"),
      actor: actorCustomer,
      source: "integration",
      priority: "high",
      status: "completed",
      impactAreas: ["financial", "schedule", "customer"],
      metadata: { keywords: ["co approved", "scope updated"] },
      relatedEntity: { id: "co-014", type: "change_order", label: "Change Order CO-014", href: null },
      attachments: [],
      financialImpact: { amount: 8400, currency: "USD", direction: "increase", budgetCategory: "owner_changes", changeOrderId: "co-014", invoiceId: null },
      scheduleImpact: { delayDays: 1, recoveredDays: 0, affectedPhase: "Drywall", affectedTaskId: null, reason: "Approved scope added" },
      aiContext: null,
    },
    {
      id: "evt-028",
      projectId,
      eventType: "invoice_created",
      category: "invoice",
      title: "projects.intelligenceEvent.invoiceCreated.title",
      description: "projects.intelligenceEvent.invoiceCreated.description",
      occurredAt: iso("2026-04-14T09:20:00-05:00"),
      createdAt: iso("2026-04-14T09:20:00-05:00"),
      actor: actorSystem,
      source: "system",
      priority: "normal",
      status: "completed",
      impactAreas: ["financial"],
      metadata: { invoiceNumber: "INV-3021", keywords: ["billing", "progress draw"] },
      relatedEntity: { id: "inv-3021", type: "invoice", label: "Invoice INV-3021", href: "/invoices" },
      attachments: [],
      financialImpact: { amount: 51200, currency: "USD", direction: "increase", budgetCategory: "accounts_receivable", changeOrderId: null, invoiceId: "inv-3021" },
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-029",
      projectId,
      eventType: "invoice_sent",
      category: "invoice",
      title: "projects.intelligenceEvent.invoiceSent.title",
      description: "projects.intelligenceEvent.invoiceSent.description",
      occurredAt: iso("2026-04-14T10:05:00-05:00"),
      createdAt: iso("2026-04-14T10:05:00-05:00"),
      actor: actorProjectManager,
      source: "integration",
      priority: "normal",
      status: "completed",
      impactAreas: ["financial", "customer"],
      metadata: { keywords: ["invoice", "sent"] },
      relatedEntity: { id: "inv-3021", type: "invoice", label: "Invoice INV-3021", href: "/invoices" },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-030",
      projectId,
      eventType: "payment_received",
      category: "payment",
      title: "projects.intelligenceEvent.paymentReceived.title",
      description: "projects.intelligenceEvent.paymentReceived.description",
      occurredAt: iso("2026-04-20T15:40:00-05:00"),
      createdAt: iso("2026-04-20T15:41:00-05:00"),
      actor: actorSystem,
      source: "integration",
      priority: "normal",
      status: "completed",
      impactAreas: ["financial"],
      metadata: { paymentNumber: "PMT-771", keywords: ["partial", "payment"] },
      relatedEntity: { id: "pmt-771", type: "payment", label: "Payment PMT-771", href: null },
      attachments: [],
      financialImpact: { amount: 20000, currency: "USD", direction: "decrease", budgetCategory: "accounts_receivable", changeOrderId: null, invoiceId: "inv-3021" },
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-031",
      projectId,
      eventType: "invoice_overdue",
      category: "invoice",
      title: "projects.intelligenceEvent.invoiceOverdue.title",
      description: "projects.intelligenceEvent.invoiceOverdue.description",
      occurredAt: iso("2026-05-02T08:20:00-05:00"),
      createdAt: iso("2026-05-02T08:20:00-05:00"),
      actor: actorSystem,
      source: "system",
      priority: "high",
      status: "open",
      impactAreas: ["financial", "customer"],
      metadata: { daysOverdue: 11, keywords: ["overdue", "invoice"] },
      relatedEntity: { id: "inv-3021", type: "invoice", label: "Invoice INV-3021", href: "/invoices" },
      attachments: [],
      financialImpact: { amount: 31200, currency: "USD", direction: "increase", budgetCategory: "accounts_receivable", changeOrderId: null, invoiceId: "inv-3021" },
      scheduleImpact: null,
      aiContext: {
        summary: "Delayed payment may impact procurement timing for finishing materials.",
        keywords: ["cash flow", "procurement"],
        riskSignals: ["invoice overdue"],
        confidence: 0.79,
        requiresAttention: true,
      },
    },
    {
      id: "evt-032",
      projectId,
      eventType: "daily_report_created",
      category: "daily_report",
      title: "projects.intelligenceEvent.dailyReportMissingGap.title",
      description: "projects.intelligenceEvent.dailyReportMissingGap.description",
      occurredAt: iso("2026-05-03T17:30:00-05:00"),
      createdAt: iso("2026-05-03T17:32:00-05:00"),
      actor: actorAI,
      source: "ai",
      priority: "high",
      status: "open",
      impactAreas: ["documentation"],
      metadata: { missingDays: 2, keywords: ["daily report", "gap"] },
      relatedEntity: { id: "dr-gap-2", type: "daily_report", label: "Missing Daily Reports", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: {
        summary: "Two consecutive days are missing daily reports, reducing schedule confidence.",
        keywords: ["reporting", "compliance"],
        riskSignals: ["documentation gap"],
        confidence: 0.88,
        requiresAttention: true,
      },
    },
    {
      id: "evt-033",
      projectId,
      eventType: "budget_updated",
      category: "budget",
      title: "projects.intelligenceEvent.budgetUpdated.title",
      description: "projects.intelligenceEvent.budgetUpdated.description",
      occurredAt: iso("2026-05-04T11:35:00-05:00"),
      createdAt: iso("2026-05-04T11:35:00-05:00"),
      actor: actorProjectManager,
      source: "manual",
      priority: "normal",
      status: "completed",
      impactAreas: ["financial"],
      metadata: { keywords: ["budget revision", "forecast"] },
      relatedEntity: { id: "budget-v4", type: "project", label: "Budget Forecast v4", href: null },
      attachments: [],
      financialImpact: { amount: 9600, currency: "USD", direction: "increase", budgetCategory: "forecast_adjustment", changeOrderId: null, invoiceId: null },
      scheduleImpact: null,
      aiContext: null,
    },
    {
      id: "evt-034",
      projectId,
      eventType: "schedule_updated",
      category: "schedule",
      title: "projects.intelligenceEvent.scheduleRecovery.title",
      description: "projects.intelligenceEvent.scheduleRecovery.description",
      occurredAt: iso("2026-05-05T14:10:00-05:00"),
      createdAt: iso("2026-05-05T14:10:00-05:00"),
      actor: actorProjectManager,
      source: "manual",
      priority: "normal",
      status: "completed",
      impactAreas: ["schedule"],
      metadata: { keywords: ["recovery plan", "double shift"] },
      relatedEntity: { id: "sch-v14", type: "project", label: "Master Schedule v14", href: null },
      attachments: [],
      financialImpact: { amount: 2400, currency: "USD", direction: "increase", budgetCategory: "overtime", changeOrderId: null, invoiceId: null },
      scheduleImpact: { delayDays: 0, recoveredDays: 2, affectedPhase: "Drywall", affectedTaskId: null, reason: "Added weekend shift to recover time" },
      aiContext: null,
    },
    {
      id: "evt-035",
      projectId,
      eventType: "ai_insight_generated",
      category: "ai",
      title: "projects.intelligenceEvent.aiInsightGenerated.title",
      description: "projects.intelligenceEvent.aiInsightGenerated.description",
      occurredAt: iso("2026-05-06T08:05:00-05:00"),
      createdAt: iso("2026-05-06T08:05:00-05:00"),
      actor: actorAI,
      source: "ai",
      priority: "high",
      status: "open",
      impactAreas: ["schedule", "financial", "customer"],
      metadata: { keywords: ["health score", "delay cause", "timeline chain"] },
      relatedEntity: { id: "ai-insight-220", type: "project", label: "Project Insight #220", href: null },
      attachments: [],
      financialImpact: null,
      scheduleImpact: null,
      aiContext: {
        summary: "Project health score dropped after material delay + failed inspection + change order scope increase.",
        keywords: ["health score", "risk chain"],
        riskSignals: ["compounded delay drivers", "cash risk"],
        confidence: 0.93,
        requiresAttention: true,
      },
      aiExplanation: {
        summary: "The health score decline is driven by compounding dependency and budget pressure events.",
        factors: [
          "Material delivery delayed",
          "Inspection failed",
          "Scope increased after change order approval",
        ],
        recommendedAction: "projects.intelligenceRiskAction.general",
      },
    },
  ];
}

export function createManualNoteEvent(
  projectId: string,
  input: NewManualProjectNoteInput,
  actor: ProjectEventActor,
): ProjectEvent {
  const now = new Date().toISOString();
  const occurredAt = new Date(input.occurredAt).toISOString();
  const idBase = slugify(`${projectId}-${input.title}-${occurredAt}`);

  return {
    id: `evt-note-${idBase}`,
    projectId,
    eventType: "note_added",
    category: input.category,
    title: input.title.trim(),
    description: input.note.trim(),
    occurredAt,
    createdAt: now,
    actor,
    source: "manual",
    priority: input.priority,
    status: "completed",
    impactAreas: ["documentation"],
    metadata: {
      keywords: ["manual note", input.category, input.priority],
      isManualNote: true,
    },
    relatedEntity: input.relatedEntity,
    attachments: [],
    financialImpact: null,
    scheduleImpact: null,
    aiContext: null,
  };
}

function slugify(value: string) {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return normalized.slice(0, 48) || "manual-note";
}

export function buildMockTimelineSummary(events: ProjectEvent[]): ProjectTimelineSummary {
  const sorted = [...events].sort((a, b) => (a.occurredAt > b.occurredAt ? -1 : 1));

  const financialImpactTotal = events.reduce((total, event) => {
    if (!event.financialImpact) {
      return total;
    }

    return total + (event.financialImpact.direction === "increase" ? event.financialImpact.amount : -event.financialImpact.amount);
  }, 0);

  const scheduleDelayDays = events.reduce((total, event) => total + (event.scheduleImpact?.delayDays || 0), 0);
  const scheduleRecoveredDays = events.reduce((total, event) => total + (event.scheduleImpact?.recoveredDays || 0), 0);

  return {
    totalEvents: events.length,
    openRisks: events.filter((event) => event.priority === "critical" || event.aiContext?.requiresAttention).length,
    financialImpactTotal,
    scheduleDelayDays,
    scheduleRecoveredDays,
    lastDailyReportAt: sorted.find((event) => event.eventType === "daily_report_created")?.occurredAt || null,
    lastSiteCamUploadAt: sorted.find((event) => event.eventType === "site_photo_uploaded")?.occurredAt || null,
    latestCustomerActivityAt: sorted.find((event) => event.category === "customer")?.occurredAt || null,
    latestInspectionResult: resolveLatestInspectionResult(sorted),
    latestActivityAt: sorted[0]?.occurredAt || null,
    firstActivityAt: sorted[sorted.length - 1]?.occurredAt || null,
  };
}

export function buildMockRiskSummary(events: ProjectEvent[]): ProjectTimelineRiskItem[] {
  return events
    .filter((event) => event.priority === "critical" || event.aiContext?.requiresAttention || event.eventType === "invoice_overdue")
    .sort((a, b) => (a.occurredAt > b.occurredAt ? -1 : 1))
    .slice(0, 8)
    .map((event) => ({
      id: `risk-${event.id}`,
      severity: event.priority,
      message: deriveRiskMessage(event),
      sourceEventId: event.id,
      occurredAt: event.occurredAt,
      sourceLabel: event.title,
      recommendedAction: deriveRiskAction(event),
      href: event.relatedEntity?.href || null,
    }));
}

function resolveLatestInspectionResult(events: ProjectEvent[]): "passed" | "failed" | "scheduled" | "none" {
  const latest = events.find((event) => event.category === "inspection");

  if (!latest) {
    return "none";
  }

  if (latest.eventType === "inspection_passed") {
    return "passed";
  }

  if (latest.eventType === "inspection_failed") {
    return "failed";
  }

  return "scheduled";
}

function deriveRiskMessage(event: ProjectEvent) {
  if (event.eventType === "material_delayed") {
    return "projects.intelligenceRisk.materialDelayed";
  }

  if (event.eventType === "inspection_failed") {
    return "projects.intelligenceRisk.inspectionFailed";
  }

  if (event.eventType === "daily_report_created" && event.aiContext?.requiresAttention) {
    return "projects.intelligenceRisk.dailyReportGap";
  }

  if (event.eventType === "change_order_approved") {
    return "projects.intelligenceRisk.changeOrderImpact";
  }

  if (event.eventType === "invoice_overdue") {
    return "projects.intelligenceRisk.invoiceOverdue";
  }

  return "projects.intelligenceRisk.general";
}

function deriveRiskAction(event: ProjectEvent) {
  if (event.eventType === "material_delayed") {
    return "projects.intelligenceRiskAction.materialDelayed";
  }

  if (event.eventType === "inspection_failed") {
    return "projects.intelligenceRiskAction.inspectionFailed";
  }

  if (event.eventType === "invoice_overdue") {
    return "projects.intelligenceRiskAction.invoiceOverdue";
  }

  return "projects.intelligenceRiskAction.general";
}
