"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui";
import { getWorkforceTimeCompliance, getWorkforceTimeReviewAccess, listSubmittedWorkforceTime, reviewWorkforceTime, type WorkforceTimeReview } from "@/lib/crews/workforce-time";
import { MobileFieldConfirmAction } from "./mobile-field-confirm-action";

const formatStamp=(value:string)=>new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));

export function MobileTimeApprovals(){
  const[rows,setRows]=useState<WorkforceTimeReview[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState<string|null>(null),[allowed,setAllowed]=useState<boolean|null>(null),decisionRef=useRef("");
  const load=useCallback(async()=>{try{const access=await getWorkforceTimeReviewAccess();setAllowed(access);if(!access){setRows([]);setMessage(null);return;}setRows(await listSubmittedWorkforceTime());}catch(error){setMessage(error instanceof Error?error.message:"Unable to load time approvals.");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const decide=async(id:string,decision:"approved"|"rejected")=>{if(decisionRef.current)return;decisionRef.current=id;setBusy(id);setMessage(null);try{await reviewWorkforceTime(id,decision);setMessage(decision==="approved"?"Time entry approved.":"Time entry rejected.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Unable to review time entry.");await load();}finally{decisionRef.current="";setBusy("");}};
  return <section data-orion-region="mobile-time-approvals" className="rounded-[var(--radius-card)] border border-[var(--border-subtle)] bg-[var(--surface-default)] p-3"><p className="text-sm font-semibold text-[var(--text-primary)]">Time approvals</p>{allowed===false?<p className="mt-2 text-xs text-[var(--text-secondary)]">Time approval controls are available to authorized supervisors and managers.</p>:<div className="mt-3 space-y-2">{rows.map(row=>{const compliance=getWorkforceTimeCompliance(row),locationEvidence=Boolean(row.clockInLocation&&row.clockOutLocation);return <article key={row.id} className="rounded-[var(--radius-card)] border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-3"><p className="text-sm font-medium text-[var(--text-primary)]">{row.employeeName} · {row.hours.toFixed(2)} hours</p><p className="text-xs text-[var(--text-secondary)]">{row.projectName||"No project"} · {formatStamp(row.startedAt)}–{formatStamp(row.endedAt)}</p><p className="text-xs text-[var(--text-secondary)]">Regular {compliance.regularHours.toFixed(2)} · Overtime {compliance.overtimeHours.toFixed(2)} · Break {row.breakMinutes} min</p><p className="mt-1 text-xs text-[var(--text-secondary)]">Location evidence: {locationEvidence?"clock-in and clock-out verified":row.clockInLocation||row.clockOutLocation?"partial":"not captured"}</p>{row.notes?<p className="mt-1 text-xs text-[var(--text-secondary)]">Note: {row.notes}</p>:null}{compliance.requiresAttention?<p role="alert" className="mt-1 text-xs text-[var(--color-warning-700)]">{compliance.missingBreak?"Missing break record. ":""}{compliance.overtimeHours>0?`${compliance.overtimeHours.toFixed(2)} overtime hours require review.`:""}</p>:null}<div className="mt-2 flex flex-wrap gap-2"><Button size="sm" disabled={Boolean(busy)} onClick={()=>void decide(row.id,"approved")}>Approve</Button><MobileFieldConfirmAction label="Reject" confirmLabel="Confirm rejection" description={`Reject ${row.employeeName}'s submitted time entry?`} disabled={Boolean(busy)} onConfirm={()=>decide(row.id,"rejected")}/></div></article>})}{allowed===true&&!rows.length?<p className="text-xs text-[var(--text-secondary)]">No submitted time entries awaiting review.</p>:null}</div>}{message?<p role="status" className="mt-2 text-xs text-[var(--text-secondary)]">{message}</p>:null}</section>;
}
