import { buildGraphEdge } from "./graph-edge-builder";
import { buildGraphNode } from "./graph-node-builder";
import type { GraphEdge, GraphNode } from "./graph-types";

const NOW = "2026-08-02T12:00:00.000Z";

function node(input: Parameters<typeof buildGraphNode>[0]): GraphNode {
  return buildGraphNode(input);
}

function edge(input: Parameters<typeof buildGraphEdge>[0]): GraphEdge {
  return buildGraphEdge(input);
}

export function buildKnowledgeGraphFixtures(): { nodes: GraphNode[]; edges: GraphEdge[]; rootNodeId: string } {
  const nodes: GraphNode[] = [
    node({
      companyId: "company-a",
      entityType: "company",
      entityId: "company-a",
      displayName: "Bango Construction A",
      status: "active",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: {},
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "customer",
      entityId: "cust-riverside",
      displayName: "Riverside Medical",
      status: "active",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { customerType: "commercial" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "project",
      entityId: "proj-riverside",
      displayName: "Riverside Expansion",
      status: "in_progress",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { projectNumber: "PRJ-2001" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "project_phase",
      entityId: "phase-framing",
      displayName: "Framing",
      status: "active",
      freshness: "aging",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { sortOrder: 2 },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "task",
      entityId: "task-1842",
      displayName: "Install MEP racks",
      status: "in_progress",
      freshness: "aging",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { priority: "high" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "crew",
      entityId: "crew-alpha",
      displayName: "Crew Alpha",
      status: "active",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { crewCode: "A-01" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "employee",
      entityId: "emp-maya",
      displayName: "Maya Rivera",
      status: "active",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { role: "superintendent" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "equipment",
      entityId: "equip-lift-44",
      displayName: "Lift 44",
      status: "maintenance",
      freshness: "stale",
      dataCompleteness: { isComplete: false, missingFields: ["lastServiceDate"] },
      source: "fixture",
      attributes: { maintenanceStatus: "overdue" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "invoice",
      entityId: "inv-1842",
      displayName: "Invoice #1842",
      status: "sent",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { totalAmount: 145000 },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "change_order",
      entityId: "co-7",
      displayName: "Change Order #7",
      status: "pending_approval",
      freshness: "aging",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { scheduleImpactDays: 4 },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "vendor",
      entityId: "vendor-steelworks",
      displayName: "SteelWorks Supply",
      status: "active",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { preferredVendor: true },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "purchase_order",
      entityId: "po-332",
      displayName: "PO #332",
      status: "open",
      freshness: "aging",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { expectedDelivery: "2026-08-05" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "schedule_event",
      entityId: "sched-delivery-12",
      displayName: "Steel Delivery Window",
      status: "at_risk",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { period: "morning" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "inspection",
      entityId: "insp-901",
      displayName: "Framing Inspection",
      status: "scheduled",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { severity: "high" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "document",
      entityId: "doc-proj-risks",
      displayName: "Project Risk Register",
      status: "active",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { category: "risk" },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-a",
      entityType: "payment",
      entityId: "pay-1842-a",
      displayName: "Payment #1842-A",
      status: "posted",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: { amount: 85000 },
      createdAt: NOW,
      updatedAt: NOW,
    }),
    node({
      companyId: "company-b",
      entityType: "project",
      entityId: "proj-other-company",
      displayName: "Other Company Project",
      status: "active",
      freshness: "fresh",
      dataCompleteness: { isComplete: true, missingFields: [] },
      source: "fixture",
      attributes: {},
      createdAt: NOW,
      updatedAt: NOW,
    }),
  ];

  const nodeByTypeId = new Map(nodes.map((item) => [`${item.entityType}:${item.entityId}`, item.id]));
  const getNodeId = (entityType: string, entityId: string) => nodeByTypeId.get(`${entityType}:${entityId}`) ?? "missing";

  const edges: GraphEdge[] = [
    edge({
      companyId: "company-a",
      fromEntityType: "company",
      fromEntityId: "company-a",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("company", "company-a"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "owns",
      direction: "directed",
      confidence: 0.95,
      freshness: "fresh",
      evidence: ["projects.company_id"],
      activeFrom: "2026-01-01T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.company_owns_project",
      ruleVersion: "1.0.0",
      timeWindowClass: "lifecycle_active",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "project",
      fromEntityId: "proj-riverside",
      toEntityType: "customer",
      toEntityId: "cust-riverside",
      fromNodeId: getNodeId("project", "proj-riverside"),
      toNodeId: getNodeId("customer", "cust-riverside"),
      relationshipType: "belongs_to",
      direction: "directed",
      confidence: 0.92,
      freshness: "fresh",
      evidence: ["projects.customer_id"],
      activeFrom: "2026-01-01T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.project_belongs_to_customer",
      ruleVersion: "1.0.0",
      timeWindowClass: "lifecycle_active",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "crew",
      fromEntityId: "crew-alpha",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("crew", "crew-alpha"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "assigned_to",
      direction: "directed",
      confidence: 0.87,
      freshness: "fresh",
      evidence: ["workforce_assignments.project_id"],
      activeFrom: "2026-07-15T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.crew_assigned_project",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "employee",
      fromEntityId: "emp-maya",
      toEntityType: "crew",
      toEntityId: "crew-alpha",
      fromNodeId: getNodeId("employee", "emp-maya"),
      toNodeId: getNodeId("crew", "crew-alpha"),
      relationshipType: "belongs_to",
      direction: "directed",
      confidence: 0.9,
      freshness: "fresh",
      evidence: ["crew_memberships.crew_id"],
      activeFrom: "2026-07-01T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.employee_belongs_crew",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "equipment",
      fromEntityId: "equip-lift-44",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("equipment", "equip-lift-44"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "assigned_to",
      direction: "directed",
      confidence: 0.77,
      freshness: "stale",
      evidence: ["equipment.assigned_job_id"],
      activeFrom: "2026-06-20T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.equipment_assigned_project",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "task",
      fromEntityId: "task-1842",
      toEntityType: "project_phase",
      toEntityId: "phase-framing",
      fromNodeId: getNodeId("task", "task-1842"),
      toNodeId: getNodeId("project_phase", "phase-framing"),
      relationshipType: "belongs_to",
      direction: "directed",
      confidence: 0.9,
      freshness: "aging",
      evidence: ["tasks.phase_id"],
      activeFrom: "2026-07-20T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.task_belongs_phase",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "project_phase",
      fromEntityId: "phase-framing",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("project_phase", "phase-framing"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "belongs_to",
      direction: "directed",
      confidence: 0.93,
      freshness: "fresh",
      evidence: ["project_phases.project_id"],
      activeFrom: "2026-07-01T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.phase_belongs_project",
      ruleVersion: "1.0.0",
      timeWindowClass: "lifecycle_active",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "invoice",
      fromEntityId: "inv-1842",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("invoice", "inv-1842"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "billed_by",
      direction: "directed",
      confidence: 0.95,
      freshness: "fresh",
      evidence: ["invoices.project_id"],
      activeFrom: "2026-08-01T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.invoice_billed_project",
      ruleVersion: "1.0.0",
      timeWindowClass: "invoice_cycle",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "invoice",
      fromEntityId: "inv-1842",
      toEntityType: "change_order",
      toEntityId: "co-7",
      fromNodeId: getNodeId("invoice", "inv-1842"),
      toNodeId: getNodeId("change_order", "co-7"),
      relationshipType: "linked_to",
      direction: "directed",
      confidence: 0.88,
      freshness: "aging",
      evidence: ["change_order_invoice_links.invoice_id"],
      activeFrom: "2026-08-01T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.invoice_linked_change_order",
      ruleVersion: "1.0.0",
      timeWindowClass: "invoice_cycle",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "change_order",
      fromEntityId: "co-7",
      toEntityType: "customer",
      toEntityId: "cust-riverside",
      fromNodeId: getNodeId("change_order", "co-7"),
      toNodeId: getNodeId("customer", "cust-riverside"),
      relationshipType: "approved_by",
      direction: "directed",
      confidence: 0.83,
      freshness: "aging",
      evidence: ["change_orders.customer_id", "change_orders.status=pending_approval"],
      activeFrom: "2026-08-01T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.change_order_approved_by_customer",
      ruleVersion: "1.0.0",
      timeWindowClass: "approval_window",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "purchase_order",
      fromEntityId: "po-332",
      toEntityType: "vendor",
      toEntityId: "vendor-steelworks",
      fromNodeId: getNodeId("purchase_order", "po-332"),
      toNodeId: getNodeId("vendor", "vendor-steelworks"),
      relationshipType: "supplied_by",
      direction: "directed",
      confidence: 0.91,
      freshness: "fresh",
      evidence: ["purchase_order.vendor_id"],
      activeFrom: "2026-07-25T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.purchase_order_supplied_by_vendor",
      ruleVersion: "1.0.0",
      timeWindowClass: "po_open",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "purchase_order",
      fromEntityId: "po-332",
      toEntityType: "schedule_event",
      toEntityId: "sched-delivery-12",
      fromNodeId: getNodeId("purchase_order", "po-332"),
      toNodeId: getNodeId("schedule_event", "sched-delivery-12"),
      relationshipType: "affects",
      direction: "directed",
      confidence: 0.79,
      freshness: "aging",
      evidence: ["delivery_window_change"],
      activeFrom: "2026-08-02T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.delivery_affects_schedule",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "inspection",
      fromEntityId: "insp-901",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("inspection", "insp-901"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "inspected_by",
      direction: "directed",
      confidence: 0.89,
      freshness: "fresh",
      evidence: ["inspection.project_id"],
      activeFrom: "2026-08-03T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.inspection_project",
      ruleVersion: "1.0.0",
      timeWindowClass: "inspection_window",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "document",
      fromEntityId: "doc-proj-risks",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("document", "doc-proj-risks"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "documented_by",
      direction: "directed",
      confidence: 0.84,
      freshness: "fresh",
      evidence: ["document.project_id"],
      activeFrom: "2026-07-28T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.document_project",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "payment",
      fromEntityId: "pay-1842-a",
      toEntityType: "invoice",
      toEntityId: "inv-1842",
      fromNodeId: getNodeId("payment", "pay-1842-a"),
      toNodeId: getNodeId("invoice", "inv-1842"),
      relationshipType: "paid_by",
      direction: "directed",
      confidence: 0.96,
      freshness: "fresh",
      evidence: ["invoice_payment_history.invoice_id"],
      activeFrom: "2026-08-02T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.payment_settles_invoice",
      ruleVersion: "1.0.0",
      timeWindowClass: "payment_window",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "task",
      fromEntityId: "task-1842",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("task", "task-1842"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "depends_on",
      direction: "bidirectional",
      confidence: 0.7,
      freshness: "unknown",
      evidence: ["task_dependencies.task_id"],
      activeFrom: "2026-07-20T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.task_project_dependency",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "schedule_event",
      fromEntityId: "sched-delivery-12",
      toEntityType: "task",
      toEntityId: "task-1842",
      fromNodeId: getNodeId("schedule_event", "sched-delivery-12"),
      toNodeId: getNodeId("task", "task-1842"),
      relationshipType: "scheduled_for",
      direction: "directed",
      confidence: 0.8,
      freshness: "fresh",
      evidence: ["schedule.assignment.task_id"],
      activeFrom: "2026-08-02T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.schedule_task",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-a",
      fromEntityType: "invoice",
      fromEntityId: "inv-1842",
      toEntityType: "document",
      toEntityId: "doc-missing",
      fromNodeId: getNodeId("invoice", "inv-1842"),
      toNodeId: "missing-node-reference",
      relationshipType: "related_to",
      direction: "directed",
      confidence: 0.5,
      freshness: "unknown",
      evidence: ["external_link_reference"],
      activeFrom: "2026-08-02T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.unresolved_reference",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
    edge({
      companyId: "company-b",
      fromEntityType: "project",
      fromEntityId: "proj-other-company",
      toEntityType: "project",
      toEntityId: "proj-riverside",
      fromNodeId: getNodeId("project", "proj-other-company"),
      toNodeId: getNodeId("project", "proj-riverside"),
      relationshipType: "related_to",
      direction: "directed",
      confidence: 0.9,
      freshness: "fresh",
      evidence: ["cross_company_test"],
      activeFrom: "2026-08-02T00:00:00.000Z",
      activeTo: null,
      ruleId: "kg.cross_company_edge",
      ruleVersion: "1.0.0",
      timeWindowClass: "week_current",
    }),
  ];

  const rootNodeId = getNodeId("invoice", "inv-1842");

  return { nodes, edges, rootNodeId };
}
