import type { DecisionPack } from "../decision-engine/types";
import { buildDeterministicMemoryId } from "./memory-signature";
import { ORION_MEMORY_DEFAULTS, type OrionOrganizationalMemoryRecord, type OrionSignalMemoryInput } from "./memory-types";

type FixtureMemoryInput = Omit<OrionOrganizationalMemoryRecord, "id" | "memoryVersion">;

function makeMemory(input: FixtureMemoryInput): OrionOrganizationalMemoryRecord {
  return {
    ...input,
    id: buildDeterministicMemoryId({
      companyId: input.companyId,
      sourceSignalId: input.sourceSignalId,
      sourceDecisionPackId: input.sourceDecisionPackId,
      ruleId: input.ruleId,
      ruleVersion: input.ruleVersion,
      memoryVersion: ORION_MEMORY_DEFAULTS.memoryVersion,
    }),
    memoryVersion: ORION_MEMORY_DEFAULTS.memoryVersion,
  };
}

export function buildOrionMemoryFixtures(): OrionOrganizationalMemoryRecord[] {
  return [
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-crew-missing-1",
      sourceDecisionPackId: "pack-crew-1",
      category: "Workforce",
      signalType: "crew_missing_update",
      entityReferences: [{ entityType: "crew", entityId: "crew-alpha", companyId: "company-a" }],
      normalizedObservation: "crew alpha missing daily update",
      normalizedEvidenceKeys: ["missing_update", "daily_report_gap", "supervisor_contact_required"],
      businessImpact: "MEDIUM",
      severity: "high",
      confidence: 0.72,
      freshness: "partial",
      detectedAt: "2026-07-14T12:00:00.000Z",
      resolvedAt: "2026-07-14T18:00:00.000Z",
      outcome: {
        state: "resolved_successfully",
        summary: "Supervisor contact restored updates.",
        evidence: ["daily-report-112"],
        actionTaken: "Supervisor contact",
        result: "Update cadence restored",
        measuredImpact: { metric: "report_submission_gap_hours", value: 2, unit: "hours" },
        limitations: [],
        verifiedAt: "2026-07-15T08:00:00.000Z",
        verifiedBy: "sup-1",
        confidence: 0.9,
      },
      actionsTaken: ["Supervisor contact"],
      measurableResult: { metric: "report_submission_gap_hours", value: 2, unit: "hours" },
      lessonsLearned: ["Supervisor outreach within same shift improves compliance."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "workforce.crew_missing_update",
      ruleVersion: "1.0.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-crew-missing-2",
      sourceDecisionPackId: "pack-crew-2",
      category: "Workforce",
      signalType: "crew_missing_update",
      entityReferences: [{ entityType: "crew", entityId: "crew-alpha", companyId: "company-a" }],
      normalizedObservation: "crew alpha update lag repeated",
      normalizedEvidenceKeys: ["missing_update", "daily_report_gap", "supervisor_contact_required"],
      businessImpact: "MEDIUM",
      severity: "high",
      confidence: 0.74,
      freshness: "partial",
      detectedAt: "2026-07-21T12:00:00.000Z",
      resolvedAt: "2026-07-21T20:00:00.000Z",
      outcome: {
        state: "resolved_successfully",
        summary: "Supervisor contact restored updates.",
        evidence: ["daily-report-126"],
        actionTaken: "Supervisor contact",
        result: "Update cadence restored",
        measuredImpact: { metric: "report_submission_gap_hours", value: 3, unit: "hours" },
        limitations: [],
        verifiedAt: "2026-07-22T08:00:00.000Z",
        verifiedBy: "sup-1",
        confidence: 0.88,
      },
      actionsTaken: ["Supervisor contact"],
      measurableResult: { metric: "report_submission_gap_hours", value: 3, unit: "hours" },
      lessonsLearned: ["Repeat outreach to same crew should include next-day check."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "workforce.crew_missing_update",
      ruleVersion: "1.0.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-crew-missing-3",
      sourceDecisionPackId: "pack-crew-3",
      category: "Workforce",
      signalType: "crew_missing_update",
      entityReferences: [{ entityType: "crew", entityId: "crew-alpha", companyId: "company-a" }],
      normalizedObservation: "crew alpha submitted late report",
      normalizedEvidenceKeys: ["missing_update", "daily_report_gap", "supervisor_contact_required"],
      businessImpact: "MEDIUM",
      severity: "high",
      confidence: 0.69,
      freshness: "partial",
      detectedAt: "2026-07-28T12:00:00.000Z",
      resolvedAt: "2026-07-29T14:00:00.000Z",
      outcome: {
        state: "resolved_unsuccessfully",
        summary: "Initial outreach did not restore same-day compliance.",
        evidence: ["daily-report-132"],
        actionTaken: "Supervisor contact",
        result: "Partial compliance only",
        measuredImpact: null,
        limitations: ["No verified reduction in delay."],
        verifiedAt: "2026-07-30T08:00:00.000Z",
        verifiedBy: "sup-2",
        confidence: 0.67,
      },
      actionsTaken: ["Supervisor contact"],
      measurableResult: null,
      lessonsLearned: ["Escalation path is needed for repeated missing updates."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "workforce.crew_missing_update",
      ruleVersion: "1.0.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-equip-inspection-1",
      sourceDecisionPackId: "pack-equip-1",
      category: "Equipment",
      signalType: "equipment_inspection_warning",
      entityReferences: [{ entityType: "equipment", entityId: "equip-44", companyId: "company-a" }],
      normalizedObservation: "inspection warning on lift equip-44",
      normalizedEvidenceKeys: ["inspection_warning", "maintenance_due", "missing_update"],
      businessImpact: "HIGH",
      severity: "high",
      confidence: 0.78,
      freshness: "live",
      detectedAt: "2026-07-07T11:00:00.000Z",
      resolvedAt: null,
      outcome: {
        state: "unresolved",
        summary: null,
        evidence: ["maintenance-log-12"],
        actionTaken: "Work order requested",
        result: null,
        measuredImpact: null,
        limitations: ["Repair verification pending."],
        verifiedAt: null,
        verifiedBy: null,
        confidence: 0.5,
      },
      actionsTaken: ["Work order requested"],
      measurableResult: null,
      lessonsLearned: ["Inspection alerts should trigger same-day maintenance window."],
      dataCompleteness: { isComplete: false, missingInformationKeys: ["maintenance_completed_at"] },
      ruleId: "equipment.inspection_warning",
      ruleVersion: "1.1.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-customer-delay-1",
      sourceDecisionPackId: "pack-customer-1",
      category: "Customer",
      signalType: "customer_approval_delay",
      entityReferences: [{ entityType: "customer", entityId: "customer-westwood", companyId: "company-a" }],
      normalizedObservation: "approval delay for westwood",
      normalizedEvidenceKeys: ["approval_delay", "change_order_pending"],
      businessImpact: "HIGH",
      severity: "high",
      confidence: 0.76,
      freshness: "live",
      detectedAt: "2026-06-30T16:00:00.000Z",
      resolvedAt: "2026-07-03T18:00:00.000Z",
      outcome: {
        state: "resolved_partially",
        summary: "Approval arrived after escalation.",
        evidence: ["approval-ticket-551"],
        actionTaken: "Escalate approval reminder",
        result: "Delay reduced but not removed",
        measuredImpact: { metric: "approval_delay_days", value: 3, unit: "days" },
        limitations: ["Still outside target timeline."],
        verifiedAt: "2026-07-05T10:00:00.000Z",
        verifiedBy: "pm-7",
        confidence: 0.73,
      },
      actionsTaken: ["Escalate approval reminder"],
      measurableResult: { metric: "approval_delay_days", value: 3, unit: "days" },
      lessonsLearned: ["Escalation helps but does not eliminate customer approval delays."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "customer.approval_delay",
      ruleVersion: "1.0.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-schedule-compress-1",
      sourceDecisionPackId: "pack-schedule-1",
      category: "Schedule",
      signalType: "schedule_compression",
      entityReferences: [{ entityType: "project", entityId: "project-riverwalk", companyId: "company-a" }],
      normalizedObservation: "schedule compression at riverwalk",
      normalizedEvidenceKeys: ["schedule_compression", "critical_path_shift"],
      businessImpact: "HIGH",
      severity: "medium",
      confidence: 0.71,
      freshness: "partial",
      detectedAt: "2026-05-26T10:00:00.000Z",
      resolvedAt: "2026-05-28T20:00:00.000Z",
      outcome: {
        state: "resolved_successfully",
        summary: "Weekend resequencing recovered schedule.",
        evidence: ["schedule-log-88"],
        actionTaken: "Weekend resequencing",
        result: "Milestone regained",
        measuredImpact: { metric: "days_recovered", value: 2, unit: "days" },
        limitations: [],
        verifiedAt: "2026-05-30T09:00:00.000Z",
        verifiedBy: "sched-2",
        confidence: 0.81,
      },
      actionsTaken: ["Weekend resequencing"],
      measurableResult: { metric: "days_recovered", value: 2, unit: "days" },
      lessonsLearned: ["Early resequencing can recover compressed schedules."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "schedule.compression",
      ruleVersion: "2.0.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-insufficient-1",
      sourceDecisionPackId: "pack-insufficient-1",
      category: "Workforce",
      signalType: "crew_missing_update",
      entityReferences: [{ entityType: "crew", entityId: "crew-bravo", companyId: "company-a" }],
      normalizedObservation: "missing update with sparse context",
      normalizedEvidenceKeys: ["missing_update"],
      businessImpact: "LOW",
      severity: "medium",
      confidence: 0.41,
      freshness: "unknown",
      detectedAt: "2026-04-14T09:00:00.000Z",
      resolvedAt: null,
      outcome: {
        state: "insufficient_data",
        summary: "Evidence did not support a verified outcome.",
        evidence: ["daily-report-77"],
        actionTaken: null,
        result: null,
        measuredImpact: null,
        limitations: ["Missing supervisor follow-up confirmation."],
        verifiedAt: null,
        verifiedBy: null,
        confidence: 0.31,
      },
      actionsTaken: [],
      measurableResult: null,
      lessonsLearned: ["Need complete follow-up evidence before outcome statements."],
      dataCompleteness: { isComplete: false, missingInformationKeys: ["follow_up_confirmed"] },
      ruleId: "workforce.crew_missing_update",
      ruleVersion: "1.0.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-false-positive-1",
      sourceDecisionPackId: "pack-false-positive-1",
      category: "Safety",
      signalType: "inspection_noncompliance",
      entityReferences: [{ entityType: "project", entityId: "project-riverwalk", companyId: "company-a" }],
      normalizedObservation: "apparent noncompliance flagged",
      normalizedEvidenceKeys: ["inspection_warning", "photo_mismatch"],
      businessImpact: "MEDIUM",
      severity: "medium",
      confidence: 0.58,
      freshness: "live",
      detectedAt: "2026-03-03T09:00:00.000Z",
      resolvedAt: "2026-03-03T12:00:00.000Z",
      outcome: {
        state: "false_positive",
        summary: "Inspection flag resolved as duplicate image metadata issue.",
        evidence: ["inspection-audit-14"],
        actionTaken: "Metadata verification",
        result: "No true noncompliance",
        measuredImpact: null,
        limitations: [],
        verifiedAt: "2026-03-03T14:00:00.000Z",
        verifiedBy: "safety-1",
        confidence: 0.87,
      },
      actionsTaken: ["Metadata verification"],
      measurableResult: null,
      lessonsLearned: ["Duplicate inspection metadata can produce false positives."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "safety.inspection_noncompliance",
      ruleVersion: "1.0.0",
    }),
    makeMemory({
      companyId: "company-b",
      sourceSignalId: "sig-cross-company-1",
      sourceDecisionPackId: "pack-cross-company-1",
      category: "Workforce",
      signalType: "crew_missing_update",
      entityReferences: [{ entityType: "crew", entityId: "crew-alpha", companyId: "company-b" }],
      normalizedObservation: "cross company memory should be ignored",
      normalizedEvidenceKeys: ["missing_update", "daily_report_gap"],
      businessImpact: "MEDIUM",
      severity: "high",
      confidence: 0.8,
      freshness: "partial",
      detectedAt: "2026-07-22T10:00:00.000Z",
      resolvedAt: "2026-07-23T12:00:00.000Z",
      outcome: {
        state: "resolved_successfully",
        summary: "Other company case.",
        evidence: ["other-company-log"],
        actionTaken: "Supervisor contact",
        result: "Resolved",
        measuredImpact: { metric: "gap_hours", value: 1, unit: "hours" },
        limitations: [],
        verifiedAt: "2026-07-24T08:00:00.000Z",
        verifiedBy: "sup-b",
        confidence: 0.9,
      },
      actionsTaken: ["Supervisor contact"],
      measurableResult: { metric: "gap_hours", value: 1, unit: "hours" },
      lessonsLearned: ["Must never leak across company boundaries."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "workforce.crew_missing_update",
      ruleVersion: "1.0.0",
    }),
    makeMemory({
      companyId: "company-a",
      sourceSignalId: "sig-old-relevant-1",
      sourceDecisionPackId: "pack-old-relevant-1",
      category: "Workforce",
      signalType: "crew_missing_update",
      entityReferences: [{ entityType: "crew", entityId: "crew-alpha", companyId: "company-a" }],
      normalizedObservation: "historical crew update issue",
      normalizedEvidenceKeys: ["missing_update", "daily_report_gap"],
      businessImpact: "MEDIUM",
      severity: "high",
      confidence: 0.66,
      freshness: "stale",
      detectedAt: "2024-12-10T10:00:00.000Z",
      resolvedAt: "2024-12-14T10:00:00.000Z",
      outcome: {
        state: "resolved_successfully",
        summary: "Historical intervention restored reporting.",
        evidence: ["archive-log-01"],
        actionTaken: "Supervisor contact",
        result: "Reporting resumed",
        measuredImpact: { metric: "gap_hours", value: 4, unit: "hours" },
        limitations: ["Historical context may not reflect current staffing."],
        verifiedAt: "2024-12-20T10:00:00.000Z",
        verifiedBy: "sup-legacy",
        confidence: 0.71,
      },
      actionsTaken: ["Supervisor contact"],
      measurableResult: { metric: "gap_hours", value: 4, unit: "hours" },
      lessonsLearned: ["Old signals can still be relevant for repeated crews."],
      dataCompleteness: { isComplete: true, missingInformationKeys: [] },
      ruleId: "workforce.crew_missing_update",
      ruleVersion: "1.0.0",
    }),
  ];
}

export function buildCurrentCrewMissingUpdateSignal(): OrionSignalMemoryInput {
  return {
    signalId: "sig-current-crew-alpha",
    companyId: "company-a",
    category: "Workforce",
    signalType: "crew_missing_update",
    entityReferences: [{ entityType: "crew", entityId: "crew-alpha", companyId: "company-a" }],
    normalizedObservation: "crew alpha missed daily update",
    normalizedEvidenceKeys: ["missing_update", "daily_report_gap", "supervisor_contact_required"],
    businessImpact: "MEDIUM",
    severity: "high",
    freshness: "partial",
    detectedAt: "2026-08-01T10:00:00.000Z",
    dataCompleteness: {
      isComplete: true,
      missingInformationKeys: [],
    },
    ruleId: "workforce.crew_missing_update",
    ruleVersion: "1.0.0",
  };
}

export function buildCurrentCrewDecisionPack(): DecisionPack {
  return {
    signalId: "sig-current-crew-alpha",
    observation: "Crew Alpha missed daily update",
    businessImpact: "MEDIUM",
    evidence: [
      {
        id: "ev-1",
        label: "Daily report not submitted",
        value: "missing_update",
        source: "daily_report",
        observedAt: "2026-08-01T10:00:00.000Z",
      },
    ],
    confidence: {
      percent: 71,
      reasons: ["Daily report gap observed", "Freshness is partial"],
    },
    missingInformation: [],
    recommendation: {
      title: "Contact supervisor",
      reason: "Recurring reporting gap",
      expectedOutcome: "Restore update cadence",
      estimatedPriority: "high",
      approvalRequired: "none_required",
    },
    approvalBoundary: "none_required",
    relatedSignals: [],
  };
}
