"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";

type Target = { id:string; name?:string; title?:string; project_number?:string|null; estimate_number?:string|null; status?:string };
type Point = { x:number; y:number };
type SavedMeasurement = { id:string; label:string; measurement_type:string; value_inches:number; method:string; confidence:string; created_at:string };
type UnitMode = "imperial" | "metric";

function distance(a:Point,b:Point){ return Math.hypot(b.x-a.x,b.y-a.y); }
function formatInches(value:number){ const feet=Math.floor(value/12); const inches=value-feet*12; return feet ? `${feet}' ${inches.toFixed(1)}\"` : `${inches.toFixed(1)}\"`; }
function displayValue(inches:number,unit:UnitMode){ return unit === "metric" ? `${(inches*2.54).toFixed(1)} cm` : formatInches(inches); }
function toInches(value:number,unit:UnitMode){ return unit === "metric" ? value/2.54 : value; }
function fromInches(value:number,unit:UnitMode){ return unit === "metric" ? value*2.54 : value; }

export function MeasureClient(){
  const search=useSearchParams();
  const canvasRef=useRef<HTMLCanvasElement>(null);
  const videoRef=useRef<HTMLVideoElement>(null);
  const imageRef=useRef<HTMLImageElement|null>(null);
  const streamRef=useRef<MediaStream|null>(null);
  const objectUrlRef=useRef<string|null>(null);
  const [projects,setProjects]=useState<Target[]>([]); const [estimates,setEstimates]=useState<Target[]>([]);
  const [targetType,setTargetType]=useState(search.get("estimateId") ? "estimate" : "project");
  const [targetId,setTargetId]=useState(search.get("projectId") || search.get("estimateId") || "");
  const [photo,setPhoto]=useState<File|null>(null); const [points,setPoints]=useState<Point[]>([]);
  const [reference,setReference]=useState(12); const [verified,setVerified]=useState(0); const [unit,setUnit]=useState<UnitMode>("imperial");
  const [label,setLabel]=useState(""); const [measurementType,setMeasurementType]=useState("length"); const [notes,setNotes]=useState("");
  const [saved,setSaved]=useState<SavedMeasurement[]>([]); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const [cameraOpen,setCameraOpen]=useState(false); const [cameraError,setCameraError]=useState("");

  useEffect(()=>{ fetch("/api/measure").then(r=>r.json()).then(j=>{ if(j.ok){setProjects(j.projects||[]);setEstimates(j.estimates||[]);} }); },[]);
  useEffect(()=>{ if(!targetId)return; fetch(`/api/measure?targetType=${targetType}&targetId=${encodeURIComponent(targetId)}`).then(r=>r.json()).then(j=>{if(j.ok)setSaved(j.measurements||[])}); },[targetType,targetId]);

  const stopCamera=useCallback(()=>{ streamRef.current?.getTracks().forEach(track=>track.stop()); streamRef.current=null; setCameraOpen(false); },[]);
  useEffect(()=>()=>{ streamRef.current?.getTracks().forEach(track=>track.stop()); if(objectUrlRef.current)URL.revokeObjectURL(objectUrlRef.current); },[]);

  const calculated=useMemo(()=>{ if(points.length<4||reference<=0)return 0; const refPx=distance(points[0],points[1]); return refPx ? reference*distance(points[2],points[3])/refPx : 0; },[points,reference]);
  const calibrationQuality=useMemo(()=>{ if(points.length<2)return null; const px=distance(points[0],points[1]); return px>=240?"Good":px>=120?"Fair":"Low"; },[points]);

  const redraw=useCallback(()=>{ const canvas=canvasRef.current,img=imageRef.current;if(!canvas||!img)return; const max=1200,scale=Math.min(1,max/img.naturalWidth); canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale); const ctx=canvas.getContext("2d");if(!ctx)return;ctx.drawImage(img,0,0,canvas.width,canvas.height); points.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,9,0,Math.PI*2);ctx.fillStyle=i<2?"#f59e0b":"#22c55e";ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#fff";ctx.stroke();}); if(points.length>=2){ctx.strokeStyle="#f59e0b";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);ctx.lineTo(points[1].x,points[1].y);ctx.stroke();} if(points.length>=4){ctx.strokeStyle="#22c55e";ctx.beginPath();ctx.moveTo(points[2].x,points[2].y);ctx.lineTo(points[3].x,points[3].y);ctx.stroke();} },[points]);
  useEffect(()=>{redraw();},[redraw]);

  function choosePhoto(file:File|null){ setPhoto(file);setPoints([]);setVerified(0);setMessage(""); if(objectUrlRef.current){URL.revokeObjectURL(objectUrlRef.current);objectUrlRef.current=null;} if(!file){imageRef.current=null;return;} const img=new Image();const url=URL.createObjectURL(file);objectUrlRef.current=url;img.onload=()=>{imageRef.current=img;redraw()};img.src=url; }

  async function startCamera(){ setCameraError(""); try{ if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera unavailable"); const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});streamRef.current=stream;setCameraOpen(true);requestAnimationFrame(()=>{if(videoRef.current){videoRef.current.srcObject=stream;void videoRef.current.play();}});}catch{setCameraError("Camera access was blocked or is unavailable. Use Take Photo instead, or allow Camera access in your browser settings.");} }
  function captureCamera(){ const video=videoRef.current;if(!video||video.videoWidth===0)return;const capture=document.createElement("canvas");capture.width=video.videoWidth;capture.height=video.videoHeight;capture.getContext("2d")?.drawImage(video,0,0);capture.toBlob(blob=>{if(!blob)return;choosePhoto(new File([blob],`bos-measure-${Date.now()}.jpg`,{type:"image/jpeg"}));stopCamera();},"image/jpeg",0.92); }

  function tapCanvas(e:React.MouseEvent<HTMLCanvasElement>){ if(points.length>=4)return; if(points.length>=2&&reference<=0){setMessage("Enter a known reference length before marking the measurement.");return;} const c=e.currentTarget,r=c.getBoundingClientRect(); const next=[...points,{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}]; setPoints(next);setMessage(""); if(next.length===4&&reference>0){const refPx=distance(next[0],next[1]);if(refPx>0)setVerified(Number((reference*distance(next[2],next[3])/refPx).toFixed(2)));} }
  function resetPoints(){setPoints([]);setVerified(0);setMessage("");}
  function setReferencePreset(inches:number){setReference(inches);setPoints([]);setVerified(0);}

  async function save(){ if(!targetId||!label.trim()||verified<=0){setMessage("Choose a project or estimate, add a label, and verify the measurement.");return;} setSaving(true);setMessage(""); const f=new FormData();f.set("targetType",targetType);f.set("targetId",targetId);f.set("label",label.trim());f.set("measurementType",measurementType);f.set("valueInches",String(verified));f.set("referenceInches",String(reference||0));f.set("notes",notes);if(photo)f.set("photo",photo); const res=await fetch("/api/measure",{method:"POST",body:f});const j=await res.json();setSaving(false);if(!j.ok){setMessage(j.error||"Could not save measurement.");return;}setMessage("Measurement saved to B.O.S.");setLabel("");setNotes("");resetPoints(); const refresh=await fetch(`/api/measure?targetType=${targetType}&targetId=${encodeURIComponent(targetId)}`).then(r=>r.json());if(refresh.ok)setSaved(refresh.measurements||[]); }

  const targets=targetType==="project"?projects:estimates;
  const step=points.length<2?"Mark the known reference":points.length<4?"Mark what you want to measure":"Review the calculated dimension";
  return <div className="mx-auto max-w-6xl space-y-6 p-4 md:p-6">
    <header><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-500">B.O.S. Field Tool · Measure Phase 2</p><h1 className="text-3xl font-bold">B.O.S. Measure</h1><p className="mt-2 text-sm text-muted-foreground">Use the live camera or a photo, calibrate from a known dimension, and let B.O.S. calculate the target measurement. Verify critical dimensions before estimating or ordering.</p></header>
    <section className="grid gap-4 rounded-2xl border bg-card p-4 md:grid-cols-4"><label className="text-sm font-medium">Save to<select className="mt-2 w-full rounded-lg border bg-background p-2" value={targetType} onChange={e=>{setTargetType(e.target.value);setTargetId("")}}><option value="project">Project</option><option value="estimate">Estimate</option></select></label><label className="text-sm font-medium md:col-span-2">Destination<select className="mt-2 w-full rounded-lg border bg-background p-2" value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Select {targetType}</option>{targets.map(t=><option key={t.id} value={t.id}>{t.project_number||t.estimate_number ? `${t.project_number||t.estimate_number} · `:""}{t.name||t.title}</option>)}</select></label><label className="text-sm font-medium">Display units<select className="mt-2 w-full rounded-lg border bg-background p-2" value={unit} onChange={e=>setUnit(e.target.value as UnitMode)}><option value="imperial">Feet / inches</option><option value="metric">Centimeters</option></select></label></section>

    <section className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><div className="space-y-4 rounded-2xl border bg-card p-4"><div><h2 className="font-semibold">1. Capture & mark</h2><p className="text-sm text-muted-foreground">Keep the reference and target on the same flat plane. A longer reference generally improves accuracy.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={cameraOpen?stopCamera:startCamera} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">{cameraOpen?"Close Camera":"Open Live Camera"}</button><label className="cursor-pointer rounded-lg border px-4 py-2 font-semibold">Take / Choose Photo<input aria-label="Take measurement photo" type="file" accept="image/*" capture="environment" onChange={e=>choosePhoto(e.target.files?.[0]||null)} className="sr-only"/></label></div>{cameraError&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{cameraError}</p>}{cameraOpen&&<div className="space-y-2"><video ref={videoRef} playsInline muted className="max-h-[65vh] w-full rounded-xl bg-black object-contain"/><button type="button" onClick={captureCamera} className="w-full rounded-lg bg-green-600 px-4 py-3 font-bold text-white">Capture Measurement Photo</button></div>}{photo&&<><div className="rounded-lg bg-blue-50 p-3 text-sm font-semibold text-blue-900">{step}</div><canvas ref={canvasRef} onClick={tapCanvas} className="max-h-[65vh] w-full cursor-crosshair rounded-xl border object-contain"/><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-amber-500/15 px-3 py-1">1–2 reference</span><span className="rounded-full bg-green-500/15 px-3 py-1">3–4 target</span>{calibrationQuality&&<span className="rounded-full border px-3 py-1">Calibration: {calibrationQuality}</span>}<button type="button" onClick={resetPoints} className="rounded-full border px-3 py-1">Reset points</button></div></>}</div>

    <div className="space-y-4 rounded-2xl border bg-card p-4"><h2 className="font-semibold">2. Calibrate & verify</h2><div><p className="text-sm font-medium">Quick reference</p><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={()=>setReferencePreset(12)} className="rounded-full border px-3 py-1 text-xs">12 in tape</button><button type="button" onClick={()=>setReferencePreset(3.375)} className="rounded-full border px-3 py-1 text-xs">Credit card 3.375 in</button><button type="button" onClick={()=>setReferencePreset(11)} className="rounded-full border px-3 py-1 text-xs">US letter 11 in</button></div></div><label className="block text-sm">Known reference ({unit==="metric"?"cm":"inches"})<input type="number" min="0.01" step="0.01" value={Number(fromInches(reference,unit).toFixed(3))} onChange={e=>setReference(toInches(Number(e.target.value),unit))} className="mt-1 w-full rounded-lg border bg-background p-2"/></label><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">B.O.S. camera calculation</p><p className="text-3xl font-bold">{calculated?displayValue(calculated,unit):"—"}</p><p className="mt-1 text-xs text-muted-foreground">Calculated from the ratio between the marked reference and target.</p></div><label className="block text-sm font-semibold">Verified measurement ({unit==="metric"?"cm":"inches"})<input type="number" min="0.01" step="0.01" value={verified?Number(fromInches(verified,unit).toFixed(2)):""} onChange={e=>setVerified(toInches(Number(e.target.value),unit))} className="mt-1 w-full rounded-lg border bg-background p-2"/><span className="mt-1 block text-xs font-normal text-muted-foreground">B.O.S. fills this automatically after point 4. Adjust it only when a tape or laser confirms a correction.</span></label></div></section>

    <section className="grid gap-4 rounded-2xl border bg-card p-4 md:grid-cols-2"><label className="text-sm">Label<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Living room north wall" className="mt-1 w-full rounded-lg border bg-background p-2"/></label><label className="text-sm">Type<select value={measurementType} onChange={e=>setMeasurementType(e.target.value)} className="mt-1 w-full rounded-lg border bg-background p-2"><option value="length">Length</option><option value="width">Width</option><option value="height">Height</option><option value="opening">Opening</option><option value="area">Area reference</option><option value="other">Other</option></select></label><label className="text-sm md:col-span-2">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border bg-background p-2"/></label><div className="md:col-span-2"><button disabled={saving} onClick={save} className="rounded-lg bg-blue-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving?"Saving…":"Save Measurement"}</button>{message&&<p className="mt-2 text-sm">{message}</p>}</div></section>
    {targetId&&<section className="rounded-2xl border bg-card p-4"><h2 className="font-semibold">Saved measurements</h2><div className="mt-3 divide-y">{saved.length===0?<p className="py-4 text-sm text-muted-foreground">No measurements saved yet.</p>:saved.map(m=><div key={m.id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-medium">{m.label}</p><p className="text-xs text-muted-foreground">{m.measurement_type} · {m.confidence.replace("_"," ")}</p></div><strong>{displayValue(Number(m.value_inches),unit)}</strong></div>)}</div></section>}
  </div>;
}
