import type {
  ExecutiveDashboardData,
  DashboardMetric,
  DashboardActivityItem,
  ScheduleEvent,
} from "./types";

const metrics: DashboardMetric[] = [
  {
    id: "active-projects",
    icon: "P",
    titleKey: "dashboard.metricActiveProjects",
    value: 14,
    valueKind: "number",
    href: "/projects",
    tooltipKey: "dashboard.metricActiveProjectsTooltip",
    trendPercent: 9.4,
    subtitleKey: "dashboard.metricActiveProjectsSubtitle",
    trendLabelKey: "dashboard.metricActiveProjectsTrend",
    trendDirection: "up",
  },
  {
    id: "employees-working",
    icon: "E",
    titleKey: "dashboard.metricEmployeesWorking",
    value: 26,
    valueKind: "number",
    href: "/team",
    tooltipKey: "dashboard.metricEmployeesWorkingTooltip",
    trendPercent: 4.1,
    subtitleKey: "dashboard.metricEmployeesWorkingSubtitle",
    trendLabelKey: "dashboard.metricEmployeesWorkingTrend",
    trendDirection: "up",
  },
  {
    id: "open-estimates",
    icon: "S",
    titleKey: "dashboard.metricOpenEstimates",
    value: 9,
    valueKind: "number",
    href: "/estimates",
    tooltipKey: "dashboard.metricOpenEstimatesTooltip",
    trendPercent: -6.2,
    subtitleKey: "dashboard.metricOpenEstimatesSubtitle",
    trendLabelKey: "dashboard.metricOpenEstimatesTrend",
    trendDirection: "down",
  },
  {
    id: "open-invoices",
    icon: "I",
    titleKey: "dashboard.metricOpenInvoices",
    value: 12,
    valueKind: "number",
    href: "/invoices",
    tooltipKey: "dashboard.metricOpenInvoicesTooltip",
    trendPercent: -3.8,
    subtitleKey: "dashboard.metricOpenInvoicesSubtitle",
    trendLabelKey: "dashboard.metricOpenInvoicesTrend",
    trendDirection: "down",
  },
  {
    id: "revenue-this-month",
    icon: "$",
    titleKey: "dashboard.metricRevenueThisMonth",
    value: 248900,
    valueKind: "currency",
    href: "/dashboard",
    tooltipKey: "dashboard.metricRevenueThisMonthTooltip",
    trendPercent: 18.2,
    subtitleKey: "dashboard.metricRevenueThisMonthSubtitle",
    trendLabelKey: "dashboard.metricRevenueThisMonthTrend",
    trendDirection: "up",
  },
  {
    id: "health-score",
    icon: "AI",
    titleKey: "dashboard.metricHealthScore",
    value: 95,
    valueKind: "score",
    href: "/dashboard",
    tooltipKey: "dashboard.metricHealthScoreTooltip",
    trendPercent: 5,
    subtitleKey: "dashboard.metricHealthScoreSubtitle",
    trendLabelKey: "dashboard.metricHealthScoreTrend",
    trendDirection: "up",
  },
];

const activities: DashboardActivityItem[] = [
  {
    id: "activity-customer-created",
    icon: "C",
    category: "customer",
    timestampMinutesAgo: 12,
    user: "M. Rivera",
    avatarLabel: "MR",
    actionLabelKey: "dashboard.activityCustomerCreated",
    projectName: "Riverside Apartments",
  },
  {
    id: "activity-project-created",
    icon: "P",
    category: "project",
    timestampMinutesAgo: 28,
    user: "A. Flores",
    avatarLabel: "AF",
    actionLabelKey: "dashboard.activityProjectCreated",
    projectName: "Northpoint Medical",
  },
  {
    id: "activity-photo-uploaded",
    icon: "SC",
    category: "sitecam",
    timestampMinutesAgo: 48,
    user: "J. Carter",
    avatarLabel: "JC",
    actionLabelKey: "dashboard.activityPhotoUploaded",
    projectName: "Dock Expansion",
  },
  {
    id: "activity-estimate-approved",
    icon: "E",
    category: "estimate",
    timestampMinutesAgo: 60,
    user: "T. Nguyen",
    avatarLabel: "TN",
    actionLabelKey: "dashboard.activityEstimateApproved",
  },
  {
    id: "activity-invoice-paid",
    icon: "I",
    category: "invoice",
    timestampMinutesAgo: 120,
    user: "L. Patel",
    avatarLabel: "LP",
    actionLabelKey: "dashboard.activityInvoicePaid",
  },
  {
    id: "activity-employee-clocked-in",
    icon: "T",
    category: "team",
    timestampMinutesAgo: 180,
    user: "R. James",
    avatarLabel: "RJ",
    actionLabelKey: "dashboard.activityEmployeeClockedIn",
    projectName: "Roofing Phase 2",
  },
];

const schedule: ScheduleEvent[] = [
  {
    id: "schedule-1",
    period: "morning",
    timeLabel: "07:30 AM",
    titleKey: "dashboard.scheduleCrewKickoff",
    projectName: "Riverside Apartments",
    location: "North Yard",
    employeesAssigned: 5,
    status: "confirmed",
    href: "/projects",
  },
  {
    id: "schedule-2",
    period: "morning",
    timeLabel: "09:00 AM",
    titleKey: "dashboard.scheduleCustomerWalkthrough",
    projectName: "Northpoint Medical",
    location: "Building A",
    employeesAssigned: 2,
    status: "pending",
    href: "/projects",
  },
  {
    id: "schedule-3",
    period: "afternoon",
    timeLabel: "01:15 PM",
    titleKey: "dashboard.scheduleInspection",
    projectName: "Harper Residence",
    location: "Lot 7",
    employeesAssigned: 3,
    status: "confirmed",
    href: "/projects",
  },
  {
    id: "schedule-4",
    period: "evening",
    timeLabel: "05:45 PM",
    titleKey: "dashboard.scheduleMaterialDelivery",
    projectName: "Dock Expansion",
    location: "South Gate",
    employeesAssigned: 4,
    status: "travel",
    href: "/projects",
  },
];

export function getExecutiveDashboardMockData(): ExecutiveDashboardData {
  return {
    metrics,
    activities,
    projectHealth: {
      onScheduleCount: 9,
      atRiskCount: 3,
      behindScheduleCount: 2,
      projects: [
        {
          id: "p-1",
          projectName: "Project Oak",
          healthScore: 72,
          budgetStatusKey: "dashboard.projectBudgetOver",
          scheduleStatusKey: "dashboard.projectScheduleAtRisk",
          lastPhotoUpload: "2h",
          lastDailyReport: "Yesterday",
          currentPhase: "Rough-in",
          riskIndicator: "high",
          href: "/projects",
        },
        {
          id: "p-2",
          projectName: "Northpoint Medical",
          healthScore: 94,
          budgetStatusKey: "dashboard.projectBudgetHealthy",
          scheduleStatusKey: "dashboard.projectScheduleOnTrack",
          lastPhotoUpload: "35m",
          lastDailyReport: "Today",
          currentPhase: "Finishes",
          riskIndicator: "low",
          href: "/projects",
        },
        {
          id: "p-3",
          projectName: "Dock Expansion",
          healthScore: 81,
          budgetStatusKey: "dashboard.projectBudgetWatch",
          scheduleStatusKey: "dashboard.projectScheduleSlightDelay",
          lastPhotoUpload: "5h",
          lastDailyReport: "Today",
          currentPhase: "Framing",
          riskIndicator: "medium",
          href: "/projects",
        },
      ],
    },
    schedule,
    weather: {
      location: "Austin, TX",
      temperatureF: 86,
      conditionKey: "dashboard.weatherConditionPartlyCloudy",
      windMph: 14,
      rainProbabilityPercent: 35,
      highF: 92,
      lowF: 74,
      tomorrow: {
        conditionKey: "dashboard.weatherConditionRainLikely",
        highF: 88,
        lowF: 71,
        rainProbabilityPercent: 72,
      },
    },
    businessScore: {
      score: 95,
      ratingKey: "dashboard.businessScoreExcellent",
      breakdown: [
        {
          id: "projects",
          labelKey: "dashboard.businessScoreProjects",
          score: 97,
          detailsKey: "dashboard.businessScoreProjectsDetails",
        },
        {
          id: "financial",
          labelKey: "dashboard.businessScoreFinancial",
          score: 92,
          detailsKey: "dashboard.businessScoreFinancialDetails",
        },
        {
          id: "scheduling",
          labelKey: "dashboard.businessScoreScheduling",
          score: 94,
          detailsKey: "dashboard.businessScoreSchedulingDetails",
        },
        {
          id: "documentation",
          labelKey: "dashboard.businessScoreDocumentation",
          score: 96,
          detailsKey: "dashboard.businessScoreDocumentationDetails",
        },
        {
          id: "safety",
          labelKey: "dashboard.businessScoreSafety",
          score: 98,
          detailsKey: "dashboard.businessScoreSafetyDetails",
        },
      ],
    },
    businessSummary: null,
    recommendations: [
      {
        id: "rec-project-oak-behind",
        icon: "P",
        priority: "high",
        timestampMinutesAgo: 5,
        messageKey: "dashboard.recommendationProjectOak",
        actions: [
          {
            id: "review-project",
            labelKey: "dashboard.actionReviewProject",
            intent: "primary",
          },
          {
            id: "dismiss-project",
            labelKey: "dashboard.actionDismiss",
            intent: "ghost",
          },
        ],
      },
      {
        id: "rec-invoice-overdue",
        icon: "I",
        priority: "critical",
        timestampMinutesAgo: 16,
        messageKey: "dashboard.recommendationInvoiceOverdue",
        actions: [
          {
            id: "view-invoice",
            labelKey: "dashboard.actionViewInvoice",
            intent: "secondary",
          },
          {
            id: "send-reminder",
            labelKey: "dashboard.actionSendReminder",
            intent: "primary",
          },
        ],
      },
      {
        id: "rec-rain-delay",
        icon: "W",
        priority: "medium",
        timestampMinutesAgo: 22,
        messageKey: "dashboard.recommendationRainDelay",
        actions: [
          {
            id: "reschedule-crew",
            labelKey: "dashboard.actionRescheduleCrew",
            intent: "primary",
          },
          {
            id: "dismiss-weather",
            labelKey: "dashboard.actionDismiss",
            intent: "ghost",
          },
        ],
      },
      {
        id: "rec-electricians-available",
        icon: "T",
        priority: "low",
        timestampMinutesAgo: 33,
        messageKey: "dashboard.recommendationElectricians",
        actions: [
          {
            id: "review-project-team",
            labelKey: "dashboard.actionReviewProject",
            intent: "secondary",
          },
          {
            id: "dismiss-team",
            labelKey: "dashboard.actionDismiss",
            intent: "ghost",
          },
        ],
      },
      {
        id: "rec-missing-reports",
        icon: "R",
        priority: "high",
        timestampMinutesAgo: 41,
        messageKey: "dashboard.recommendationMissingReports",
        actions: [
          {
            id: "send-reminder-reports",
            labelKey: "dashboard.actionSendReminder",
            intent: "primary",
          },
          {
            id: "dismiss-reports",
            labelKey: "dashboard.actionDismiss",
            intent: "ghost",
          },
        ],
      },
    ],
    pendingFollowups: [
      {
        id: "f-1",
        estimateNumber: "EST-4120",
        title: "Northpoint finish package",
        status: "viewed",
        dueAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        daysOverdue: 2,
        href: "/estimates",
      },
    ],
    automationQueue: [
      {
        runId: "estimate-approved-workflow:evt-100",
        ruleId: "estimate-approved-workflow",
        triggerEvent: "estimate.approved",
        startedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        status: "running",
        relatedEstimateId: "est-100",
        relatedProjectId: null,
      },
    ],
    recentAutomations: [
      {
        id: "a-1",
        runId: "estimate-approved-workflow:evt-050",
        ruleId: "estimate-approved-workflow",
        triggerEvent: "estimate.approved",
        completedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        status: "completed",
        durationMs: 930,
        href: "/projects",
      },
    ],
    estimatePipeline: {
      total: 9,
      draft: 2,
      sent: 3,
      viewed: 1,
      revisionRequested: 1,
      approved: 2,
      rejected: 0,
    },
    topPriorities: [
      {
        id: "d-1",
        priority: "critical",
        category: "finance",
        title: "Deposit overdue",
        summary: "One deposit invoice is overdue.",
        recommendation: "Follow up with customer and collect deposit.",
        actionLabel: "Open Invoice",
        actionHref: "/invoices",
        detectedAt: new Date().toISOString(),
        status: "new",
      },
    ],
    businessHealth: [
      { id: "sales", score: 82, rating: "Good" },
      { id: "operations", score: 74, rating: "Attention" },
      { id: "financial", score: 68, rating: "Attention" },
      { id: "scheduling", score: 79, rating: "Good" },
      { id: "customer", score: 84, rating: "Good" },
      { id: "overall", score: 77, rating: "Good" },
    ],
    riskSummary: {
      critical: 1,
      high: 2,
      medium: 1,
      low: 0,
    },
    decisionRecommendations: [
      {
        id: "d-2",
        priority: "high",
        category: "projects",
        title: "Project delayed",
        summary: "Project Oak Ridge has blocked work.",
        recommendation: "Review blocked tasks and rebalance labor.",
        actionLabel: "Open Project",
        actionHref: "/projects",
        detectedAt: new Date().toISOString(),
        status: "new",
      },
    ],
    todaysDecisions: [
      {
        id: "d-3",
        priority: "medium",
        category: "estimates",
        title: "Estimate viewed but not approved",
        summary: "Estimate EST-4220 was viewed and is still pending.",
        recommendation: "Send a customer follow-up reminder.",
        actionLabel: "Open Estimate",
        actionHref: "/estimates",
        detectedAt: new Date().toISOString(),
        status: "new",
      },
    ],
    criticalAlerts: [
      {
        id: "d-4",
        priority: "critical",
        category: "operations",
        title: "High automation failure rate",
        summary: "Automation failures exceeded threshold in the last day.",
        recommendation: "Review automation failure logs.",
        actionLabel: "Open Schedule",
        actionHref: "/dashboard",
        detectedAt: new Date().toISOString(),
        status: "new",
      },
    ],
    morningBriefing: {
      greeting: "Good Morning Bango.",
      lines: [
        "2 estimates need follow-up.",
        "One deposit is overdue.",
        "Crew Alpha has no work tomorrow.",
      ],
    },
    widgetDefinitions: [
      {
        id: "kpi",
        titleKey: "dashboard.metricSectionTitle",
        descriptionKey: "dashboard.metricSectionDescription",
      },
      {
        id: "schedule",
        titleKey: "dashboard.todaySchedule",
        descriptionKey: "dashboard.todayScheduleDescription",
      },
      {
        id: "project-health",
        titleKey: "dashboard.projectHealth",
        descriptionKey: "dashboard.projectHealthDescription",
      },
      {
        id: "weather",
        titleKey: "dashboard.weather",
        descriptionKey: "dashboard.weatherDescription",
      },
      {
        id: "activity",
        titleKey: "dashboard.recentActivity",
        descriptionKey: "dashboard.recentActivityDescription",
      },
      {
        id: "pending-followups",
        titleKey: "dashboard.pendingFollowupsTitle",
        descriptionKey: "dashboard.pendingFollowupsDescription",
      },
      {
        id: "automation-queue",
        titleKey: "dashboard.automationQueueTitle",
        descriptionKey: "dashboard.automationQueueDescription",
      },
      {
        id: "recent-automations",
        titleKey: "dashboard.recentAutomationsTitle",
        descriptionKey: "dashboard.recentAutomationsDescription",
      },
      {
        id: "estimate-pipeline",
        titleKey: "dashboard.estimatePipelineTitle",
        descriptionKey: "dashboard.estimatePipelineDescription",
      },
      {
        id: "top-priorities",
        titleKey: "dashboard.topPrioritiesTitle",
        descriptionKey: "dashboard.topPrioritiesDescription",
      },
      {
        id: "business-health",
        titleKey: "dashboard.businessHealthTitle",
        descriptionKey: "dashboard.businessHealthDescription",
      },
      {
        id: "risk-summary",
        titleKey: "dashboard.riskSummaryTitle",
        descriptionKey: "dashboard.riskSummaryDescription",
      },
      {
        id: "decision-recommendations",
        titleKey: "dashboard.decisionRecommendationsTitle",
        descriptionKey: "dashboard.decisionRecommendationsDescription",
      },
      {
        id: "todays-decisions",
        titleKey: "dashboard.todaysDecisionsTitle",
        descriptionKey: "dashboard.todaysDecisionsDescription",
      },
      {
        id: "critical-alerts",
        titleKey: "dashboard.criticalAlertsTitle",
        descriptionKey: "dashboard.criticalAlertsDescription",
      },
      {
        id: "business-score",
        titleKey: "dashboard.businessScoreTitle",
        descriptionKey: "dashboard.businessScoreDescription",
      },
      {
        id: "command-center",
        titleKey: "dashboard.commandCenterTitle",
        descriptionKey: "dashboard.commandCenterDescription",
      },
    ],
  };
}
