import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const read = (path: string) => readFileSync(fileURLToPath(new URL(path, import.meta.url)), "utf8");
const handlers = read("../orion/commands/handlers.ts");
const email = read("./contract-email.ts");
assert.match(handlers, /customers\(email, first_name\)/, "Orion send must load the company-scoped estimate recipient");
assert.match(handlers, /customer\?\.email\?\.trim\(\)/, "Orion send must reject estimates without a customer email");
assert.match(handlers, /await sendContractEmail\(/, "Orion send must call the real contract email provider");
assert.match(handlers, /idempotencyKey: `orion-estimate-send\/\$\{context\.idempotencyKey\}`/, "provider retries must use a stable Resend idempotency key");
assert.match(handlers, /if \(!delivery\.delivered\)/, "provider rejection must stop the command before sent status is recorded");
assert.ok(handlers.indexOf("if (!delivery.delivered)") < handlers.indexOf('.update({\n      status:'), "estimate sent status must follow provider acceptance");
assert.match(handlers, /provider_message_id: delivery\.providerId/, "delivery evidence must include the provider message ID");
assert.match(handlers, /delivery_status: "accepted"/, "events must record provider acceptance rather than claiming inbox delivery");
assert.match(handlers, /accepted for delivery to/, "Orion's message must accurately describe provider acceptance");
assert.match(email, /VERCEL_PROJECT_PRODUCTION_URL/, "server commands must build links from a configured production origin");
assert.match(email, /encodeURIComponent\(token\)/, "contract tokens must be safely encoded into the public URL");
assert.match(email, /"Idempotency-Key"/, "the delivery adapter must send provider idempotency evidence");
assert.match(handlers, /Email was accepted, but BOS could not update/, "post-acceptance persistence failures must not encourage duplicate delivery");
console.log("Orion estimate email-delivery contract passed");
