begin;
create table public.project_submittals(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,project_id uuid not null,submittal_number integer not null,title text not null check(btrim(title)<>''),description text,discipline text not null default 'General',status text not null default 'draft' check(status in('draft','submitted','under_review','approved','approved_as_noted','revise_resubmit','rejected','closed','void')),due_date date,submitted_at timestamptz,reviewed_at timestamptz,created_by uuid not null,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(project_id,company_id) references public.projects(id,company_id) on delete cascade,foreign key(created_by,company_id) references public.profiles(id,company_id) on delete restrict,foreign key(updated_by,company_id) references public.profiles(id,company_id) on delete set null,unique(company_id,project_id,submittal_number));
create index project_submittals_project_status_idx on public.project_submittals(company_id,project_id,status,due_date);
alter table public.project_submittals enable row level security;
create policy project_submittals_select on public.project_submittals for select to authenticated using(public.is_company_member(company_id));
create policy project_submittals_insert on public.project_submittals for insert to authenticated with check(public.is_company_member(company_id) and public.blueprint_project_belongs_to_company(project_id,company_id) and created_by=auth.uid());
create policy project_submittals_update on public.project_submittals for update to authenticated using(public.is_company_member(company_id)) with check(public.is_company_member(company_id) and public.blueprint_project_belongs_to_company(project_id,company_id));
alter table public.blueprint_operational_links drop constraint if exists blueprint_operational_links_target_type_check;
alter table public.blueprint_operational_links add constraint blueprint_operational_links_target_type_check check(target_type in('task','estimate_line_item','change_order','rfi','punch_item','workforce_assignment','submittal'));
create or replace function public.create_submittal_from_blueprint_issue(p_company_id uuid,p_project_id uuid,p_blueprint_version_id uuid,p_annotation_id uuid) returns uuid language plpgsql security invoker set search_path=public,pg_temp as $$
declare v_annotation public.blueprint_annotations%rowtype;v_id uuid;v_number integer;
begin
if auth.uid() is null or not public.is_company_member(p_company_id) then raise exception 'Blueprint submittal creation is not authorized.' using errcode='42501';end if;
select * into v_annotation from public.blueprint_annotations where id=p_annotation_id and company_id=p_company_id and project_id=p_project_id and blueprint_version_id=p_blueprint_version_id and annotation_type='pin';if not found then raise exception 'Blueprint issue pin was not found.' using errcode='P0002';end if;
select target_id into v_id from public.blueprint_operational_links where company_id=p_company_id and project_id=p_project_id and annotation_id=p_annotation_id and target_type='submittal' order by created_at limit 1;if v_id is not null then return v_id;end if;
perform pg_advisory_xact_lock(hashtext('project-submittal:'||p_project_id::text));select coalesce(max(submittal_number),0)+1 into v_number from public.project_submittals where company_id=p_company_id and project_id=p_project_id;
insert into public.project_submittals(company_id,project_id,submittal_number,title,description,discipline,status,due_date,created_by) values(p_company_id,p_project_id,v_number,coalesce(nullif(btrim(v_annotation.content),''),'Blueprint submittal'),'Created from Blueprint issue pin '||p_annotation_id::text||' on revision '||p_blueprint_version_id::text||'.',v_annotation.discipline,'draft',v_annotation.due_at::date,auth.uid()) returning id into v_id;
insert into public.blueprint_operational_links(company_id,project_id,blueprint_version_id,annotation_id,target_type,target_id,created_by) values(p_company_id,p_project_id,p_blueprint_version_id,p_annotation_id,'submittal',v_id,auth.uid());
insert into public.workflow_events(company_id,workflow_name,event_type,current_state,next_state,actor_profile_id,reference_entity,reference_id,source_module,payload,metadata,idempotency_key) values(p_company_id,'blueprint_issue_submittal','submittal.created',null,'draft',auth.uid(),'project_submittal',v_id,'projects',jsonb_build_object('project_id',p_project_id,'submittal_number',v_number,'annotation_id',p_annotation_id,'blueprint_version_id',p_blueprint_version_id,'page_number',greatest(coalesce((v_annotation.geometry->>'page')::integer,1),1)),jsonb_build_object('project_id',p_project_id),'blueprint:submittal:'||p_annotation_id::text) on conflict(company_id,event_type,idempotency_key) where idempotency_key is not null do nothing;return v_id;end;$$;
revoke all on function public.create_submittal_from_blueprint_issue(uuid,uuid,uuid,uuid) from public;grant execute on function public.create_submittal_from_blueprint_issue(uuid,uuid,uuid,uuid) to authenticated;
commit;
