begin;

-- ---------------------------------------------------------------------------
-- Public contract token revision binding + atomic signature finalization.
--
-- A bearer link must authorize exactly the estimate revision that existed when
-- the link was issued.  The final legal state transition must also serialize
-- against the home-solicitation cancellation RPC so a cancellation and a
-- signature cannot cross in flight and leave contradictory evidence.
-- ---------------------------------------------------------------------------

create or replace function public.validate_estimate_public_token(
  p_token text,
  p_ip_address text default null,
  p_user_agent text default null
)
returns table (
  token_id uuid,
  company_id uuid,
  estimate_id uuid,
  expires_at timestamptz,
  is_valid boolean,
  failure_reason text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_token_hash text;
  v_row public.estimate_public_tokens%rowtype;
  v_estimate_version integer;
  v_deleted_at timestamptz;
  v_archived_at timestamptz;
  v_issued_version_text text;
begin
  if p_token is null or btrim(p_token) = '' then
    return query
      select null::uuid, null::uuid, null::uuid, null::timestamptz, false, 'token_missing'::text;
    return;
  end if;

  -- Keep the digest input bounded. Contract tokens generated by B.O.S. are far
  -- shorter than this; oversized values are never legitimate bearer links.
  if char_length(p_token) > 512 then
    return query
      select null::uuid, null::uuid, null::uuid, null::timestamptz, false, 'token_malformed'::text;
    return;
  end if;

  v_token_hash := encode(extensions.digest(p_token, 'sha256'::text), 'hex');

  select *
    into v_row
  from public.estimate_public_tokens t
  where t.token_hash = v_token_hash
  limit 1;

  if not found then
    return query
      select null::uuid, null::uuid, null::uuid, null::timestamptz, false, 'token_not_found'::text;
    return;
  end if;

  if v_row.revoked_at is not null then
    return query
      select v_row.id, v_row.company_id, v_row.estimate_id, v_row.expires_at, false, 'token_revoked'::text;
    return;
  end if;

  if v_row.expires_at <= now() then
    return query
      select v_row.id, v_row.company_id, v_row.estimate_id, v_row.expires_at, false, 'token_expired'::text;
    return;
  end if;

  select e.version_number, e.deleted_at, e.archived_at
    into v_estimate_version, v_deleted_at, v_archived_at
  from public.estimates e
  where e.id = v_row.estimate_id
    and e.company_id = v_row.company_id;

  if not found or v_deleted_at is not null or v_archived_at is not null then
    return query
      select v_row.id, v_row.company_id, v_row.estimate_id, v_row.expires_at, false, 'estimate_unavailable'::text;
    return;
  end if;

  v_issued_version_text := coalesce(v_row.metadata ->> 'estimate_version', '');
  if v_issued_version_text !~ '^[0-9]+$' then
    return query
      select v_row.id, v_row.company_id, v_row.estimate_id, v_row.expires_at, false, 'token_revision_missing'::text;
    return;
  end if;

  if v_issued_version_text::integer <> v_estimate_version then
    return query
      select v_row.id, v_row.company_id, v_row.estimate_id, v_row.expires_at, false, 'token_stale_revision'::text;
    return;
  end if;

  update public.estimate_public_tokens
     set view_count = view_count + 1,
         last_viewed_at = now(),
         last_viewed_ip = coalesce(nullif(btrim(coalesce(p_ip_address, '')), ''), last_viewed_ip),
         last_viewed_user_agent = coalesce(nullif(left(btrim(coalesce(p_user_agent, '')), 1000), ''), last_viewed_user_agent),
         updated_at = now()
   where id = v_row.id;

  return query
    select v_row.id, v_row.company_id, v_row.estimate_id, v_row.expires_at, true, null::text;
end;
$$;

revoke all on function public.validate_estimate_public_token(text, text, text) from public;
grant execute on function public.validate_estimate_public_token(text, text, text) to anon, authenticated, service_role;

create or replace function public.finalize_verified_estimate_contract_signature(
  p_company_id uuid,
  p_estimate_id uuid,
  p_public_token_id uuid,
  p_signature_id uuid,
  p_agreement_version_id uuid,
  p_agreement_snapshot jsonb,
  p_agreement_hash text,
  p_signed_at timestamptz,
  p_actor_profile_id uuid,
  p_signature_metadata jsonb,
  p_acceptance_idempotency_key text,
  p_home_solicitation_applicable boolean default false,
  p_cancellation_deadline_date date default null
)
returns table(
  project_id uuid,
  cancellation_deadline_date date,
  idempotent boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_est public.estimates%rowtype;
  v_token public.estimate_public_tokens%rowtype;
  v_signature public.estimate_signatures%rowtype;
  v_profile public.estimate_home_solicitation_profiles%rowtype;
  v_project_id uuid;
  v_issued_version_text text;
  v_signed_at timestamptz := coalesce(p_signed_at, now());
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Service role required.' using errcode = '42501';
  end if;

  if p_company_id is null or p_estimate_id is null or p_public_token_id is null
     or p_signature_id is null or p_agreement_version_id is null
     or p_actor_profile_id is null or p_agreement_snapshot is null
     or nullif(btrim(coalesce(p_agreement_hash, '')), '') is null
     or nullif(btrim(coalesce(p_acceptance_idempotency_key, '')), '') is null then
    raise exception 'Contract finalization identity and evidence are required.' using errcode = '22023';
  end if;

  -- This is the same lock key used by record_verified_home_solicitation_cancellation.
  -- Whichever legal action obtains it first completes atomically before the other
  -- can inspect or alter the transaction.
  perform pg_advisory_xact_lock(hashtextextended('home-solicitation-cancel:' || p_estimate_id::text, 0));

  select * into v_token
  from public.estimate_public_tokens t
  where t.id = p_public_token_id
    and t.company_id = p_company_id
    and t.estimate_id = p_estimate_id
  for update;

  if not found or v_token.revoked_at is not null or v_token.expires_at <= now() then
    raise exception 'CONTRACT_TOKEN_NO_LONGER_VALID' using errcode = '42501';
  end if;

  v_issued_version_text := coalesce(v_token.metadata ->> 'estimate_version', '');
  if v_issued_version_text !~ '^[0-9]+$' then
    raise exception 'CONTRACT_TOKEN_REVISION_MISSING' using errcode = '23514';
  end if;

  select * into v_est
  from public.estimates e
  where e.id = p_estimate_id
    and e.company_id = p_company_id
  for update;

  if not found or v_est.deleted_at is not null or v_est.archived_at is not null then
    raise exception 'ESTIMATE_UNAVAILABLE' using errcode = 'P0002';
  end if;

  if v_issued_version_text::integer <> v_est.version_number then
    raise exception 'CONTRACT_TOKEN_STALE_REVISION' using errcode = '23514';
  end if;

  if v_est.status = 'void' then
    raise exception 'TRANSACTION_CANCELLED' using errcode = '23514';
  end if;

  if v_est.status = 'approved' then
    if v_est.approval_signature_id = p_signature_id then
      return query select coalesce(v_est.converted_project_id, v_est.project_id), p_cancellation_deadline_date, true;
      return;
    end if;
    raise exception 'ESTIMATE_ALREADY_SIGNED' using errcode = '23505';
  end if;

  if p_home_solicitation_applicable then
    select * into v_profile
    from public.estimate_home_solicitation_profiles p
    where p.company_id = p_company_id
      and p.estimate_id = p_estimate_id
    for update;

    if not found then
      raise exception 'HOME_SOLICITATION_PROFILE_REQUIRED' using errcode = '23514';
    end if;
    if v_profile.cancelled_at is not null then
      raise exception 'TRANSACTION_CANCELLED' using errcode = '23514';
    end if;
    if p_cancellation_deadline_date is null then
      raise exception 'CANCELLATION_DEADLINE_REQUIRED' using errcode = '23514';
    end if;
  end if;

  if not exists (
    select 1 from public.estimate_agreement_versions av
    where av.id = p_agreement_version_id
      and av.company_id = p_company_id
      and av.estimate_id = p_estimate_id
  ) then
    raise exception 'AGREEMENT_VERSION_MISMATCH' using errcode = '23514';
  end if;

  select * into v_signature
  from public.estimate_signatures s
  where s.id = p_signature_id
    and s.company_id = p_company_id
    and s.estimate_id = p_estimate_id
    and s.agreement_version_id = p_agreement_version_id
    and s.public_token_id = p_public_token_id
  for update;

  if not found then
    raise exception 'SIGNATURE_EVIDENCE_MISMATCH' using errcode = '23514';
  end if;

  if exists (
    select 1 from public.estimate_signatures s
    where s.company_id = p_company_id
      and s.estimate_id = p_estimate_id
      and s.verification_result = 'verified'
      and s.id <> p_signature_id
  ) then
    raise exception 'ESTIMATE_ALREADY_HAS_VERIFIED_SIGNATURE' using errcode = '23505';
  end if;

  update public.estimate_signatures
     set verification_result = 'verified',
         metadata = coalesce(p_signature_metadata, '{}'::jsonb)
   where id = p_signature_id
     and company_id = p_company_id
     and estimate_id = p_estimate_id;

  update public.estimates
     set agreement_version_id = p_agreement_version_id,
         agreement_snapshot = p_agreement_snapshot,
         agreement_hash = p_agreement_hash,
         approval_signature_id = p_signature_id,
         status = 'approved',
         approved_at = v_signed_at,
         updated_at = v_signed_at
   where id = p_estimate_id
     and company_id = p_company_id;

  if p_home_solicitation_applicable then
    update public.estimate_home_solicitation_profiles
       set transaction_signed_at = v_signed_at,
           cancellation_deadline_date = p_cancellation_deadline_date,
           updated_at = v_signed_at
     where company_id = p_company_id
       and estimate_id = p_estimate_id;
  end if;

  if not exists (
    select 1 from public.estimate_acceptance_events ae
    where ae.company_id = p_company_id
      and ae.estimate_id = p_estimate_id
      and ae.idempotency_key = p_acceptance_idempotency_key
  ) then
    insert into public.estimate_acceptance_events(
      company_id, estimate_id, signature_id, event_type, actor_type,
      actor_profile_id, idempotency_key, metadata
    ) values (
      p_company_id, p_estimate_id, p_signature_id, 'signed', 'customer',
      null, p_acceptance_idempotency_key,
      jsonb_build_object('agreement_hash', p_agreement_hash)
    );
  end if;

  select c.project_id into v_project_id
  from public.convert_verified_estimate_contract(
    p_company_id,
    p_estimate_id,
    p_signature_id,
    p_actor_profile_id
  ) c
  limit 1;

  if v_project_id is not null and p_home_solicitation_applicable then
    update public.projects
       set contract_compliance_hold_active = true,
           contract_compliance_hold_until = ((p_cancellation_deadline_date + 1)::timestamp at time zone 'America/New_York'),
           contract_compliance_hold_reason = 'Ohio home-solicitation cancellation period',
           updated_at = v_signed_at
     where company_id = p_company_id
       and id = v_project_id;
  end if;

  return query select v_project_id, p_cancellation_deadline_date, false;
end;
$$;

revoke execute on function public.finalize_verified_estimate_contract_signature(
  uuid,uuid,uuid,uuid,uuid,jsonb,text,timestamptz,uuid,jsonb,text,boolean,date
) from public, anon, authenticated;
grant execute on function public.finalize_verified_estimate_contract_signature(
  uuid,uuid,uuid,uuid,uuid,jsonb,text,timestamptz,uuid,jsonb,text,boolean,date
) to service_role;

commit;
