import type { DailyChecklist } from "./mobile-field-operations-types";

const DATABASE_NAME="bango-field-checklist-drafts",STORE_NAME="drafts",DATABASE_VERSION=1;
type StoredDraft={key:string;checklist:DailyChecklist;updatedAt:string};
function openDatabase():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DATABASE_NAME,DATABASE_VERSION);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE_NAME))request.result.createObjectStore(STORE_NAME,{keyPath:"key"});};request.onsuccess=()=>{request.result.onversionchange=()=>request.result.close();resolve(request.result);};request.onerror=()=>reject(request.error??new Error("Unable to open checklist draft storage."));request.onblocked=()=>reject(new Error("Checklist draft storage is blocked by another session."));});}
function transaction<T>(mode:IDBTransactionMode,operation:(store:IDBObjectStore)=>IDBRequest<T>):Promise<T>{return openDatabase().then(database=>new Promise<T>((resolve,reject)=>{const tx=database.transaction(STORE_NAME,mode),request=operation(tx.objectStore(STORE_NAME));let result!:T;request.onsuccess=()=>{result=request.result;};request.onerror=()=>reject(request.error??new Error("Unable to access checklist draft storage."));tx.oncomplete=()=>{database.close();resolve(result);};tx.onerror=()=>{database.close();reject(tx.error??new Error("Unable to commit checklist draft storage."));};tx.onabort=()=>{database.close();reject(tx.error??new Error("Checklist draft storage was cancelled."));};}));}
export function createMobileChecklistDraftStore(resolveScope:()=>Promise<{companyId:string;userId:string}>){const keyFor=async(crewId:string)=>{const scope=await resolveScope();return `${scope.companyId}:${scope.userId}:${crewId}`;};return{
  async load(crewId:string){const key=await keyFor(crewId),saved=await transaction<StoredDraft|undefined>("readonly",store=>store.get(key));return saved?.checklist??null;},
  async save(crewId:string,checklist:DailyChecklist){const key=await keyFor(crewId);await transaction("readwrite",store=>store.put({key,checklist,updatedAt:new Date().toISOString()} satisfies StoredDraft));},
  async remove(crewId:string){const key=await keyFor(crewId);await transaction("readwrite",store=>store.delete(key));},
};}
